### ISSUE TITLE
Change HTTPS Everywhere icon behavior to be more similar to other extensions

### ISSUE THREAD

**Issue by vgturtle127** [EFForg/https-everywhere#3139] opened 2015-10-29 00:56 UTC
This seems like small changes that could really help the extension.

When you are using any number of encrypted sites, the HTTPS Everywhere counter is on the right and is rather tall. I would recommend making it a small rounded square at the upper right. That way it not only looks similar to other extensions, but it also will decrease the potential of a user miscounting because another extension has a number right next to it.

Privacy Badger already has this implemented, and since you guys made that I would assume you could just steal from yourselves. :smiley: 

You could make it grey like the ad blockers, or you could make it red like Privacy Badger so there was some unification.

I would also recommend getting rid of the arrow next to the icon. Clicking on the icon assumes you will get some sort of menu or options, every extension that has an icon like that has some sort of clickable action.

I hope this is an easy change to make. :smile: 

Thanks for listening.

**Comment by foobar13373** [comment] 2015-10-31 16:38
Totally agree. Would love to see these changes as the current look always bothered me.

**Comment by vgturtle127** [comment] 2015-11-03 08:02
It isn't horrible by any means, I have seen worse. But the difference is noticeable and it also is mostly likely a simple small change.

Also, what is it with GitHub and not letting users pick labels?

**Comment by fuglede** [comment] 2015-11-03 20:16
Duplicate of #2470?

**Comment by vgturtle127** [comment] 2015-11-05 06:09
I expanded upon it, and I find it odd that GitHub didn't catch the similarities in content for both issues.

It should be worth noting that the issue was also left alone for 2+ months, so maybe switch to this issue since we have also expanded upon the issue?

>! Also as an FYI, Mozilla's plan to deprecate XPCOM may mean that in the long run (18 months), XUL is no longer a thing, and we have to migrate to the WebExtensions style of doing things: https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/. I'm guessing that button styling will be different in that world too.

Also, we should keep this in mind for whatever changes are eventually made.

Has any work been done to progress any of the goals in either issue? I can't tell since the development builds I am using are currently broken due to some changes I am making to my build systems and what not.

**Comment by vgturtle127** [comment] 2015-12-17 03:56
@fuglede Since Firefox 43.0 is out, has anything changed in terms of what you guys want to do with the UI in regards to this issue as well as #2470 and #1697? I know XUL and XPCOM are being phased out, so the UI has to pretty much has to change anyway, but I think upgrading won't be too difficult if we plan ahead.

**Comment by fuglede** [comment] 2015-12-26 17:15
I'd ask @jsha but since my logic of "let's just copy the styling from the SDK" didn't exactly pan out, I imagine that any effort would be better spent towards porting the add-on to WebExtensions.

**Comment by vgturtle127** [comment] 2016-02-21 03:41
@fuglede @jsha Agreed, a WebExtensions port is a good idea. Updating the icon to better fix the standard would be good if you guys aren't planning on working on it for awhile, though.

**Comment by pipboy96** [comment] 2019-03-28 18:17
Currently, the counter looks exactly like uBlock Origin's counter.

**Closed** 2019-03-28 18:16 UTC
Labels: ui
