### ISSUE TITLE
Problem with insecure content on gmx.com home page

### ISSUE THREAD

**Issue by notfoss** [EFForg/https-everywhere#1895] opened 2015-06-10 04:38 UTC
With the GMX rule on gmx.com, insecure content is loaded, resulting in the following:

<a href='http://postimg.org/image/i7foi30oh/' target='_blank'><img src='http://s8.postimg.org/i7foi30oh/2015_06_10_095511.jpg' border='0' alt="2015 06 10 095511" /></a>

**Comment by KommX** [comment] 2015-06-10 07:32
I can't reproduce this issue with the latest FF on Ubuntu 15.04.

![gmx com](https://cloud.githubusercontent.com/assets/7859245/8077102/0b20a068-0f53-11e5-8661-033353a63d32.png)

**Comment by notfoss** [comment] 2015-06-10 08:59
I can reproduce it with a clean profile, even without using HTTPS everywhere, i.e., simply going to https://www.gmx.com

You can see the insecure elements in the screenshot:
<a href='http://postimg.org/image/bmb4w37qf/' target='_blank'><img src='http://s23.postimg.org/bmb4w37qf/2015_06_10_142001.jpg' border='0' alt="2015 06 10 142001" /></a>

I am on Arch Linux using Firefox 38.0.5

**Comment by KommX** [comment] 2015-06-10 09:19
And by clean profile you mean without any other add-ons?

btw: If this happens without using HTTPS everywhere this can't be a HTTPS everywhere bug...

**Comment by notfoss** [comment] 2015-06-10 09:25
Yes, by clean profile, I meant without any add-ons.

As for it not being an HTTPS everywhere bug, gmx.com doesn't support https for all elements on the home page. HTTPS everywhere simple forces that and the breakage occurs.

**Comment by KommX** [comment] 2015-06-10 10:51
Can anyone else reproduce this error? I can't.

**Comment by donced** [comment] 2015-07-10 07:48
I can reproduce. It's caused by MCB due to i[0-9].gmx.com unable to serve HTTPS. Ruleset updated.

**Comment by wizwuz** [comment] 2015-07-24 13:21
Latest modifications also changed the gmx.net rule (as well as .de, .at...), now it redirects to gmx.ch.
This is not needed as gmx.net supports https, and it is separate domain.
Before this change, previous rule has been happily there for many years.

Can this be please reverted back to the previous rule for gmx.net?

One thing is redirecting from http to https, completely different is to redirect to another domain (some people call that hijacking!). I don't believe that's the intention of HTTPS Everywhere...

**Comment by donced** [comment] 2015-07-27 02:04
I made a mistake by pre-empting the server's redirection, which isn't necessary since the server redirects just fine. I have made the changes. However, do note that domain rewrite is necessary is some cases (not in this case though) because SSL is served at different domain (http://example.com to https://s-example.com). There is also SSL cert that doesn't/only apply to www.

**Comment by galeksandrp** [comment] 2017-03-28 12:25
@J0WI Is this fixed by #2329?

**Comment by J0WI** [comment] 2017-03-28 14:13
LGTM, so I'm closing this.

**Closed by J0WI** 2017-03-28 14:13 UTC
Labels: ruleset-bug
