### ISSUE TITLE
HTTPS everywhere break acces to rmfon.pl

### ISSUE THREAD

**Issue by papsheetski** [EFForg/https-everywhere#14295] opened 2018-01-15 21:41 UTC
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: ruleset issue
Type: new ruleset
Type: code issue
Type: feature request
Type: other

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: rmfon.pl

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

Domain use http access, to view content have to disable https plugin.

**Comment by jeremyn** [comment] 2018-01-16 15:00
There's no ruleset for the domain `rmfon.pl`, see https://www.eff.org/https-everywhere/atlas/?rmfon.pl , so HTTPS Everywhere should not rewrite this domain to HTTPS. Do you have `Block all unencrypted requests` checked in the UI? If so, try turning that off. Otherwise, please be more specific about what is not working.

**Comment by papsheetski** [comment] 2018-01-22 21:56
Thank you Jeremy for your email. I had block unencrypted enabled, after turning off as you suggest, everything works perfect.

Thanks a mil.

On 16 Jan 2018, at 15:00, Jeremy Nation <notifications@github.com<mailto:notifications@github.com>> wrote:


There's no ruleset for the domain rmfon.pl, see https://www.eff.org/https-everywhere/atlas/?rmfon.pl , so HTTPS Everywhere should not rewrite this domain to HTTPS. Do you have Block all unencrypted requests checked in the UI? If so, try turning that off. Otherwise, please be more specific about what is not working.

**Comment by jeremyn** [comment] 2018-01-22 22:17
@papsheetski Thanks for letting us know. I'm closing this issue since the problem is resolved.

**Closed by jeremyn** 2018-01-22 22:17 UTC
