### ISSUE TITLE
Website not visualized, keeps "loading" forever

### ISSUE THREAD

**Issue by leodp** [EFForg/https-everywhere#7283] opened 2016-10-06 07:25 UTC
The website 
http://www.ksv-fechten.at/termine/
keeps on loading, without being visualized or giving any error message, looking as there is a very slow internet connection.

Please ignore if this is a known issue, I have searched a bit for similar bugs, then followed the "report" indication eff gives but I do not know the details of the reporting policy.

Ciao, Leo

**Comment by jeremyn** [comment] 2016-10-06 14:02
Thanks for the report. I can't reproduce this problem on Windows 10, Firefox or Chrome. Which browser are you using? Also, can you consistently reproduce the problem by deactivating and reactivating HTTPS Everywhere?

**Comment by leodp** [comment] 2016-10-06 14:33
Yes, I can reproduce it.
...and no. Now it works. I do not know what happened, I have not done anything, not even restarting Firefox. It works now.
The problem has been present continuoisly for one week, now it seems gone.

I'm on Linux 4.4.0-41-generic #61-Ubuntu SMP,  64bits i7 system
Firefox 49.0
HTTPS Everywhere #5.2.5.

On Chromium (Chrome) I could install HTTPS Everywhere 2016.9.21, there is no issue.

**Comment by jeremyn** [comment] 2016-10-06 14:37
Maybe it was an actual internet connection problem? Anyway I'm closing this issue but please feel free to reopen it with a comment if the problem consistently reappears.

**Comment by leodp** [comment] 2016-10-06 14:43
...wait: restarted FF, the problem appears again

**Comment by jeremyn** [comment] 2016-10-06 15:03
This really does not sound like an HTTPS Everywhere problem.

**Comment by jeremyn** [comment] 2016-10-06 15:03
Do you get any errors in the [Firefox Web Console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console) when you load the site with HTTPS Everywhere active?

**Comment by leodp** [comment] 2016-10-06 15:15
There are some messages which say something like:
Multiorigine request  blocked(cross-origin): the criterion of origin correspondence does not allow reading remote resource from http:// ...

Nothing else. (Messages are in italian, I can switch language but not today)

Bloccata richiesta multiorigine (cross-origin): il criterio di corrispondenza dell’origine non consente la lettura della risorsa remota da http://cdn.website-start.de/app/cdn/min/group/web.js?1473256848480. Motivo: header CORS “Access-Control-Allow-Origin” mancante.(sconosciuto)

Bloccata richiesta multiorigine (cross-origin): il criterio di corrispondenza dell’origine non consente la lettura della risorsa remota da http://cdn.website-start.de/s/build/web.bundle.js?1473256848480. Motivo: header CORS “Access-Control-Allow-Origin” mancante.(sconosciuto)

Bloccata richiesta multiorigine (cross-origin): il criterio di corrispondenza dell’origine non consente la lettura della risorsa remota da http://cdn.website-start.de/app/cdn/min/group/pfcsupport.js?1473256848480. Motivo: header CORS “Access-Control-Allow-Origin” mancante.(sconosciuto)

**Comment by Hainish** [comment] 2017-10-05 22:08
Closing for now as a legacy issue.  If the problem is still happening on the latest version, please respond and we can re-open.

**Closed** 2017-10-05 22:08 UTC
Labels: ruleset-bug
