### ISSUE TITLE
Extension doesn't redirect until disabled and re-enabled

### ISSUE THREAD

**Issue by BoffinBrain** [EFForg/https-everywhere#18110] opened 2019-06-20 07:09 UTC
Type: code issue

Firefox version: 67.0.3
Extension version: 2019.6.4

This has been an issue for at least 3 months but I didn't report it until now.

After starting Firefox fresh, when you visit a website that supports both HTTP and HTTPS and has no server-side redirects or HSTS/pin rules, I find that HTTPS Everywhere simply doesn't redirect as it should. Even adding a duplicate, custom rule doesn't do anything. If I go into Extensions and disable, then enable it again and refresh the tab, then it will redirect as expected.

**Comment by pipboy96** [comment] 2019-06-20 11:30
Can't reproduce. Do you have any other extensions?

**Comment by Bisaloo** [comment] 2019-06-20 13:00
Possibly related: https://github.com/EFForg/https-everywhere/issues/13535

Does it always happen or just sometimes? In #13535, it seemed like this would happen right after extension updates.

**Comment by BoffinbraiN** [comment] 2019-09-26 23:29
Yes, it always happens the first time I try to load the site after starting Firefox, whether that be immediately upon running, or some time later. Refreshing the page does nothing. Disabling and enabling the addon seems to be the only way.

**Comment by BoffinbraiN** [comment] 2019-09-26 23:32
And yes, it happens with all other addons disabled.

**Comment by pipboy96** [comment] 2019-09-26 23:39
Related: #17960.
Should probably be fixed by #17746.

**Comment by pipboy96** [comment] 2019-09-26 23:39
cc @zoracon.

**Comment by zoracon** [comment] 2020-10-01 19:14
Is this issue still persistent? @BoffinBrain

**Comment by BoffinBrain** [comment] 2020-10-01 23:16
Can't verify at the moment. The site issues 301 permanent redirects now. Is there a test domain I could try instead? I know there are a few out there that are used to test various HTTP/HTTPS configurations.

**Closed** 2023-01-09 20:14 UTC
Labels: firefox, needs more info
