### ISSUE TITLE
Don't probe https://check.torproject.org/?TorButton=true to detect proxy settings even if tor disabled

### ISSUE THREAD

**Issue by KOLANICH** [EFForg/https-everywhere#4286] opened 2016-03-07 09:21 UTC

**Comment by espress0** [comment] 2016-03-16 01:53
Potential spyware, huh. What do you think EFF?

I think this should be stopped; probing without user consent is absolutely no.

**Comment by reedy** [comment] 2016-03-28 13:28
Dupe of #2719

**Closed by reedy** 2016-03-28 13:28 UTC
