### ISSUE TITLE
Conflict with uBlock Origin extension on Chrome

### ISSUE THREAD

**Issue by bartovan** [EFForg/https-everywhere#14998] opened 2018-03-26 13:51 UTC
Type: code issue

Chrome gives an error message in chrome://extensions/: "This extension failed to redirect a network request to https://www.googletagmanager.com/gtm.js?id=GTM-PVMWP3 because another extension "...
The rest is unreadable, but a previous similar error stated that the other extension was uBlock Origin, which I have installed also (v 1.15.18), together with uBlock Origin Extra v.2.64.
Using HTTPS Everywhere 2018.2.26 on Chrome 65.0.3325.181 (Official Build) (64-bit), Windows 10 Pro.

**Comment by bartovan** [comment] 2018-03-26 13:53
Just noticed this is a duplicate of "[Redirect conflict with uBlock Origin #14961](https://github.com/EFForg/https-everywhere/issues/14961)".
Sorry for the double posting...

**Comment by Bisaloo** [comment] 2018-03-26 14:03
Thank you for your report. Closing this as duplicate of #14961.

**Closed by Bisaloo** 2018-03-26 14:03 UTC
