### ISSUE TITLE
Wix Hosted Website Blocked

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#5148] opened 2016-06-19 08:27 UTC
HTTPS Everywhere blocks http://www.livingstreams.tv/ from loading. This appears to be due to the Wix Static rule (https://www.eff.org/https-everywhere/atlas/domains/wixstatic.com.html).

**Comment by jeremyn** [comment] 2016-09-04 15:33
When I go to http://www.livingstreams.tv/ , I can see the CORS issue in the web console, for example:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://api.mixpanel.com/decide/?verbose=1&version=1&lib=web&token=b8f279f309ff018a6cf07375fe4e59aa&ip=1&_=1473003128841. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

but the site looks okay to me. What's not working?

**Comment by LivingStreamsTV** [comment] 2016-09-09 10:57
> When I go to http://www.livingstreams.tv/ , I can see the CORS issue 
> in the web console, for example:
>
>     Cross-Origin Request Blocked: The Same Origin Policy disallows
>     reading the remote resource at
>     http://api.mixpanel.com/decide/?verbose=1&version=1&lib=web&token=b8f279f309ff018a6cf07375fe4e59aa&ip=1&_=1473003128841.
>     (Reason: CORS header 'Access-Control-Allow-Origin' missing).
>
> but the site looks okay to me. What's not working?
>
It's working fine now. Perhaps one of the fixes/updates since the bug 
report has addressed the issue. It's a Wix site and calls plugins and 
content from various external sources.

Feel free to close the ticket.

Thanks

Liam

**Comment by LivingStreamsTV** [comment] 2016-09-09 11:10
Actually my lat email was premature and i did find a bug after all.

On the main landing page (http://livingstreams.tv) there should be a 
grey circle background behind the 'FREE Christian TV And Radio Streams' 
text near the top right. When HTTPS Everywhere is Enabled, the grey 
circle background is not there. At a guess i suspect HTTPS Everywhere is 
forcing https on a link which doesn't support it and the image won't load.

To reproduce, find and examine the 'FREE Christian TV And Radio Streams' 
text near the top right both with HTTPS Everywhere enabled and disabled. 
When disabled the grey circle background behind that text is loaded as 
it should be.

See the attached screenshot to see what the main webpage looks likes 
when HTTPS Everywhere is disabled.

Kind regards

Liam

**Comment by jeremyn** [comment] 2016-09-09 16:31
Your screenshot didn't get attached to the issue but I see what you mean with the gray circle. That is probably related to this error in the web console:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://static.wixstatic.com/shapes/8463f60718194af748c49dddbe45b668_svgshape.v1.HollowCircle.svg. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

The other `Blocked` URLs in the web console are for https://mixpanel.com , which looks like an analytics service, so those blocks wouldn't show up visually on the site.

I think this is related to long-standing issue #49 , which means the problems with your site are valid and this issue we're discussing should stay open. The `CORS-bugs` label is related to that. Unfortunately #49 probably won't be fixed soon. I'm glad the original total breakage that you reported has been fixed though.

**Comment by gloomy-ghost** [comment] 2017-08-26 11:48
http://www.livingstreams.tv moved to https

**Closed by gloomy-ghost** 2017-08-26 11:48 UTC
Labels: CORS-bugs
