### ISSUE TITLE
Videos in the 3sat library cause redirect loop

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#4351] opened 2016-03-13 09:24 UTC
Example: https://www.3sat.de/mediathek/?mode=play&obj=50970

You see that the site tries to reload itself again and again...

**Comment by numismatika** [comment] 2016-03-14 12:56
i would say duplicate of #4245

**Comment by rugk** [comment] 2016-03-14 17:44
@numismatik Yes, indeed this seems to be a duplicate.
Feel free to close it.

**Comment by J0WI** [comment] 2016-03-21 13:42
Closed by #4254

**Closed by J0WI** 2016-03-21 13:42 UTC
Labels: ruleset-bug
