### ISSUE TITLE
HTTPS Everywhere "LLVM.org (partial)" rule causes redirect from functional HTTP page to broken-HTTPS page

### ISSUE THREAD

**Issue by dholbert** [EFForg/https-everywhere#10071] opened 2017-05-30 16:36 UTC
llvm.org has a broken HTTPS configuration right now, which makes the "LLVM.org (partial)" HTTPS Everywhere rule problematic.

As described on [this bug comment](https://bugs.llvm.org/show_bug.cgi?id=31474#c2), LLVM.org's main cert uses a deprecated algorithm (SHA1), so Firefox refuses to load it (and Chrome displays it with struck-out "https").  They do have a valid cert for bugs.llvm.org, though, which is why you can load that bug page.  But llvm.org HTTPS URLs like https://llvm.org/svn/llvm-project/llvm/trunk/ have broken HTTPS.

Unfortunately, HTTPS Everywhere currently redirects working-just-fine HTTP URLs on llvm.org (like e.g. http://llvm.org/svn/llvm-project/llvm/trunk/ )  to HTTPS, so it takes a functional HTTP page and replaces it with a broken won't-load-at-all-in-Firefox HTTPS page.

This is caused by the "LLVM.org (partial)" rule.  That rule should be relaxed to not perform this redirect for http://llvm.org/ -- though some subdomains (like bugs.llvm.org) are fine to redirect I think.

**Comment by dholbert** [comment] 2017-05-30 16:45
Furthermore: even if we disregard the cert issues, LLVM.org serves different (missing) content from its HTTPS frontpage as compared to its HTTP frontpage.

HTTP Version:  http://llvm.org/ :  useful page with info about LLVM
> The LLVM Compiler Infrastructure
> ...

HTTPS Version: https://llvm.org/ : broken (even if you bypass HTTPS error)
>Not Found
>The requested URL / was not found on this server.
> Apache/2.2.22 (Ubuntu) Server at llvm.org Port 443

LLVM is aware of this -- it's tracked [here](https://bugs.llvm.org//show_bug.cgi?id=15653) -- but for the time being, the HTTPS Everywhere rule effectively makes the llvm.org frontpage unreachable due to this difference in content.

**Comment by jeremyn** [comment] 2017-05-30 19:19
Thanks for the report. [Here](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/LLVM.org.xml) is the current LLVM ruleset. There is an `exclusion` [here](https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/LLVM.org.xml#L58) to not rewrite http://llvm.org URLs unless they are under `bugs/` or `svn/`. In other words http://llvm.org should not redirect to HTTPS, and in fact it doesn't redirect when I test it myself. So it should already be behaving the way that you want it to behave.

I'm not sure why http://llvm.org/ is redirecting to https://llvm.org for you. Do you have a custom ruleset for LLVM, maybe? Can you check if http://llvm.org redirects to HTTPS in a new Firefox profile (about:profiles) with a new installation of HTTPS Everywhere?

**Comment by dholbert** [comment] 2017-05-30 21:54
My bad -- http://llvm.org/ itself is fine. Sorry!

The link I really care about, though, is http://llvm.org/svn/llvm-project/llvm/trunk/ , and that's still broken.  http://llvm.org/bugs/ is broken as well.

**Comment by jeremyn** [comment] 2017-05-30 22:54
Thanks for the clarification, I can reproduce the problem now. It looks like `^llvm.org` and `www.llvm.org` should be removed entirely. Probably the entire ruleset should be reviewed.

**Comment by koops76** [comment] 2017-07-03 14:13
#10865

**Comment by gloomy-ghost** [comment] 2017-07-04 09:42
Closing as LLVM.org had [announced](https://lists.llvm.org/pipermail/llvm-dev/2017-June/114554.html) HTTPS support one week ago.
Current valid certificate: https://crt.sh/?id=160744179

**Closed by gloomy-ghost** 2017-07-04 09:42 UTC
