### ISSUE TITLE
EASE breaks site - https://qpages.com/

### ISSUE THREAD

**Issue by sirald66** [EFForg/https-everywhere#17629] opened 2019-03-25 01:39 UTC
Windows 7 HP SP1
Chrome 72.0.3626.121
Everywhere 2019.1.31  (ruleset 2019.3.14)

**EASE mode breaks icons on - https://qpages.com/**
Resulting in icon labels obscuring and making adjacent text unreadable.

**Comment by Bisaloo** [comment] 2019-03-25 13:00
I can reproduce. It's due to the fact that the resources are loaded from `qpages.gaysaltlake.com` which does not support HTTPS.

There is not much we can do though. EASE is bound to break some sites that are not fully compatible with HTTPS once in a while. That's why it's not the default mode of HTTPS Everywhere.

Your best bet is to disable HTTPS Everywhere (or just EASE) on this website.

**Comment by Bisaloo** [comment] 2019-03-25 13:08
I just created a PR that should fix this specific issue by fetching the resources from `qpages.com` instead of `qpages.gaysaltlake.com`. Once it is merged, it should take a couple of days to be active in your browser.

**Closed** 2019-03-25 19:21 UTC

**Comment by sirald66** [comment] 2019-03-25 19:56
@Bisaloo Thanks for tweaking that.
