### ISSUE TITLE
Only show a ruleset if at least one redirection took place.

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#13412] opened 2017-10-29 18:58 UTC
Type: code issue
ping @Hainish @cowlicks.

Possibly also if the redirect could have taken place if the request were made over HTTP.

**Comment by jeremyn** [comment] 2017-10-29 21:30
As I understand it, a ruleset appears in the UI if the page URL or the URLs of any secondary request match that ruleset. So this issue is already solved if we allow the condition "Possibly also if the redirect could have taken place if the request were made over HTTP." Is that right?

If we don't allow that condition, so that for example `Freerangekitten.com` would not appear in the UI if you directly visit https://freerangekitten.com , then you wouldn't be able to disable that ruleset, since it's not in the UI to toggle on or off.

**Comment by koops76** [comment] 2017-10-30 06:33
@jeremyn No, it simply checks for targets, not for actual possible redirection.

**Comment by Bisaloo** [comment] 2017-10-30 08:04
> @jeremyn No, it simply checks for targets, not for actual possible redirection.

That's what I observed as well. It was pretty obvious with the google rulesets. Not so much now that some of them have been removed.

Note that this differs from the behaviour of the legacy HTTPS-Everywhere.

**Comment by cschanaj** [comment] 2017-10-30 11:48
I think that I can confirm @koops76 and @Bisaloo 's observations. Given a `tabId`, for each request, we look for rulesets which have matching `target`. Among these `ruleset`, if it is `active` (not `default_off`), we show it as an entry of "Stable rules"; otherwise, it is regarded as "Experimental rules". So, whether or not these rulesets make a redirection is not taken into account. 

While this issue shouldn't be too difficult to fix, but I am not sure what is the expected behavior for those `default_off` rulesets? By definition, they do not make redirections until an user activate them. However, if they do not show up, it might not be possible for non-technical user to activate these rulesets. 

cc @Hainish @cowlicks 

https://github.com/EFForg/https-everywhere/blob/e958e4bf4e8f3be30a8d183a3ed305ccb72a85b1/chromium/background.js#L285-L290

**Comment by jeremyn** [comment] 2017-10-30 14:11
All: thanks for the clarification. So is the point of this issue to take into account complications like `exclusion`s and complex `rule`s when deciding when to show a ruleset in the UI?

**Comment by Hainish** [comment] 2017-10-31 18:49
Thanks for the issue, and @cschanaj's explanation is correct: we show all *potentially* applicable rulesets, whether or not they are actually triggered on a page.  This is behavior that _is_ consistent with the legacy extension, and I believe should not be altered.

One reason for this is that for a particular page which no redirection has occurred, you may still want to disable (or enable) a potentially applicable ruleset.

https://github.com/EFForg/https-everywhere/issues/12325#issue-254763957 is related, but instead of hiding the rulesets away in the menu, the suggestion is to limit the number you see in the badge to how many actual redirects happen due to HTTPS Everywhere.  This seems most sensible to me.

**Comment by koops76** [comment] 2017-10-31 19:22
@Hainish Do you want me to open a PR?

**Comment by Hainish** [comment] 2017-10-31 19:50
@koops76 yes, I think that would be useful, thank you.

**Comment by koops76** [comment] 2017-10-31 20:08
@Hainish Does Chrome have a "tab load finished" event?

**Comment by Hainish** [comment] 2017-10-31 22:41
@koops76 https://developer.chrome.com/extensions/webRequest

**Comment by pipboy96** [comment] 2019-09-17 18:57
Duplicate of #17047.

**Closed by pipboy96** 2019-09-17 18:57 UTC
