### ISSUE TITLE
https everywhere prevents downloading mods on http://www.nexusmods.com

### ISSUE THREAD

**Issue by demonicgoat** [EFForg/https-everywhere#12324] opened 2017-09-01 17:48 UTC

**Comment by Bisaloo** [comment] 2017-09-01 18:50
Duplicate of https://github.com/EFForg/https-everywhere/issues/11953 and https://github.com/EFForg/https-everywhere/issues/11970.

It's being worked on in https://github.com/EFForg/https-everywhere/pull/11961.

**Comment by gloomy-ghost** [comment] 2017-11-06 06:55
Close as duplicate

**Closed by gloomy-ghost** 2017-11-06 06:55 UTC
