### ISSUE TITLE
Research broken bbc.co.uk / player.fm audio podcast feed

### ISSUE THREAD

**Issue by ldexterldesign** [EFForg/https-everywhere#16930] opened 2018-10-19 23:27 UTC
Type: ruleset issue

Domain: http://bbc.co.uk

Hi all,

Thanks for software

Hope you're well

This[s] audio podcast's episodes won't play with http everywhere installed. Although the .rss feed is served as https the .mp3 episodes are served as http.

It's actually an issue with *all* the BBC podcasts I subscribe to

Before I attempt to contact the BBC, prompting their adoption of universal https, please confirm whether:

a) BBCs lack of https support is the root of the problem, or;
b) it's a https everywhere ruleset issue, or;
c) both?

NB I attempted to fix this issue by disabling some https everywhere features but no luck which makes me suspicious this isn't just a)

It would sure be nice to have my podcasts back without having to disable https everywhere extension

If you have any issues (e.g. questions/queries) happy to help

Hope this is clear/useful and to hear back

Keep up great work!

Reference:

https://twitter.com/TrustifyCyber/status/1050745889806008321
https://twitter.com/getify/status/1043970491743113216
https://twitter.com/CydeWeys/status/1050795094931062785
https://twitter.com/alexcomninos/status/1049923164803911680

Related:

https://github.com/EFForg/https-everywhere/issues/275
https://github.com/EFForg/https-everywhere/issues/15218

Yours faithfully

PS couldn't really make sense of https://www.eff.org/https-everywhere/atlas/domains/bbci.co.uk.html so if it's relevant I'd love to know how to interpret this resource in the future

[s] https://player.fm/series/kermode-and-mayos-film-review-1301420/with-jamie-lee-curtis

**Comment by numismatika** [comment] 2018-10-26 21:19
In the past only a few things on the bbc websites could be fetched via TLS without being redirected to plain.
This made the rules quite ugly. Recently the BBC began to secure their websites and announced that on their blog.
So before we go over the bbc rules again, it would make sense to wait until they are done converting their website to fully support TLS.

**Comment by ldexterldesign** [comment] 2018-10-26 22:38
Hi @numismatika,

Thanks for reply

> Recently the BBC began to secure their websites and announced that on their blog

For future reference, what's the source of that information?

Hope to hear back

Yours faithfully

**Comment by numismatika** [comment] 2018-10-27 06:10
http://www.bbc.co.uk/blogs/internet/entries/f6f50d1f-a879-4999-bc6d-6634a71e2e60
http://www.bbc.co.uk/blogs/internet/entries/a6604322-99a9-4272-860c-f78e667e18e3
It is older than i remembered.
Maybe we should try again with a clean file with no exceptions and go from there.

**Comment by numismatika** [comment] 2018-11-03 08:01
It is work in progress in : https://github.com/numismatika/https-everywhere/tree/bbc_TLS
Right now i am just testing the base urls for the most obvious redirects to plain.
Then i will browse the page and see which subfolders cause problems.

**Comment by ldexterldesign** [comment] 2019-05-07 15:49
BUMP

**Comment by pipboy96** [comment] 2019-08-12 00:55
@ldexterldesign Is this issue still relevant?

**Comment by ldexterldesign** [comment] 2019-08-12 00:59
@pipboy96 yes 😞

**Comment by pipboy96** [comment] 2019-08-12 01:00
@ldexterldesign Can it be tested without an active BBC UK account?

**Comment by ldexterldesign** [comment] 2019-08-12 01:00
@pipboy96 yea, totally, use the URL(s) in my OP

**Comment by pipboy96** [comment] 2019-08-12 01:01
@ldexterldesign Confirmed!

**Comment by pipboy96** [comment] 2019-08-12 01:06
The reason is the URL the `<audio>` tag on the page is pointing at is not available over an encrypted connection. Until the website owners will fix that, we would have to disable `stitcher.acast.com` domain.

**Comment by pipboy96** [comment] 2019-08-12 01:08
High priority since a very high-traffic website is broken. If this is added by mistake, please remove.

**Comment by ldexterldesign** [comment] 2019-08-12 01:26
For convenience:

1. https://player.fm/series/kermode-and-mayos-film-review-1301420/episode-239547342
2. http://open.live.bbc.co.uk/mediaselector/6/redir/version/2.0/mediaset/audio-nondrm-download/proto/http/vpid/p07k7lxh.mp3
2.1 https://stitcher.acast.com/livestitches/3a59ac07-148b-4599-83ed-cd9156da14b7/fbdd750548fd668632dcb54f95fd2b52.mp3?aid=3a59ac07-148b-4599-83ed-cd9156da14b7&chid=761083cd-3c59-4246-b8d7-a5a9288d43aa&ci=303cdae4-5cae-4868-989f-3813d1862c00&pf=rss&uid=fbae889f7cad7b5f46a97b5d40d4d60c&Expires=1578534047&Signature=GRPDKDaEcPX3VdJKuXOyUkg-T-M6G3iqf6NhOmFnPwhmAQNz6VxBVoOobGPlxUzMMQu5tg~Ymqex01uj1ciZ98~AEL6rgcRTkzOlGEM~1x0HmiUC7gYkbebx2wm1WOoan2nDcc9h2XO3VMPrpi3P5no-Svo4~cEH42zRyb8r~NSKv3vKoRDnpK6yRccxFmhTB-LJnuYcLOy-SY5EQUwAPx-8wKMFdOprVrQpc353gNLhE20m61tjPQTmvc-xVNWqy~jJb76fV23aNJPTWCxD0WscH5~SVkP6Q58lcDEskAI4~F-SAA~J8sWNrpw4w86Kxu5VGddqsGEv-1jA6mfXvg__&Key-Pair-Id=APKAJXAFARUOTJQ3BLOQ

**Comment by pipboy96** [comment] 2019-08-12 01:30
@ldexterldesign Thanks! This should allow fixing the issue instead of disabling the domain.

**Comment by pipboy96** [comment] 2019-08-12 01:47
@ldexterldesign I confirmed a fix works correctly. I will create a PR soon!

**Comment by pipboy96** [comment] 2019-08-12 02:22
@ldexterldesign #18310.

**Comment by ldexterldesign** [comment] 2019-08-12 02:46
FYI `Encrypt All Sites Eligible is ON` (i.e. Unencrypted requests are currently blocked) seems to fix this issue, which I believe is `OFF` (i.e. Unencrypted requests are currently allowed) by default because I've only just discovered it

This seems to be the total opposite of what I think it does?!

If I wanted any chance of playing my blocked podcast then I would set this feature to `off` and allow unencrypted requests - please someone explain what's going on here and why setting it to `on` fixes my issue?

Yours hopefully

**Comment by pipboy96** [comment] 2019-08-12 03:04
@ldexterldesign EASE fixes it since it makes the first request (to `flex.acast.com`) to be sent over HTTPS, which causes it to return a HTTPS link to `stitcher.acast.com` that has a correct hash (which is not reproducible in any other way other than having that first request sent over HTTPS).

**Comment by ldexterldesign** [comment] 2019-08-12 03:49
@pipboy96 when/where in the UX does that `flex.acast.com` request occur?

**Comment by pipboy96** [comment] 2019-08-12 04:06
`flex.acast.com` redirects to the actual sound file that's stored on `stitcher.acast.com` domain (the link is unique and also depends on http/https).

**Comment by pipboy96** [comment] 2019-09-04 00:25
The fix for this issue has been merged!

**Closed by pipboy96** 2019-09-04 00:25 UTC
Labels: high priority
