### ISSUE TITLE
HTTPS Everywhere is blocking legitimate sites

### ISSUE THREAD

**Issue by furchgott** [EFForg/https-everywhere#7531] opened 2016-11-10 16:24 UTC
Hi, HTTPS Everywhere is blocking some legitimate sites I use, that were fine in the past. One such site is:

https://blackironbeast.com/5/3/1/calculator

The error message is:

"Secure Connection Failed

An error occurred during a connection to blackironbeast.com. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

The page you are trying to view cannot be shown because the authenticity of the received data could not be verified."

If I need to tell the site to make a change, please let me know, I will tell it.

**Comment by xBytez** [comment] 2016-11-10 16:38
I am unable to reproduce this issue. I've tried to go to that exact same page with a clean version of Chrome (HTTPS Everywhere is not installed) and I get the same error.

**Comment by furchgott** [comment] 2016-11-10 16:44
Hmmm. I'm on a MAC, running Sierra 10.12.1, and I have this problem both 
on my iMac and AirBook. I have the problem with both Firefox and Chrome. 
I've tried turning off extensions one at a time, and HTTPS Everywhere is 
the one blocking my content. Any thoughts on how I might fix this?

And thanks for getting back to me.

--R


xBytez wrote:

**Comment by xBytez** [comment] 2016-11-10 16:53
What I suggest you do is turn off HTTPS Everywhere for that particular site if the HTTP version works fine. You could also reach out to said website asking them to sort out their SSL configuration.

This is my first comment on HTTPS Everywhere so excuse me if I fail here but I believe the ruleset should be changed as well if it's breaking for everyone.

https://github.com/EFForg/https-everywhere/blob/445df151702555218cda70aab9aff092f1bfd214/src/chrome/content/rules/Black_Iron_Beast.com.xml

**Comment by furchgott** [comment] 2016-11-10 16:55
It's my first post as well. Does it work with all of your browsers and 
HTPPS Everywhere on?

--R


xBytez wrote:

**Comment by xBytez** [comment] 2016-11-10 17:01
HTTPS is definitely broken for that website. For all my browsers, regardless if HTTPS Everywhere is installed.

HTTPS Everywhere is forcing you to HTTPS because of the ruleset though (as intended if the SSL configuration would work). 

My current recommendation for you right now is to press the HTTPS Everywhere button and to untick "Black Iron Beast.com", the site won't work with SSL.

![Screenshot](https://i.xbytez.io/d/2016-11-10_17-59-16.png)

**Comment by furchgott** [comment] 2016-11-10 17:05
Perfect. Thanks!

--R

xBytez wrote:

**Comment by Hainish** [comment] 2016-11-10 22:28
@furchgott I'm able to access the WaPo fine with HTTPS Everywhere installed.  Are you seeing this for the front page, or some subpage?

**Comment by furchgott** [comment] 2016-11-10 23:52
Subpage -- a link from a Google search, actually.

--R


William Budington wrote:

**Comment by J0WI** [comment] 2017-02-12 11:47
closed by #8257.
This fix will ship with the next release.

**Closed by J0WI** 2017-02-12 11:47 UTC
