### ISSUE TITLE
If possible, rewrite the rulesets in a way that does not require HTTPS->HTTPS rules.

### ISSUE THREAD

**Issue by koops76** [EFForg/https-everywhere#11993] opened 2017-08-19 21:39 UTC
## Pending
- [ ] 7Headlines.com.xml
- [ ] Aeriagames.xml
- [ ] AJC.com.xml
- [ ] basekit.com.xml
- [ ] Blip.xml
- [ ] CA-State-Board-of-Equalization.xml
- [ ] Caltech.xml
- [ ] Care-Net.xml
- [ ] Comic-Con-Intl.xml
- [ ] Cru.org.xml
- [ ] DailyDot.xml
- [ ] Epic-Systems.xml
- [ ] Fasthosts.xml
- [ ] First_Class_Magazine.se.xml
- [ ] Google.xml
- [ ] HealthCheckUSA.xml
- [ ] InkFrog.com.xml
- [ ] Intelliworks_Chat.com.xml
- [ ] Khalsa-Credit-Union.xml
- [ ] KKH.de.xml
- [ ] Knappschaft-Bahn-See.xml
- [ ] MoveOn.xml
- [ ] MyEdAccount.Com.xml
- [ ] MYEDDEBT.com.xml
- [ ] National_Geographic.xml
- [ ] Necuhb.xml
- [ ] Numergy.xml
- [ ] Pair-Networks.xml
- [ ] Parkerpen.com.xml
- [ ] Perfect_Audience.xml
- [ ] Plymouth-University.xml
- [ ] Sberbank_of_Russia.xml
- [ ] SPajIT.xml
- [ ] spectator.co.uk.xml
- [ ] Telus.xml
- [ ] US-Dept-of-Veterans-Affairs.xml
- [ ] VEVO.xml
- [ ] Volgistics.xml
- [ ] Yimg.com.xml
- [ ] yWorks.com.xml
## Done
- [x] cambridgeshire.gov.uk.xml (#11996)

**Comment by jeremyn** [comment] 2017-08-21 21:05
I'm closing this as a duplicate of #10843 . See https://github.com/EFForg/https-everywhere/issues/10843#issuecomment-323852757 for why.

**Closed by jeremyn** 2017-08-21 21:05 UTC
