### ISSUE TITLE
2018.3.13 causing blank pages in Firefox

### ISSUE THREAD

**Issue by KyleDave** [EFForg/https-everywhere#15047] opened 2018-03-31 20:40 UTC
Type: code issue
Domain: zerohedge.com

I never saw this issue ( for years) until the 2018.3.13 update.   1/5 to 1/2 the time that I go to any URL the page will be blank and I have to click reload before it will display.   The problem happens on numerous domains but I see it most often at zerohedge.com.    I can verify that disabling the extension restores normal function.

Firefox 54.0
Fedora 24

**Comment by jeremyn** [comment] 2018-04-03 00:09
@KyleDave Thanks for reporting this issue.

I can't reproduce the problem with Firefox 59.0.2. If it's only failing sometimes then the problem may be associated with an ad service, or a particular ad or group of ads.

I don't know why this would fail specifically in Firefox 54, but that's not a version we really support, since it's not current (v59) nor ESR (v52). Can you consistently reproduce this problem in either current or ESR Firefox? Also, if you're familiar with Firefox developer tools, please take a look at the console while the page is loading and see if you notice any red errors that might be relevant.

**Comment by KyleDave** [comment] 2018-04-03 03:53
Yes, I tried debugging it in Firebug.   Nothing in console and no apparent html is downloaded ( thus the blank page).   I see only DOM activity which always has plenty of errors in it.  Note this is happening even when I click on https URL's on an https site.    And why would the page always reload just fine?     
Oh, my Fedora is EOL'd and there's no way to get a newer version.

**Comment by jeremyn** [comment] 2018-04-03 13:23
You could try running a more current version of Fedora/Firefox in a VM, or download Firefox directly from Mozilla on your Fedora 24 system.

In any case, do you see anything interesting in the Network tab of the developer tools? For example, obviously messed up domains, or a lot of unusual HTTP errors?

**Comment by KyleDave** [comment] 2018-04-03 13:59
No, that's what was so bizarre about it - zero network activity.

**Comment by Bisaloo** [comment] 2018-04-03 17:28
Can you also reproduce with your current Firefox and HTTPS Everywhere versions but a fresh Firefox profile?

**Comment by KyleDave** [comment] 2018-04-03 18:17
I tried just now with a new user ( never run Firefox before ), so HTTPS Everywhere was the only extension running.   I cannot get a blank page after repeated attempts - of course!   So I guess there's a bad interaction with one of the other extensions I have loaded:   flashblock, adblock, session manager, MAFIAAFire, vimperator...

**Comment by KyleDave** [comment] 2018-04-03 18:30
So just now, I tried enabling those one at a time in the new user profile and still cannot reproduce the problem.    
Could an earlier version of HTTPS Everywhere be the problem?   Which files do I need to delete to install HTTPS Everywhere from scratch?

**Comment by pipboy96** [comment] 2019-03-28 18:54
Related to old version, can't reproduce. Closing.

**Closed by pipboy96** 2019-03-28 18:54 UTC
