### ISSUE TITLE
EASE mode is disabled by default

### ISSUE THREAD

**Issue by m23retyer** [EFForg/https-everywhere#19018] opened 2020-03-13 23:32 UTC
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: other

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

It doesn't block http requests by default, after install. See "Encrypt All Sites Eligible is OFF". I took risk and tried a site, and got the http version.

To fix, after install, set "Encrypt All Sites Eligible is ON". No more http sites, displays a warning instead of doing nothing. When fixed, can recommend this extension.

you are welcome,
Raj (tester of silly browser extensions 🙃)

**Comment by m23retyer** [comment] 2020-03-13 23:35
https://github.com/EFForg/https-everywhere/issues/11995 don't know if it is related.

**Comment by pipboy96** [comment] 2020-03-13 23:41
This is the intended behavior. Rewriting every website indiscriminatingly would cause serious problems for an average user. The problem of users not being informed about EASE is hopefully fixed in the next release by upboarding page.

There are also alternatives to HTTPS Everywhere that do just the same thing you seem to want (always trying HTTPS for all websites and going back to HTTP if it doesn't work), such as [Smart HTTPS](https://mybrowseraddon.com/smart-https.html).

This behavior is fully expected and intentional, so I close this issue. You may still comment here even though the issue is closed.

**Closed by pipboy96** 2020-03-13 23:41 UTC
Labels: wontfix
