### ISSUE TITLE
[Discussion] New build system

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#13512] opened 2017-11-07 09:09 UTC
Type: other

Important features:

- [ ] Builds are reproducible.
- [ ] Runs at least on latest version of Windows 10, Ubuntu and macOS.
- [ ] Runs faster than the current build system.

Desired features:

- [ ] Based on Node.
- [ ] Runs everywhere Node does.

**Comment by koops76** [comment] 2017-11-07 20:39
ping @Hainish @cowlicks @jeremyn @gloomy-ghost.

**Comment by jeremyn** [comment] 2017-11-08 22:47
@koops76 I'm wondering what the motivation is here. Are you looking for a way to personally contribute something big to the project and want to focus on this? Or have there been recent build problems you want to fix?

The build process seems mostly okay to me. It's not the highest priority problem we have. It could definitely be improved though.

**Comment by koops76** [comment] 2017-11-09 13:13
@jeremyn The current process is tied to Linux, not very fast and the builds are not reproducible.

**Comment by koops76** [comment] 2017-11-09 13:18
@jeremyn Recently we have switched to WebExtensions too.

**Comment by Hainish** [comment] 2017-11-15 00:41
@koops76 the builds are reproducible from one run to another locally - this is one of the reasons for the inclusion of `utils/zipfile_deterministic.py` in the repo.  If they are not reproducible from one build environment to another, this should be investigated as some source of entropy is leaking into the project somewhere (perhaps a `.gitignore`'d file is sneaking into the build)

**Comment by koops76** [comment] 2017-11-15 13:33
@Hainish I would like to replace the current build system with a Gulp or Webpack based one, this is what this issue is about. Either of these supports [building CRX files](https://github.com/oncletom/crx) and [reproducible builds](https://github.com/bitgenics/deterministic-zip).

**Comment by koops76** [comment] 2017-11-15 13:35
Also I would like proper support for NPM dependencies.

**Comment by Hainish** [comment] 2018-01-31 03:34
This set of requirements is particular to this contributor.  They have removed their account.  Closing.

**Closed by Hainish** 2018-01-31 03:34 UTC

**Comment by jeremyn** [comment] 2018-01-31 16:54
@Hainish I agree with closing this issue since the contributor has closed their account. However, I think we agree with some of their suggestions as wishlist items, like converting the build system to Node, and it might be worth adding them to whatever wishlist roadmap exists, or making such a roadmap. But there's no need to discuss that further here.
