### ISSUE TITLE
Feature request: UI to temporarily allow insecure requests when otherwise blocking them

### ISSUE THREAD

**Issue by axch** [EFForg/https-everywhere#11511] opened 2017-07-29 15:34 UTC
The use case I have in mind is a user defaulting to "block insecure requests", but being able to permit some in particular cases, somewhat by analogy with the behavior of NoScript.  I can imagine variants allowing insecure requests for a particular time, in a particular browser tab, or directed to a particular host.

**Comment by jeremyn** [comment] 2017-07-29 15:50
@axch Thanks for your suggestion, however I'm closing this as a duplicate of issue https://github.com/EFForg/https-everywhere/issues/2299. Please feel free to comment on that issue if you want.

**Closed by jeremyn** 2017-07-29 15:50 UTC
