### ISSUE TITLE
Politico (partial) breaks images

### ISSUE THREAD

**Issue by terrorist96** [EFForg/https-everywhere#9410] opened 2017-04-04 02:23 UTC
https://secure.politico.com/blogs/under-the-radar/2017/04/new-hampshire-ballot-selfies-no-supreme-court-236823

`Politico.com (partial)` breaks several images on the page.

**Comment by cschanaj** [comment] 2017-04-04 13:03
Related: #9361

**Comment by J0WI** [comment] 2017-04-18 00:32
This is a dupe of #9000 and has been fixed in #9518.

**Closed** 2017-04-18 00:32 UTC

**Comment by terrorist96** [comment] 2017-04-25 22:49
@J0WI The issue is fixed now, but politico no longer redirects to https, so I guess that's one way of fixing it.
