### ISSUE TITLE
9gag.com rule breaks commenting on the site

### ISSUE THREAD

**Issue by sledgehammer999** [EFForg/https-everywhere#2657] opened 2015-08-25 12:11 UTC
I have had this problem for 3-4 months now. Before it was working.
I was really baffled why it didn't work, until I started disabling extensions one-by-one.
Basically I cannot comment on 9gag when https-everywhere is enabled.

I am using firefox 40 on Windows 7.
https-everywhere is 5.1.0

**Comment by TheNavigat** [comment] 2015-08-27 21:46
I tried fixing this. The following works, but I can't push it.

```
<ruleset name="9gag (partial)">

	<target host="9gag.com" />
	<target host="admin.9gag.com" />
	<target host="api.9gag.com" />
	<target host="m.9gag.com" />
	<target host="www.9gag.com" />
	<target host="assets-9gag-lol.9cache.com" />
	<target host="images-cdn.9gag.com" />

	<exclusion pattern="^http://(?:m\.|www\.)?9gag\.com/+(?!(?:about|advertise|faq|login|privacy|recover|signup|tos)(?:$|[?/])|favicon\.ico|img/)" />

	<securecookie host="^admin\.9gag\.com$" name=".+" />

	<rule from="^http://images-cdn\.9gag\.com/"
		to="https://d24w6bsrhbeh9d.cloudfront.net/" />

	<rule from="^http://assets-9gag-lol\.9cache\.com/"
		to="https://assets-9gag-lol.9cache.com/" />

	<rule from="^http:" to="https:" />

</ruleset>
```

Apparently it fails because of missing tests, but I can't figure out how to add the tests correctly, they're never counted as valid tests for the exclusion clause. Can someone help with that?

**Comment by jsha** [comment] 2015-08-27 22:24
The exclusion pattern is a bit confusing:

`^http://(?:m\.|www\.)?9gag\.com/+(?!(?:about|advertise|faq|login|privacy|recover|signup|tos)(?:$|[?/])|favicon\.ico|img/)`

The "?!" is a negative lookahead assertion, which meanus "match everything that is not followed by this pattern. But since this is an exclusion pattern, it's saying "rewrite m.9gag.com/about, m.9gag.com/advertise, www.9gag.com/about, etc."

I generally recommend resolving that double negative by turning exclusion rules into positive rules, i.e. rewrite only those paths. However, since the other paths would then fall through to the default http->https rewrite, that would be incorrect. You'd additionally have to add an explicit rewrite for all the other hosts, and remote the default http->https rewrite.

**Comment by TheNavigat** [comment] 2015-08-28 00:52
That is a little bit too confusing for me.

What I understood is that we need to add an explicit rule for each subdomain/page, or to be specific, for all the functioning subdomains as well as the specific pages/directories listed in the exclusion pattern. And then we need to remove the http to https rule (I think you mistakenly wrote remote instead of remove. If you did actually mean "remote", then I'd be grateful if someone could explain that bit as well). Is that correct?

**Comment by jsha** [comment] 2015-08-28 00:55
Your understanding is correct. And you're right, I meant "remove." I edited the post to fix it.

**Comment by TheNavigat** [comment] 2015-08-28 19:25
Here,

```
<ruleset name="9gag (partial)">

	<target host="9gag.com" />
	<target host="admin.9gag.com" />
	<target host="api.9gag.com" />
	<target host="m.9gag.com" />
	<target host="www.9gag.com" />
	<target host="assets-9gag-lol.9cache.com" />
	<target host="images-cdn.9gag.com" />

	<exclusion pattern="^http://(?:m\.|www\.)?9gag\.com/+(?!(?:about|advertise|faq|login|privacy|recover|signup|tos)(?:$|[?/])|favicon\.ico|img/)" />

	<securecookie host="^admin\.9gag\.com$" name=".+" />

	<rule from="^http://images-cdn\.9gag\.com/"
		to="https://d24w6bsrhbeh9d.cloudfront.net/" />

	<rule from="^http://assets-9gag-lol\.9cache\.com/"
		to="https://assets-9gag-lol.9cache.com/" />

	<rule from="^http://assets-9gag-lol\.9cache\.com/"
		to="https://assets-9gag-lol.9cache.com/" />

	<rule from="^http:\/\/(?:m\.|www\.)?9gag\.com\/about"
		to="https://$19gag.com/about" />

	<rule from="^http:\/\/(?:m\.|www\.)?9gag\.com\/advertise"
		to="https://$19gag.com/advertise" />

	<rule from="^http:\/\/(?:m\.|www\.)?9gag\.com\/faq"
		to="https://$19gag.com/faq" />

	<rule from="^http:\/\/(?:m\.|www\.)?9gag\.com\/login"
		to="https://$19gag.com/login" />

	<rule from="^http:\/\/(?:m\.|www\.)?9gag\.com\/privacy"
		to="https://$19gag.com/privacy" />

	<rule from="^http:\/\/(?:m\.|www\.)?9gag\.com\/recover"
		to="https://$19gag.com/recover" />

	<rule from="^http:\/\/(?:m\.|www\.)?9gag\.com\/signup"
		to="https://$19gag.com/signup" />

	<rule from="^http:\/\/(?:m\.|www\.)?9gag\.com\/tos"
		to="https://$19gag.com/tos" />

	<rule from="^http:\/\/(?:m\.|www\.)?9gag\.com\/img"
		to="https://$19gag.com/img" />

	<rule from="^http:\/\/(?:m\.|www\.)?9gag\.com\/favicon.ico"
		to="https://$19gag.com/favicon.ico" />

</ruleset>
```

I'm quite sure that is incorrect because it doesn't even push, but I'm stuck. Travis reports that error.

```
../src/chrome/content/rules/9gag.xml:56: element rule: Relax-NG validity error : Element rule failed to validate attributes
Relax-NG validity error : Extra element rule in interleave
```

I do understand what the error says, but I'm not sure how to fix it.

**Comment by TheNavigat** [comment] 2015-08-30 17:13
@fuglede Can you please help with that?

**Comment by fuglede** [comment] 2015-09-06 19:11
As far as I can see, two things are happening. First of all, the error is caused by the escaped slashes. You want <code>/</code> in place of <code>\/</code> throughout.

Then, for the rules to apply correctly, <code>(?:</code> should be replaced by <code>(</code> (since otherwise, the subdomain isn't captured).

By the way, I tested with http://m.9gag.com/privacy which gives a 404. Of course, rewriting a 404 to a https 404 is fine but it suggests that going through the rules might not be a bad idea.

**Comment by OlleNeiman** [comment] 2016-11-05 09:37
This still doesn't work, btw.

**Closed** 2017-02-21 20:35 UTC
