### ISSUE TITLE
WorldNow.com (partial) breaks CSS for many websites

### ISSUE THREAD

**Issue by parseword** [EFForg/https-everywhere#7221] opened 2016-09-29 04:19 UTC
Using HTTPS Everywhere 5.2.5, Firefox 49.0.1 

The **[WorldNow.com (partial)](https://github.com/EFForg/https-everywhere/blob/release/src/chrome/content/rules/WorldNow.com.xml)** rule blocks several .css files from loading on websites hosted by the WorldNow platform. As of now, the affected URI [edit: the two struckthrough were false positives] is:

~~`http://ftpcontent.worldnow.com/wncustom/custom/raycom/2015/custom-master.css`~~

~~`http://ftpcontent4.worldnow.com/raycom/custom/2015/raycom_custom_global.css`~~

`http://content.worldnow.com/global/css/_pub/platform.min.css?ver=7.3.4.63_release-7.3`

When this URI is rewritten to https, the SSL certificate for `content.worldnow.com` doesn't match the requested hostname, so Firefox prevents it from loading. As a result, rendering is broken. 

**Screenshots**:

[www.wmcactionnews5.com](https://i.imgur.com/3sz6UWE.png) with "WorldNow.com (partial)" rule enabled; the CSS layout is broken

[www.wmcactionnews5.com](https://i.imgur.com/nxbCv6I.png) with "WorldNow.com (partial)" rule disabled; the CSS layout is correct

**Comment by jeremyn** [comment] 2016-09-29 15:39
Thanks for the report. Please provide the URL that matches the screenshots.

**Comment by ampersign** [comment] 2016-09-29 16:04
The URL for the screenshots is:

http://www.wmcactionnews5.com

The same behavior is exhibited on most websites hosted by WorldNow, e.g.

http://www.kait8.com/
http://www.newschannel6now.com/
http://www.wmbfnews.com/
http://www.newswest9.com/
http://www.hawaiinewsnow.com/
http://www.fox8live.com/
http://www.cleveland19.com/
http://www.wave3.com/

**Comment by jeremyn** [comment] 2016-09-29 17:02
Thanks for clarifying. I can't reproduce the problem with any of the nine links you provided using Windows 10, Firefox 49.0.1, and HTTPS Everywhere 5.2.5. Also, for the three CSS URLs you gave in the first comment, HTTPS Everywhere doesn't try to rewrite `ftpcontent.` and `ftpcontent4.`, and the rewrite for `content.` is successful. This is consistent with the ruleset, which only has a `target` for `content.worldnow.com`.

Can you please watch the [Firefox Web Console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console) when you load http://www.wmcactionnews5.com and let us know whether you see any errors related to any CSS files, or anything about "mixed content blocking"?

**Comment by ampersign** [comment] 2016-09-29 19:22
Thanks for investigating! Checking the web console, I don't see anything about mixed content blocking. I do get CSS errors both with and without the rule enabled. I've created a couple of pastebins containing the CSS errors from the console. I'm not sure the errors themselves are useful here; only the fact that there are fewer errors when the rule is enabled, presumably because fewer CSS files are being successfully loaded.

[With "WorldNow.com (partial)" rule enabled](http://pastebin.com/raw/NEgKeSNm) (when layout is broken)
[With "WorldNow.com (partial)" rule disabled](http://pastebin.com/raw/eN3Rj4Pm) (when layout is correct)

The only change I made between these two pageloads was to go to the HTTPS Anywhere icon in the toolbar and click on the green "WorldNow.com (partial)" rule to disable it. 

> HTTPS Everywhere doesn't try to rewrite ftpcontent. and ftpcontent4.

Sorry, right you are. I've tried fetching these two manually and they do work properly whether the rule is turned on or off. I'll amend my original report.

> and the rewrite for content. is successful

This is apparently the root of my problem. If I disable the rule and go to the following URL, I see the CSS just fine:

`http://content.worldnow.com/global/css/_pub/platform.min.css?ver=7.3.4.63_release-7.3`

If I enable the rule and reload that URL, it's rewritten to https://, and Firefox gives me [this error message](https://i.imgur.com/pzfgHcL.png) about the SSL hostname mismatch.

On my end, `content.worldnow.com` is resolving to `104.90.12.223` as a CNAME to `wildcard.worldnow.com.edgekey.net` which itself is a CNAME to `e6078.g.akamaiedge.net`. 

Maybe the Akamai server you're hitting has a proper certificate installed?

**Comment by pipboy96** [comment] 2019-03-31 08:00
Seems to have been resolved.

**Closed by pipboy96** 2019-03-31 08:00 UTC
Labels: ruleset-bug
