### ISSUE TITLE
myfitnesspal.com partially broken

### ISSUE THREAD

**Issue by VioletRose** [EFForg/https-everywhere#11029] opened 2017-07-12 04:58 UTC
This is a food diary/fitness tracking site, and on it, with HTTPS Everywhere forcing secure connections to MyFitnessPal, most lists of food items don't load properly, with the following or similar appearing in the browser console:
XMLHttpRequest cannot load https://www.myfitnesspal.com/food/load_recent. Response for preflight is invalid (redirect)

Additionally, if a list is working, attempting to add an item from it to the food diary will trigger the site's "under maintenance" message, with the following appearing in the browser console:
POST https://www.myfitnesspal.com/food/add_favorites 502 (Bad Gateway)

**Comment by Bisaloo** [comment] 2017-07-12 10:46
Thank you for your report. 

Can you post an example URL where this happens? Also do we need an account for this?

**Comment by VioletRose** [comment] 2017-07-12 16:03
This is the main one, though the query string is irrelevant, it happens with all meals.
http://www.myfitnesspal.com/food/add_to_diary?meal=0
And yes, unfortunately the functionality that's broken is adding food items to the list of what you've eaten today, which is a list you won't have without an account.

**Comment by Bisaloo** [comment] 2017-07-12 16:29
Okay, I completely disabled the ruleset anyways. The `https` support seems sporadic and buggy.

My main concern is that the broken functionality might be due to another ruleset interfering.

Could you please test if you can reproduce when you disable the `MyFitnessPal` ruleset? (you can do so by clicking on it in the dropdown menu)

**Comment by VioletRose** [comment] 2017-07-12 17:07
When I said "with HTTPS Everywhere forcing secure connections to MyFitnessPal", I meant to imply that this only happens with the MyFitnessPal ruleset enabled. Turning it off fixes the issue without HTTPS Everywhere needing to be disabled. Sorry for the confusion, I haven't spent enough time around this project to know how to refer to things clearly.

**Comment by Bisaloo** [comment] 2017-07-12 17:54
Great! #11033 should fix it then.

Hopefully, it will be included in the next release (https://github.com/EFForg/https-everywhere/issues/10888).

Please report back if you still have issues after that.

**Comment by HTTPSNowhere** [comment] 2017-07-13 11:29
Reported in the Tor Project trac ticket as well: https://trac.torproject.org/projects/tor/ticket/22887

**Closed** 2017-07-26 18:57 UTC
