### ISSUE TITLE
Add support for Safari 12 - 2019 and still no secure option for Safari

### ISSUE THREAD

**Issue by whatthehomepod** [EFForg/https-everywhere#17631] opened 2019-03-25 19:23 UTC

**Comment by pipboy96** [comment] 2019-03-26 00:13
Duplicate of #5121.

**Closed by pipboy96** 2019-03-26 00:13 UTC

**Comment by whatthehomepod** [comment] 2019-03-26 08:24
Yeah do something about it than. I opened another one because the first issue opened three years ago. Jesus Christ. 

Verstuurd vanaf mijn iPhone

**Comment by pipboy96** [comment] 2019-03-26 08:38
@whatthehomepod Please address all your concerns to #5121.
