### ISSUE TITLE
store.steampowered.com search dropdown not functioning

### ISSUE THREAD

**Issue by twistedau** [EFForg/https-everywhere#1560] opened 2015-04-23 00:12 UTC
When the ruleset "Steam Powered.com (Partial)" is enabled the search box does not automatically populate with matched results.

**Comment by twistedau** [comment] 2015-04-23 13:22
Steam static.com (Partial) also breaks functionality on the store.steampowered.com site (Add to wishlist, follow, etc). For example: http://store.steampowered.com/app/364360/.

**Comment by reedy** [comment] 2015-04-23 20:54
Dupe of #1453

**Closed by reedy** 2015-04-23 20:54 UTC
