### ISSUE TITLE
Firefox 47 on Linux still has the old logo

### ISSUE THREAD

**Issue by forteller** [EFForg/https-everywhere#6065] opened 2016-08-03 20:27 UTC
At least for me. I use Ubuntu Gnome 16.04, Firefox 47.0 and HTTPS-Everywhere 5.2.1

**Comment by fuglede** [comment] 2016-08-05 18:04
Cruious Firefox 47.0.1 on Debian here, and I have the new logo.

**Comment by forteller** [comment] 2016-08-05 18:55
Hmm… After updating to Fx 48 I have the new logo too, so I guess everything is ok :)

**Comment by fuglede** [comment] 2016-08-05 18:57
It would have been nice to understand the cause of course; I guess we'll see if more reports come in. Do you want to close this?

**Comment by Hainish** [comment] 2016-08-06 02:24
I'm guessing this was just due to the extension not having been upgraded, I'm closing but feel free to open a new issue if you can reproduce.

**Closed by Hainish** 2016-08-06 02:24 UTC
