### ISSUE TITLE
Ruleset Everydayfeminism.com works on Firefox (Desktop), but not on Firefox Android)

### ISSUE THREAD

**Issue by Mikaela** [EFForg/https-everywhere#7317] opened 2016-10-11 16:37 UTC
From https://github.com/EFForg/https-everywhere/pull/6782#issuecomment-252918615 : 

>> Why would a rule work with Firefox desktop (50.0b5), but not with Firefox Beta for Android (50.0b4)? Both browsers say to be using HTTPS Everywhere 5.2.5 and I see the rule in question https://github.com/EFForg/https-everywhere/blob/5.2.5/src/chrome/content/rules/Everydayfeminism.com.xml under the tag 5.2.5. The site also doesn't have separate mobile site that I can see (I don't know anywhere deeper to look than the address bar though).

> I wondered this on Sunday at #https-everywhere on irc.oftc.net which seems quite silent. I hope you do read at least GitHub if not IRC or there was some event preventing IRC from seeing.

* * * * *

@jeremyn replied:

> I don't follow HTTPS Everywhere IRC channels. The best place to report problems is GitHub.

> I can confirm the problem you're seeing, that is, http://everydayfeminism.com doesn't get rewritten to HTTPS on Firefox for Android even with HTTPS Everywhere 5.2.5, but it does get rewritten in desktop Firefox. I don't know why. Could you please submit a new issue for this problem?

* * * * *

A little offtopic, but if the issue with IRC is requiring 24/7 shells or bouncers for using, you could use Matrix which has bridge to OFTC.

* https://matrix.to/#/#_oftc_#https-everywhere:matrix.org

**Comment by jeremyn** [comment] 2016-10-11 18:09
I can confirm that on Firefox for Android 49.0, HTTPS Everywhere 5.2.5 **does not** rewrite http://everydayfeminism.com to https but **does** rewrite, as an example, http://www.juno.com , so the problem is not with every domain. In both cases the appropriate ruleset name is on and active under `HTTPS Everywhere > Enable/disable rules`. Both rulesets correctly rewrite on desktop Android. Neither site is HSTS preloaded.

I'm marking this as `High Priority` because at this point it could be many domains, not just http://everydayfeminism.com . Unfortunately I don't know much about troubleshooting Firefox for Android.

**Comment by Hainish** [comment] 2016-10-17 18:24
The reason for this seems to be differential treatment of HTTPS requests to https://everydayfeminism.com/ based on request user-agent:

```shell
legind@EFF-420 ~/workspace/https-everywhere (master) $ curl -I 'https://everydayfeminism.com/' -H 'Host: everydayfeminism.com' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0'
HTTP/1.1 200 OK
Date: Mon, 17 Oct 2016 18:19:57 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=d766311607e5f9e753d512f061e3e680d1476728396; expires=Tue, 17-Oct-17 18:19:56 GMT; path=/; domain=.everydayfeminism.com; HttpOnly
Vary: Accept-Encoding,Cookie
X-Cacheable: SHORT
Cache-Control: max-age=600, must-revalidate
X-Cache: HIT: 5
X-Cache-Group: normal
Link: <https://everydayfeminism.com/wp-json/>; rel="https://api.w.org/"
X-Type: default
X-Pass-Why: 
Set-Cookie: X-Mapping-fjhppofk=37FD84793E73FD4531CA55F5A4B7E373; path=/
Server: cloudflare-nginx
CF-RAY: 2f35c2fffd2c0d3d-LAX

legind@EFF-420 ~/workspace/https-everywhere (master) $ curl -I 'https://everydayfeminism.com/' -H 'Host: everydayfeminism.com' -H 'User-Agent: Mozilla/5.0 (Android 7.0; Mobile; rv:49.0) Gecko/49.0 Firefox/49.0'
HTTP/1.1 301 Moved Permanently
Date: Mon, 17 Oct 2016 18:20:04 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=de43a76a90c578cbade0ad632eecd1c461476728404; expires=Tue, 17-Oct-17 18:20:04 GMT; path=/; domain=.everydayfeminism.com; HttpOnly
Vary: Accept-Encoding
X-Cacheable: non200
Cache-Control: max-age=600, must-revalidate
X-Cache: HIT: 9
X-Cache-Group: iphone
Location: http://everydayfeminism.com/
X-Type: default
X-Pass-Why: 
Set-Cookie: X-Mapping-fjhppofk=37FD84793E73FD4531CA55F5A4B7E373; path=/
Set-Cookie: redirect_count=1; path=/
Server: cloudflare-nginx
CF-RAY: 2f35c32dfea853de-LAX
```

This results in a redirect loop in Android, which after several attempts results in HTTPS Everywhere allowing the HTTP request to proceed.

As this is intended behavior, I'm closing this.

**Closed by Hainish** 2016-10-17 18:24 UTC
Labels: android

**Comment by Mikaela** [comment] 2016-10-19 17:21
Can this be fixed somehow on the ruleset level? Are there any tests to show if this issue happens with ruleset as there might be issues with other rulesets too?

**Comment by Hainish** [comment] 2016-10-19 17:36
There's no way to fix the issue within HTTPS Everywhere because the remote site is essentially refusing to serve HTTPS when you request it with a certain browser.  Your mobile browser can report any arbitrary User-Agent string it wants, and reporting a desktop UA string *should* make the site available over HTTPS, but this is outside the scope of HTTPS Everywhere.  The site owner should contact their CDN (seems to be Cloudflare) and request the site be available for mobile browsers over HTTPS.
