### ISSUE TITLE
Add exception feature which allow http for certain site when "block all unecrypted request" is enabled.

### ISSUE THREAD

**Issue by contactlp** [EFForg/https-everywhere#16050] opened 2018-07-10 14:37 UTC
Type: feature request

Domain: internal company site

I love to use https every where with "block all unecrypted request" option. This helps me to forward site from http to https for example. sandesh.com

But, I also have to work with some of the internal company site  which do not have https. This creates frustracting situation(experience) where I have to disable "block all unecrypted request" for a while. 

I hope there is exception feature where I can add internal sites (preferably with regular expression support).

Thanks

**Comment by Bisaloo** [comment] 2018-07-10 14:59
Thank you for your report! I'm closing this issue as a duplicate of #2299. If it's something you would like to work on, pull requests are very much welcome!

**Closed by Bisaloo** 2018-07-10 14:59 UTC
