### ISSUE TITLE
[msn.com] Not forcing https

### ISSUE THREAD

**Issue by derpyderpaderp** [EFForg/https-everywhere#10968] opened 2017-07-09 08:40 UTC
Msn is not forcing itself to HTTPS any ideas as to why? I read an issue from back in april but it seems to have been fixed then. It is now broken again. Any help to lead me into the right direction on how to fix this would be appreciated. PS. I am on the latest version of chrome thanks!

**Comment by jeremyn** [comment] 2017-07-12 15:17
Rewrites happen based on the specific URL, so I encourage you to search through https://www.eff.org/https-everywhere/atlas/ and GitHub to figure out why the URL you're concerned about isn't matching. If you have trouble figuring it out, please reply with the specific URL and the behavior you expect to see, otherwise please close this issue.

**Comment by J0WI** [comment] 2017-08-09 21:33
@derpyderpaderp could you please try to reproduce with the current version of HTTPS Everywhere?
Please post your version if you are still able to reproduce this issue.

**Comment by derpyderpaderp** [comment] 2017-08-09 22:10
Still able to reproduce this with Version: 2017.7.18 https://gyazo.com/a3ed94a97788935f469e001c99ececaa

**Comment by J0WI** [comment] 2017-08-09 22:27
Looks like mixed passive content. Would you like to open your browser console and share the related warnings with us?

**Comment by derpyderpaderp** [comment] 2017-08-09 22:33
https://gyazo.com/3b3f8ab310d06b989ee1745373159b26

**Comment by J0WI** [comment] 2017-08-09 23:25
Thank you for the helpful screenshots!
I was able to reproduce the issue. Microsoft injects some insecure adverts and trackers on msn.com, but those gets blocked by the browsers mixed content blocker.
We don't consider Ads as an important part of the site, so we won't disable the rule because of this.

The mixed passive content is secured by HTTPS Everywhere, but the browser triggers the mixed content before we are allowed to secure it. Since mixed passive content is not (yet) blocked in browsers, you won't have any functional issues with this.

**Closed by J0WI** 2017-08-09 23:25 UTC

**Comment by derpyderpaderp** [comment] 2017-08-09 23:28
Okay thank you
