### ISSUE TITLE
"Block All Unencrypted Requests", except...

### ISSUE THREAD

**Issue by c64whiz** [EFForg/https-everywhere#14841] opened 2018-03-02 21:12 UTC
Type: feature request

I usually keep the "Block All Unencrypted Requests" checked.  This is my "safe mode".  However, I have a local, development, site for example, on my local machine for which SSL is not enabled.  Rather than enabling SSL on the local dev server, I'd rather just be able to provide an exception to the "Block All Unencrypted Requests" state.  However, my testing with rules seems to apply only to normal operation (i.e. "Block All..." being _unchecked_).

So the feature request is to write rules which could keep a site http, even if "Block All..." is checked.

Thanks!

**Comment by jeremyn** [comment] 2018-03-02 22:01
Thanks for your suggestion, however I'm closing this as a duplicate of issue https://github.com/EFForg/https-everywhere/issues/2299.

**Closed by jeremyn** 2018-03-02 22:01 UTC
