### ISSUE TITLE
Feature request: More informative refusal to follow insecure link in Firefox

### ISSUE THREAD

**Issue by axch** [EFForg/https-everywhere#11512] opened 2017-07-29 15:36 UTC
I tried browsing with "block insecure requests" on, and observed that when I clicked on links that HTTPS Everywhere could not translate to https, the browser just ignored my click and didn't do anything.  I think it would be more helpful to perform some UI action, like popping up a tooltip, that acknowledged the click, so that the user know that they did not mis-click, but that the action was blocked purposefully.

**Comment by Bisaloo** [comment] 2017-07-29 15:42
Related: https://github.com/EFForg/https-everywhere/issues/8239

**Comment by jeremyn** [comment] 2017-07-29 15:47
@axch Can you please give an example of a page with a link that behaves this way? I can't think of any case where HTTPS Everywhere should cause a browser to entirely ignore a click.

**Comment by axch** [comment] 2017-07-29 16:10
@jeremyn Looking for it, I am not finding a situation exactly as described, but here's an instance of something that could be smoothed out, at least for new users like me: I just searched Google for "noaa" and tried to navigate to the first hit, which is the web site of the National Oceanic and Atmospheric Administration.  The user experience was a long lag, followed by Firefox saying "The server at www.noaa.gov is taking too long to respond."  This is kind of jarring, because www.noaa.gov is generally pretty reliable -- under the http protocol.  As a new user of HTTPS Everywhere, I found myself having to consciously double-check the URL bar and note that what failed was https://www.noaa.gov.

I wonder whether there is something you might do to smooth out this element of the new user experience?  Maybe a tooltip or notification when a request is rewritten by default without an explicit rule-set?  Is there a way to detect connection failure in such circumstances and notify only if the connection indeed failed?  Presumably experienced users will want to be able to turn such a notification off regardless, but it might help newbies like me get used to the experience of the web as seen through "block insecure requests".

**Comment by jeremyn** [comment] 2017-07-29 17:12
@axch Okay, I understand what you're seeing now. The issue that @Bisaloo linked above, https://github.com/EFForg/https-everywhere/issues/8239, is very relevant for this and I'm going to close this issue as a duplicate. I encourage you to read the discussion there.

A key thing to understand is that the major value of HTTPS Everywhere is that there are over 20,000 ruleset files, many/most of which do targeted HTTP->HTTPS rewrites that have been written or reviewed by one or more human beings. For example there is a ruleset that rewrites NOAA.gov domains and it doesn't include http://www.noaa.gov specifically because that domain times out, which is the problem you encountered (see [`National_Oceanic_and_Atmospheric_Administration.xml`](https://github.com/EFForg/https-everywhere/blob/9bf49cbeb4696cdea76df23f685da1d11031f693/src/chrome/content/rules/National_Oceanic_and_Atmospheric_Administration.xml#L13)).

"Block all unencrypted requests" just rewrites everything from HTTPS->HTTP, and you can probably understand that selecting that option is a much blunter approach than what you see in the ruleset file I linked.

**Closed by jeremyn** 2017-07-29 17:13 UTC

**Comment by Bisaloo** [comment] 2017-09-01 08:30
@jeremyn, this issue rang a bell but I couldn't find a test url at the time so I let it go.

I managed to reproduce so I would be great if we could reopen that issue (although it is strongly related to #8239). It may be still be worth to keep it in a separate issue because it is more severe than the case discussed in #8239.

Nothing will happen if you click on a link to a domain that redirect to `http`.

You will want to try it for yourself, you can click on the 2nd link from [this duckduckgo search](https://duckduckgo.com/?q=http%3A%2F%2Fcalvinhobbesdaily.tumblr.com).
