### ISSUE TITLE
Unable to test IPv6 hosts

### ISSUE THREAD

**Issue by J0WI** [EFForg/https-everywhere#4762] opened 2016-05-12 23:43 UTC
Travis does not support IPv6. IPv6 only hosts will fail our tests.
See #4080 or #4760.

Travis refuses to support IPv6 in near future (see linked comments in https://github.com/EFForg/https-everywhere/pull/4080#issuecomment-218583651)

How do we handle that?
I think this get much more important for us in near future.
cc @Hainish @jsha

**Comment by J0WI** [comment] 2016-05-12 23:51
As a workaround we should think about a 6to4 tunnel:
https://wiki.debian.org/DebianIPv6#IPv6_6to4_Configuration

**Comment by mnordhoff** [comment] 2016-05-13 01:34
Looks like they don't support proto-41 traffic either. If that remains true, 6in4 and 6to4 are out:

https://stackoverflow.com/questions/31066205/how-to-allow-protocol-41-6in4-through-the-gce-firewall
https://cloud.google.com/compute/docs/networks-and-firewalls
https://cloud.google.com/compute/docs/protocol-forwarding/

**Comment by Hainish** [comment] 2016-05-13 01:43
I think a quick solution to this is to use a third-party ipv6 over 4 such as [miredo](http://www.remlab.net/miredo/).  This usually works OOTB, but still seems to be failing for my test travis run:

https://travis-ci.org/Hainish/https-everywhere/jobs/129889699#L648

**Comment by Hainish** [comment] 2016-05-13 22:08
I wonder if the error is occurring due to ipv6 kernel modules not being loaded?  I see the same error as the travis build on my local before installing `miredo`, but as soon as installing `miredo` the problem is resolved.

**Comment by J0WI** [comment] 2016-05-14 10:54
It should be enabled in newer versions of Ubuntu. You may check for `/proc/net/if_inet6` and the config in `/etc/sysctl.d/` anyway.
May be it also requires to restart the networking service?

**Comment by Hainish** [comment] 2016-05-19 22:26
It looks like within a docker container, we can get travis speaking ipv6 via `miredo`:

https://travis-ci.org/Hainish/test-travis-ipv6/builds/131532034
https://github.com/Hainish/test-travis-ipv6/tree/b0442d7a7903367f1f27c458d19d947b0dbd0a6b

This is less ideal than getting it to work natively in the travis build environment, since it would require restructuring our travis file quite a bit.  I'll continue trying to get native support working.

**Comment by Hainish** [comment] 2016-05-19 23:00
It seems as though travis doesn't want you poking around at ipv6 settings: https://travis-ci.org/Hainish/test-travis-ipv6/builds/131556865

**Comment by Hainish** [comment] 2016-05-20 18:47
Request to enable IPv6-over-4 via `miredo` was dismissed out of hand: https://github.com/travis-ci/travis-ci/issues/6082

If we were to switch to docker builds on travis, we'd want to speed things up a bit.  Main distro docker images lack a lot of essential tools that we'd need to do tests, and installing from the repos takes time.  So we could create a base image which has all the essential system requirements you'd need to perform the tests, and in the docker build phase inherit from it.  This will download the image each time a test is run, which will be quicker than installing it from the repos each time.

**Comment by Hainish** [comment] 2016-05-20 20:41
Building an image as described above results in an unacceptably large image size:

```shell
electronicfrontierfoundation/https-everywhere-docker-base   latest              324853222b07        About an hour ago   1.043 GB
```

Even with the network pipe that `travis` has, this image would be very slow to download.

**Comment by Hainish** [comment] 2016-05-23 19:13
They've reopened https://github.com/travis-ci/travis-ci/issues/6082, hopefully this will allow us to do ipv6 testing with miredo without the use of docker.

Another option would be to move to another CI service, like [Circle CI](https://circleci.com/), but I'd like to avoid this if possible.  It's not the CI stack that everyone knows, and would still require refactoring whatever replaces `.travis.yml`

**Comment by Hainish** [comment] 2016-05-24 19:24
I have travis running tests via docker:

https://travis-ci.org/Hainish/https-everywhere/builds/132640174
https://github.com/Hainish/https-everywhere/tree/dockerize-travis-test

This adds 30 seconds to a minute onto the test suite running time.  There are ways to reduce this: for example, incorporating installation of the python packages in the docker base image.  But this involves a trade-off: if a pull request changes those requirements, it will not be automatically changed in the base image, and thus the tests would not actually reflect the current state of the code.  This seems an unacceptable solution to me.

Another possible solution is to convince travis to make the base image (or any layers it inherits from) available locally.  Here's what `docker images` shows me in the travis build env:

```shell
$ docker images

REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZEThe 


command "docker images" exited with 0.
```

So in fact docker is not caching any base images, even the most popular ones.  `https-everywhere-docker-base` is inherited from `ubuntu:xenial`.  It probably wouldn't be a hard sell to convince them to cache `ubuntu:xenial`, since it's so popularly used, and this would decrease the download time significantly.

I'm open to suggestions.

**Comment by Hainish** [comment] 2016-05-24 20:38
Opened https://github.com/travis-ci/travis-ci/issues/6102 asking for most popular docker images to be cached.

**Comment by J0WI** [comment] 2016-05-24 21:48
> There are ways to reduce this: for example, incorporating installation of the python packages in the docker base image. But this involves a trade-off: if a pull request changes those requirements, it will not be automatically changed in the base image, and thus the tests would not actually reflect the current state of the code. This seems an unacceptable solution to me.

Why not using the Dockerfile from this repo for the base image?
I wonder why you would need all the requirements on your local machine when we have Docker.

**Comment by Hainish** [comment] 2016-05-24 22:11
@J0WI, the Dockerfile for this repo would be inheriting *from* the base image.  As a result, the base image would be downloaded upon each travis test, rather than built.  This is faster than inheriting from `ubuntu:xenial` and running the `apt` commands directly.

**Comment by J0WI** [comment] 2016-05-24 22:31
I mean this step here: https://github.com/Hainish/https-everywhere/blob/dockerize-travis-test/.travis.yml#L6

**Comment by Hainish** [comment] 2016-05-24 22:37
@J0WI we use the Dockerfile https://github.com/Hainish/https-everywhere/blob/dockerize-travis-test/Dockerfile, which inherits from a base image here: https://github.com/EFForg/https-everywhere-docker-base/blob/master/Dockerfile

**Comment by Hainish** [comment] 2016-05-24 23:05
I've added `miredo` to the base build and travis.yml file.  When rebased from `dockerize-travis-test`, #4080 passes! https://travis-ci.org/Hainish/https-everywhere/builds/132701915

**Comment by Hainish** [comment] 2016-05-24 23:17
Docker tests have been merged with IPv6 support - yay!

**Closed by Hainish** 2016-05-24 23:17 UTC
Labels: question
