### ISSUE TITLE
theverge.com no longer working correctly

### ISSUE THREAD

**Issue by renestalder** [EFForg/https-everywhere#1299] opened 2015-03-27 08:35 UTC
I'm not sure I have to place this issue here on Github, so please give me feedback, where to post, if it's wrong.

Tested with https everywhere on Chrome, theverge.com (partial) does no longer load all images correctly. Also the comment section seems not to work.

It starts working again, when I deactivate it.

![screenshot 2015-03-27 09 34 49](https://cloud.githubusercontent.com/assets/105358/6864635/908aae76-d464-11e4-8701-7aa8a6a59d5a.png)

**Comment by 2d1** [comment] 2015-04-02 02:27
Seeing as @voxmedia haven't fixed this problem on their end, replied to a support request, nor responded to github 'pings', it seems evident that either they're unable to secure Sonobi scripts (as in [Sonobi.com.xml] (../blob/master/src/chrome/content/rules/Sonobi.com.xml)), are unusually busy, or don't care.

Given how overtly hostile their pages are to privacy (take a look at your noscript menu[!]), I'm guessing that it's the lattermost case.

On the one hand, I'm hesitant to sacrifice the privacy of https-everywhere users solely for comments sections. But on the other hand, torbrowser both enables scripts by default and makes not cascading permissions to all those trackers hard, so users who browse theverge are for the most part fscked.* https won't save anyone from the aforementioned hostility. Presumably savvy users both know not to enable scripts and how to enable rulesets that are off by default.

That said, I don't want to be the one that condemns the first group, so I'll defer to @jsha. Could you decide whether comments are worth disabling this ruleset please. To be clear, images require scripting to be enabled but afaict work over http & https. Comments otoh do not work.

\* The fact that torbrowser doesn't include privacybadger is bizarre

**Comment by jsha** [comment] 2015-04-02 18:20
I'm not able to reproduce the image-loading problem or the comments problem. Could you provide more complete instructions to reproduce?

**Comment by 2d1** [comment] 2015-04-05 01:53
On checking again, it seems to have been fixed. Previously the sonobi script was printed where the comment section is now.

@renestalder could you verify that it's working for you now,  please.

**Comment by renestalder** [comment] 2015-04-07 08:39
Using the Google Chrome Plugin **https everywhere**, all stable rules on theverge.com activated, the blog post images are not loading. This looks like this:

**Images not loading**

![screenshot 2015-04-07 10 34 18](https://cloud.githubusercontent.com/assets/105358/7019581/bacffa82-dd11-11e4-9c7e-b15c4cb55156.png)
![screenshot 2015-04-07 10 34 13](https://cloud.githubusercontent.com/assets/105358/7019580/bacca3fa-dd11-11e4-950c-a5a9d592d76c.png)
![screenshot 2015-04-07 10 37 54](https://cloud.githubusercontent.com/assets/105358/7019622/2fa19cda-dd12-11e4-8699-52248f3a282f.png)

**Comments not loading**

![screenshot 2015-04-07 10 35 34](https://cloud.githubusercontent.com/assets/105358/7019596/e5fd76a8-dd11-11e4-9432-e3712e322282.png)



@2d1 Do I have to update something to get it working? Is it already deployed to Chrome Web Store? I manually hit the update extensions button in Chrome.

**Comment by 2d1** [comment] 2015-04-07 10:16
@renestalder I don't know about Chrome. Perhaps you're hitting an instance of https://github.com/EFForg/https-everywhere/issues/1339.

**Comment by jsha** [comment] 2015-04-09 19:46
I still haven't been able to reproduce this in Chrome or Firefox, but I think given multiple reports it makes sense to disable this rule in the next release unless we can diagnose and fix.

**Comment by justlurking** [comment] 2015-04-10 13:25
I'm also seeing the issues both with images on the home page and (more importantly) with comments not loading.  (On Chrome, stable branch, for Mac OS 10.10.2.)  I have been in contact with someone from The Verge's support - I will send them the link to this issue.

Until there is an update pushed, is there an easy fix that doesn't involve completely disabling the extension?

**Comment by renestalder** [comment] 2015-04-10 13:29
@justlurking You can easily fix that temporary. Just deactivate The Verge (Partial) in the browser add-
![screenshot 2015-04-10 15 28 56](https://cloud.githubusercontent.com/assets/105358/7088714/6c2a7498-df96-11e4-91a1-d526a2b23b77.png)
on while you are on the website.

**Comment by justlurking** [comment] 2015-04-10 13:38
@renestalder Thank you for the quick response.  That was an easy fix - I will keep it in mind if I run into problems on other sites in the future.  

For what it's worth, I received an almost immediate reply from Verge support after emailing them this issue:

"Hi XXX, upgrading to full HTTPS support is definitely in our plans for this year. There's no immediate action being taken on our end, so whitelisting the site in the extension may be your best bet for now."

**Comment by cwilliams2k4** [comment] 2015-04-10 17:13
HTTPS is a security priority for us at Vox Media this year. We'll be certainly moving towards that goal over the summer. We're looking forward to bringing the HTTPS experience to all of our users as soon as we are able.

**Comment by jsha** [comment] 2015-04-10 18:48
@cwilliams2k4: Awesome to hear you're working on it full HTTPS support, thanks!

**Closed** 2015-04-15 22:22 UTC
