### ISSUE TITLE
photo

### ISSUE THREAD

**Issue by LisonFan** [EFForg/https-everywhere#6741] opened 2016-09-03 09:14 UTC
![](http://ww4.sinaimg.cn/large/006fVPCvjw1f7gikepc72j30lr040aac.jpg)

**Comment by jeremyn** [comment] 2016-09-03 15:29
I'm not sure what the red text is saying but I guess this is a duplicate of #5874 . Closing issue.

**Closed by jeremyn** 2016-09-03 15:29 UTC
