### ISSUE TITLE
Chrome does not consider HTTPS Everywhere's internal redirects to be secure

### ISSUE THREAD

**Issue by Manouchehri** [EFForg/https-everywhere#2389] opened 2015-08-03 21:57 UTC
This has probably been brought up before, but HTTPS Everywhere seems to be missing some  embedded content. Chromium isn't blocking the content either, so I don't quite understand why the requests aren't being rewritten.

Example:

(`--allow-running-insecure-content` is on for this experiment, though it's probably not necessary.) Going directly to [Fig. 1](http://people.mozilla.org/~bsterne/tests/62178/static/script/script3.js) redirects to the [HTTPS version](https://people.mozilla.org/~bsterne/tests/62178/static/script/script3.js) (as expected). However, when going to [a page that has Fig. 1 on it](https://people.mozilla.org/~bsterne/tests/62178/test.html), Fig. 1 is not rewritten to HTTPS.

**Comment by reedy** [comment] 2015-08-11 14:53
Yeah, this feels like a dupe...

**Comment by Manouchehri** [comment] 2015-08-11 14:54
@reedy: Can you point me towards the right ticket? I tried going through a few pages but couldn't find it.

**Comment by reedy** [comment] 2015-08-11 16:20
I can't find it straight off :/

**Comment by jsha** [comment] 2015-08-11 19:35
This is a known issue with Mixed Content Blocking: scripts get blocked before HTTPS Everywhere has a chance to rewrite them, in both Chrome and Firefox. See this entry: https://www.eff.org/https-everywhere/rulesets#mixed-content

**Comment by Manouchehri** [comment] 2015-08-11 19:47
Doesn't seem to be that, I can verify with a few network captures and/or
screenshots if you really want.

This happens with embedded *pictures* too. Initially I showed the exact
same example with an image instead of a script (I removed it because the
links went dead and I felt it would be confusing to link to an nonexistent
resource). If you enable experimental rules for Wolfram Alpha, you'll see
image results being grabbed over HTTP that should be hitting a rule (and
they do if you open them up in a new tab).

Also, I've explicitly allowed insecure scripts to run (mentioned in the
first post). They're not being blocked. The issue is that they're not being
upgrade to HTTPS, despite having the chance to.

**Comment by jsha** [comment] 2015-08-11 20:39
Ah, interesting. Sorry for jumping to conclusions! I'll see if I can reproduce.

**Comment by Manouchehri** [comment] 2015-08-11 22:13
I went to go reproduce the issue, ended up figuring out the cause. It's definitely not HTTPS Everywhere's fault. At first I thought I just made an insanely bad PEBCAK error, but after reading up, I think I can cut myself a bit of slack; I'll try to explain it in case the issue comes up again.

When I enabled insecure scripts, I also enabled another plugin, uMatrix, to handle enforcing certain strict HTTPS rules. What I thought would happen is that since both extensions were touching the same requests, that the extension installed last (uMatrix) would also be run last and let all the new HTTPS URLs through. I believe [`run_at` level with `document_start`](https://github.com/gorhill/uMatrix/blob/master/platform/chromium/manifest.json#L56) will also always be run after [`chrome.webRequest`](https://github.com/EFForg/https-everywhere/blob/master/chromium/background.js#L507), so it's probably a non-issue anyway. 

In theory both of these extensions should compliment each other pretty well, since the mixed content (script or otherwise) blocking is going to be applied _after_ HTTPS Everywhere (this would basically solve the entire issue referred in the FAQ about Chrome blocking scripts before having a chance to fix them).

What's happening now is that uMatrix is mistakenly blocking HTTPS Everywhere's `307 Internal Redirect`. It turns out that this is a [bug in how Chrome (dating back from 2012)](https://code.google.com/p/chromium/issues/detail?id=122548) considers an internal redirect to be just as insecure as an external one. (Chris Evans seems to be the one who pointed out that [insecure redirects can be an attacking point on HTTPS](https://conference.hitb.org/hitbsecconf2009dubai/materials/D2T2%20-%20Chris%20Evans%20and%20Billy%20Rios%20-%20Cross%20Domain%20Leakiness.pdf) and the Chromium team correctly [squashed all insecure redirects](http://googleonlinesecurity.blogspot.ca/2011/06/trying-to-end-mixed-scripting.html) after a [few](https://code.google.com/p/chromium/issues/detail?id=238484) [tries](https://code.google.com/p/chromium/issues/detail?id=7338). I don't see any consideration given for internal extensions vs. external content.) @pde brought up years ago that this is a pretty annoying bug for us; an extension can already do whatever the heck it wants on a page, so you better darn well hope it meets the definition of "secure". 

Firefox is taking the same view, [they've corrected the issue of external redirect requests being considered secure](https://bugzilla.mozilla.org/show_bug.cgi?id=418354). I'm not sure what the current state is for extensions, but I thought I should point it out if anyone feels like testing it.

For the tl;dr part, I can basically think of three ways to solve this.

1. Convince the Chromium team to consider internal redirects to always be secure. I don't think this would create any attack vector, but feel free to correct me.
2. Fake HSTS with HTTPS Everywhere. This is also currently [not possible with Chrome](https://code.google.com/p/chromium/issues/detail?id=313965). Also likely to introduce lots of headaches dealing with Regular Expression exceptions.
3. Have HTTPS Everywhere fetch content itself and inject it as if it were local data (e.g., data URI images instead of issuing a `307 Internal Redirect`). This feels like it would be a major hack job, probably have performance issues and possibly undermine security if things aren't done carefully.

**Comment by semenko** [comment] 2015-12-17 20:34
Going to close this again -- as you wrote above, it's just something we can't fix: https://code.google.com/p/chromium/issues/detail?id=122548

(Plus there's no HSTS API available, and injecting / fetching content ourselves would absolutely destroy the extension's performance.)

**Closed by semenko** 2015-12-17 20:34 UTC
