### ISSUE TITLE
HTTPS Everywhere is blocked from being installed on Firefox Developer Edition (and Firefox 42+)

### ISSUE THREAD

**Issue by toothbrush7777777** [EFForg/https-everywhere#2526] opened 2015-08-11 18:03 UTC
Since HTTPS Everywhere is not signed, and Mozilla now require signing of addons, it's impossible to use it on Firefox Developer Edition (without disabling an option).
Is it possible to have it signed? Besides, Firefox 42+ is going to require signing.

**Comment by reedy** [comment] 2015-08-11 18:14
Dupe of #2051

**Closed by reedy** 2015-08-11 18:14 UTC

**Comment by toothbrush7777777** [comment] 2015-08-11 18:32
@reedy Sorry, I didn't notice that one.
