### ISSUE TITLE
Add rule for Cvs.com

### ISSUE THREAD

**Issue by robatino** [EFForg/https-everywhere#9697] opened 2017-04-28 09:23 UTC
HTTPS Everywhere currently doesn't have a rule for Cvs.com, so http://www.cvs.com doesn't redirect to https://www.cvs.com as it should.

**Comment by Bisaloo** [comment] 2017-04-28 11:17
For anyone interested in working on this, some work has already been done in https://github.com/EFForg/https-everywhere/pull/6641.

**Comment by gloomy-ghost** [comment] 2017-08-27 10:21
Thanks @Bisaloo, closing as duplicate of #5599

**Closed by gloomy-ghost** 2017-08-27 10:21 UTC
