### ISSUE TITLE
breaks Wix site

### ISSUE THREAD

**Issue by roweger** [EFForg/https-everywhere#6196] opened 2016-08-10 06:20 UTC
http://www.gjj-gh.com/ 

shows up blank. Works with httpseverywhere disabled.

**Comment by tomwys** [comment] 2016-08-12 17:41
I have reproduced this. It is related to rule "Wix static.com".

**Comment by PotcFdk** [comment] 2016-10-02 22:43
Can't reproduce with Firefox 49.0.1 and HTTPSE 5.2.5. Are you sure you're running the site's scripts? When trying around with NoScript it seems that `storage.googleapis.com` needs to be loaded, or else the page stays blank. Enabling or disabling HTTPSE didn't make any difference for me.

**Comment by HTTPSNowhere** [comment] 2017-07-13 12:11
@jeremyn Issue is not reproducible, can you please close this issue?

**Comment by HTTPSNowhere** [comment] 2017-07-20 10:41
@J0WI Issue is not reproducible, can you please close this issue?

**Closed** 2017-07-20 13:26 UTC
Labels: ruleset-bug
