### ISSUE TITLE
Images broken on www.ok.ru

### ISSUE THREAD

**Issue by pde** [EFForg/https-everywhere#2924] opened 2015-09-17 21:10 UTC
Reported for Opera [here](https://addons.opera.com/en/extensions/details/https-everywhere/?display=en&reports#r130045).

When this ticket is closed, let's be sure to reply to the original report.

**Comment by J0WI** [comment] 2016-05-11 23:15
Maybe a dupe of #3228

**Comment by J0WI** [comment] 2018-06-15 17:39
See https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Ok.ru.xml

**Closed by J0WI** 2018-06-15 17:39 UTC
Labels: ruleset-bug
