### ISSUE TITLE
Chrome says: This extension may have been corrupted.

### ISSUE THREAD

**Issue by peterbrinck** [EFForg/https-everywhere#6766] opened 2016-09-06 08:12 UTC
After the latest update, Chrome says: This extension may have been corrupted.

**Comment by anand-bhat** [comment] 2016-09-06 15:10
Reported and being tracked via Issue https://github.com/EFForg/https-everywhere/issues/5874.

**Comment by jeremyn** [comment] 2016-09-06 15:22
I'm closing this as a duplicate of #5874.

**Closed by jeremyn** 2016-09-06 15:22 UTC

**Comment by peterbrinck** [comment] 2016-09-06 19:36
Oh, sorry
I didn't see there already was one

**Comment by jeremyn** [comment] 2016-09-06 19:39
@peterbrinck That's fine, you're not the only one.
