### ISSUE TITLE
Flickr logins don't work (Firefox only?)

### ISSUE THREAD

**Issue by BillWeiss** [EFForg/https-everywhere#728] opened 2014-11-11 03:49 UTC
In Firefox, running HTTPS Everywhere 4.0.2 with the default ruleset, attempting to log in to Flickr leads to a page with the below text (at https://www.flickr.com/register_cookies.gne, titled "no cookied") after logging in.  Disabling the Flickr rule (but keeping the "Yahoo! (partial)" rule enabled) fixes this.  I don't see the same issue in Chrome running the same rules and HTTPS Everywhere 2014.9.11 (which seems current?).

```
Ooops
  	

Your registration was successful.

However, we couldn't log you in automatically because it looks like you don't have cookies enabled.

There are a few options:

    Clear your existing Flickr cookies
    Check that your cookies are actually enabled (Click here for instructions on how to enable your cookies.)
    If you've done both of these things, and restarted your browser, and tried to log in and it's still not working, please contact us.

Here's a link to the login page.
```

**Comment by l0b0** [comment] 2015-03-19 22:31
Seems like this is still an issue - I'm still getting the same message as OP with Firefox 36.0.1. Tried various privacy settings (including setting them to the default "Remember history"), clearing cache and cookies, restarting and even rebooting, but nothing worked until I disabled HTTPS Everywhere. Or has the fix not yet been released?

**Comment by jsha** [comment] 2015-03-19 22:50
The fix is released in the latest 5.0development.3, a candidate to become the next stable version. If you'd like to try it out, please do! https://eff.org/https-everywhere/#install-development

**Comment by danfournier** [comment] 2015-04-30 11:57
FF 37.0.2 with SSL Everywhere 5.0.3 still seems to behave the same way?

**Comment by jsha** [comment] 2015-04-30 19:27
@2d1 can you look at this?

**Comment by jschauma** [comment] 2015-10-10 21:41
This appears to still be an issue in https-everywhere 5.1.1 with Firefox 41.0.1 and Chrome  45.0.2454.101.  See also: https://twitter.com/xor/status/652856846462660612

**Comment by diracdeltas** [comment] 2015-10-14 16:29
I can't seem to repro this in Chrome 46.0.2490.71 or FF 41.0.1 with 5.1.1 (OSX) so maybe it's an edge case. Can someone who has this problem verify that disabling the Flickr rule (as opposed to Yahoo) fixes this?

**Comment by Bisaloo** [comment] 2016-03-06 17:17
Ok, that's strange. I can reproduce in FF 44.0.2 (Ubuntu 14.04) but not in Chromium 48.0.2564.116

I thought it may be due to another add-on (like privacy badger) but everything works fine when I disable the Flickr.com rule.

**Comment by J0WI** [comment] 2016-05-11 21:28
This should be fixed in #1577

**Comment by Bisaloo** [comment] 2016-05-12 05:30
Not fixed in FF 46.0 and HTTPSE 5.1.9

**Comment by J0WI** [comment] 2016-05-14 15:28
@Balgden could you compare what cookies are set with and without a secure flag, once with HTTPS Everywhere enabled and once disabled?

Please tell us the difference (watch out that you leak no sensitive information).

**Comment by Balgden** [comment] 2016-05-16 23:17
@J0WI: Since I have no idea what this is about, I don't think you wanted to ping me.

**Comment by J0WI** [comment] 2016-05-16 23:47
Sorry, wrong auto completion. I ment @Bisaloo

**Comment by Bisaloo** [comment] 2016-05-17 19:19
List of cookies created with the rule enabled:

- BX
- _current_identity_
- ffs
- flrb
- flrbcr
- flrbgdrp
- flrbgmrp
- flrbgrp
- flrbp
- flrbrst
- flrbs
- flrtags
- localization
- xb

All of them are secure at the exclusion of `current_identity`.

None of them is secure with the rule disabled.

**Closed** 2016-07-14 21:31 UTC
Labels: ruleset-bug
