### ISSUE TITLE
Error "This extension may have been corrupted"

### ISSUE THREAD

**Issue by ntwb** [EFForg/https-everywhere#6506] opened 2016-08-21 02:58 UTC
![screen shot 2016-08-21 at 12 50 34 pm](https://cloud.githubusercontent.com/assets/1016458/17835096/c7d170b2-679e-11e6-82d0-84b443e99633.png)

Running `Repair` does not resolve the issue.

Removing the extension and reinstalling results in the same warning message being displayed:

`This extension may have been corrupted`

**Comment by J0WI** [comment] 2016-08-21 23:00
Do you tried to install the extension from https://www.eff.org/https-everywhere?

**Comment by ntwb** [comment] 2016-08-21 23:10
> Do you tried to install the extension from https://www.eff.org/https-everywhere?

Yes, that's where I reinstalled it from after removing it.

**Comment by ntwb** [comment] 2016-08-21 23:14
I just removed the extension once again.

Visited: https://www.eff.org/https-everywhere

Clicked: https://chrome.google.com/webstore/detail/gcbommkclmclpchllfjekcdonpmejbdp

Clicked: "Add to Chrome"

This time it has worked and no warning, everything working as expected /shrug

**Comment by nucular** [comment] 2016-09-03 20:04
This is still happening for me on Chrome 54.0.2840.8 dev-m.

**Comment by viking** [comment] 2016-10-03 14:56
I'm still experiencing this problem. I tried removing the extension, and then installing it from the EFF site. The icon immediately disappears and I get the same message about it being corrupted.

**Comment by viking** [comment] 2016-10-03 15:06
Chrome version: 53.0.2785.92
HTTPS Everywhere version: 2016.9.21

**Comment by olsh** [comment] 2016-10-04 12:42
The same problem and the same versions of software.

**Comment by novashultz** [comment] 2016-10-04 15:45
Same problem

**Comment by Jwpe** [comment] 2016-10-04 19:07
I am experiencing this issue on:
Google Chrome 53.0.2785.143 
HTTPS Everywhere 2016.9.21

**Comment by J0WI** [comment] 2016-10-05 21:20
@jsha since @Hainish is ooo, could you have a look here?
cc @cooperq

**Comment by TomRoche** [comment] 2016-10-06 04:10
**Summary:** I'm experiencing this problem, but only in Chrome: I successfully installed Firefox extension on same box, which is running:

    $ date
    Wed Oct  5 20:56:55 MST 2016
    $ uname -rsv
    Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02)
    $ lsb_release -ds
    LMDE 2 Betsy
    $ cat /etc/debian_version
    8.5
    $ gcc --version | head -n 1
    gcc (Debian 4.9.2-10) 4.9.2
    $ google-chrome-stable --version
    Google Chrome 53.0.2785.92

**Procedure:**

`0.` start Chrome

`1.` browse to https://www.eff.org/https-everywhere

`2.` click icon/link='Install in Chrome' -> https://chrome.google.com/webstore/detail/gcbommkclmclpchllfjekcdonpmejbdp

`3.` HTTPSE appears to install, but when I goto 'More Tools'>Extensions, I see

    HTTPS Everywhere 2016.9.21
    This extension may have been corrupted
    ...
    ID: gcbommkclmclpchllfjekcdonpmejbdp

`4.` click link=Repair: no change

`5.` Try restarting Chrome and rechecking 'More Tools'>Extensions: no change

`6.` remove extension from Chrome

`7.` restart Chrome, browse to https://www.eff.org/https-everywhere , scroll down, follow link to FAQ entry=https://github.com/EFForg/https-everywhere/issues/6506 . Does not apply: different error semantics, and caused by Avast anti-virus which I don't run.

`8.` Try installing from direct link=https://www.eff.org/files/https-everywhere-chrome-2016.9.21.crx :

`8.1.` Download https://www.eff.org/files/https-everywhere-chrome-2016.9.21.crx to /tmp/https-everywhere-chrome-2016.9.21.crx

`8.2.` goto 'More Tools'>Extensions

`8.3.` set checkbox='Developer mode', hit button='Load unpacked extension...': in file chooser, /tmp/https-everywhere-chrome-2016.9.21.crx is shown but unselectable

`9.` repeat steps 1-4: no change

`10.` remove extension from Chrome

**Comment by jeremyn** [comment] 2016-10-06 13:55
I'm closing this as a duplicate of #5874 . Please see https://github.com/EFForg/https-everywhere/issues/5874#issuecomment-249885095 and the related discussion for more information and a workaround, and report any further related problems on that issue.

**Closed by jeremyn** 2016-10-06 13:55 UTC
Labels: chrome, High Priority
