### ISSUE TITLE
Lenovo unable to customize computers or see "Sold Out" when enabled in https-everywhere

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#1656] opened 2015-05-09 15:10 UTC
Eg:
http://shop.lenovo.com/us/en/laptops/thinkpad/x-series/x1-carbon/

Fixed by disabling Lenovo in https-everywhere

**Comment by reedy** [comment] 2015-06-03 22:31
Confirmed

**Comment by pde** [comment] 2016-03-29 05:40
Ugh, I just encountered across this.  If we can't get a fix, we should disable the ruleset by default :(. CC: @Hainish @loveithateit

**Comment by KommX** [comment] 2016-05-25 06:59
This bug is still present.

Test case:
http://shop.lenovo.com/us/en/laptops/thinkpad/t-series/t460s/

**Comment by Hainish** [comment] 2016-06-03 01:26
@galeksandrp are you working on a full review of this ruleset?  If not, I think we should disable/delete it.

**Comment by coman4** [comment] 2016-11-01 19:08
Did it get worse? The links referenced above now show a blank page. Other links like this one [http://shop.lenovo.com/us/en/smartphones/phab-series/phab2/] looks very broken. They're all fixed if HTTPS Everywhere is disabled.

**Comment by jwarkentin** [comment] 2017-03-29 19:12
Still very broken. It took me a while to figure out which extension was breaking things.

Example: http://shop.lenovo.com/us/en/laptops/thinkpad/t-series/t570

**Comment by jwarkentin** [comment] 2017-03-29 19:24
Looks like the problem is that even though lenovo.com supports https there is a single request that is not getting blocked but returning a 509 "bandwidth exceeded" error code when made with https. When I make the request over http it returns a larg(-ish) response body. I'm guessing lenovo has configured their servers to refuse to serve large requests over https. Is it possible to add a rule that will retry a request with http when it gets a 509 error code?

**Comment by Hainish** [comment] 2017-03-29 21:31
There's a lot in the Lenovo rule, but it looks like only the `shop.lenovo.com` subdomain has been having problems.  I think disabling that `target` and the associated `rules`, `exceptions`, and `tests` should do fix this.

**Comment by Hainish** [comment] 2017-03-29 21:32
If a whole lot of extra work is required when this ruleset is modified due to the file hash no longer matching the whitelists, I think it's fine to re-whitelist rather than fix a bunch of unrelated problems

**Comment by J0WI** [comment] 2017-04-10 20:31
Closed by #9381

**Closed by J0WI** 2017-04-10 20:31 UTC
Labels: ruleset-bug
