### ISSUE TITLE
Automated DNS lookups on Firefox startup with HTTPS Everywhere enabled

### ISSUE THREAD

**Issue by username4650** [EFForg/https-everywhere#3354] opened 2015-12-02 23:19 UTC
HTTPS Everywhere is causing two DNS lookups whenever I start Firefox with the extension enabled. It only occurs when HTTPS Everywhere is enabled. The Observatory feature is turned off. I tried toggling various about:config observatory entries but could not prevent the browser from doing the DNS lookups. I know this possibly has something to do with checking to see if Tor is being used, so that the SSL certificate checks can be sent through Tor, but if the observatory is disabled, it should not be happening. Only the two DNS looksups (on port 53) were noticed. No other connections (e.g. to check.torproject.org) occur, although it's possible others were attempted and blocked by my firewall settings. This seems like it's bad for privacy/tracking/fingerprinting if the same DNS queries are being sent out every time Firefox is started. Is there an about:config setting that can be changed to prevent this, or is this a bug?

**Comment by fuglede** [comment] 2015-12-05 18:59
Duplicate of #2719.

**Comment by rugk** [comment] 2015-12-05 22:00
Why not close it if this is a duplicate?

**Closed** 2015-12-15 23:45 UTC
