### ISSUE TITLE
amazon.in - "Today's Deal" page does not support https

### ISSUE THREAD

**Issue by anantoghosh** [EFForg/https-everywhere#7414] opened 2016-10-22 16:41 UTC
http://www.amazon.in/gp/goldbox/ breaks.
The current exclusion rule does not filter this url.

https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/amazon.in.xml

**Comment by anantoghosh** [comment] 2016-10-22 16:52
![image](https://cloud.githubusercontent.com/assets/12339068/19620987/bf32dae4-98a5-11e6-9299-b69c6f69b933.png)
Some other pages also don't work.
It looks like every url with /gp/ breaks.

**Comment by anantoghosh** [comment] 2016-10-22 16:58
![image](https://cloud.githubusercontent.com/assets/12339068/19621024/c3a752c0-98a6-11e6-87d0-037eb0cbf1cf.png)
/xa/ too

**Comment by J0WI** [comment] 2016-10-23 14:07
This is a dupe of #6157
Thanks for posting the useful details about the blocked requests.

**Closed by J0WI** 2016-10-23 14:07 UTC
