### ISSUE TITLE
Do not route if address is available locally by another extension

### ISSUE THREAD

**Issue by midzer** [EFForg/https-everywhere#9939] opened 2017-05-15 05:25 UTC
Hi all,
i use HTTPS Everywhere in combination with https://github.com/Synzvato/decentraleyes. The latter stores libraries to serve them locally without the need to fetch from CDNs.

Sometimes there is a warning in Chromium Extensions log:
> Die Erweiterung konnte die Netzwerkanfrage nicht an chrome-extension://ldpochfccmkkmhdbclfhpagapcfdljkj/resources/jquery/1.7.2/jquery.min.js.dec weiterleiten, da eine andere Erweiterung (HTTPS Everywhere) sie an https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js weitergeleitet hat.

decentraleyes wants to deliver local jquery.min.js library, but HTTPS everywhere routes request to Google CDN in any case.

I would prefer local file to be served by decentraleyes and HTTPS Everywhere skipping it's job in this situation.

Have a nice day
midzer

**Comment by numismatika** [comment] 2017-05-15 10:32
As far as i know the most recently installed extension wins.
I also get IPv6 icons and rule hits for stuff that my Content Blocker already removed or cert warnings.
I think the underlying issue is a bit bigger.

**Comment by jeremyn** [comment] 2017-05-15 15:05
Thanks for the report, however I'm closing this as a duplicate of issue https://github.com/EFForg/https-everywhere/issues/9404.

**Closed by jeremyn** 2017-05-15 15:05 UTC
