### ISSUE TITLE
Extension messes up images in Tumblr

### ISSUE THREAD

**Issue by lydialaurenson** [EFForg/https-everywhere#1196] opened 2015-03-13 22:56 UTC
Hello!  

I love HTTPS everywhere but I have to disable it because it's messing up some stuff in Tumblr.  This just started recently, within the last few weeks, but I'm not sure when exactly.  Here is the problem:  

When HTTPS everywhere is enabled, I can't post images on Tumblr -- they display as a broken image. I tried as both a PNG format and a JPEG format. Additionally, my last 3 incoming submissions all display as broken images when the extension is enabled.  

Thanks for all your awesome work!!  
Love, 
Lydia

**Comment by faustocarrera** [comment] 2015-03-15 22:33
Same problem here.
Firefox 36.0.1
Ubuntu 14.04
HTTPS everywhere 4.0.3
When HTTPS everywhere is active, seems the images are not loaded from https://media.tumblr.com instead it try to load from https://gs1.wac.edgecastcdn.net/8019B6/data.tumblr.com with a 403 error.
Disabling the Addon fixes the problem.
[Image sample affected](https://gs1.wac.edgecastcdn.net/8019B6/data.tumblr.com/b4981630c4202ff214ddf1fccb77372c/tumblr_nl9htflRPg1qzp9cfo1_500.jpg)

**Comment by jsha** [comment] 2015-03-16 18:18
Hi,

Can you try installing the latest development version from https://eff.org/https-everywhere#install-development? It may be fixed in the development version, which will soon become the stable version.

**Comment by faustocarrera** [comment] 2015-03-16 18:49
That fixed the problem.
Thanks

**Comment by morganmay** [comment] 2015-03-19 20:03
I also had this problem, and installing the development version appears to have fixed it.

**Comment by DJDBgr** [comment] 2015-03-24 01:36
I also had this problem with Opera and Firefox, using the latest dev version fixed it.

**Comment by J0WI** [comment] 2015-07-14 15:15
@DJDBgr do you have any news for us?

**Comment by semenko** [comment] 2015-12-17 20:06
Closing, as this issue is >6 months old and may be resolved or invalid. Feel free to reopen or send a pull request if you think it's still a bug.

**Comment by ThiefMaster** [comment] 2016-09-20 06:50
It's still a problem. http://24.media.tumblr.com/d2f87e51824a1afddfdee9036a5065bf/tumblr_mtf5uaTHZu1rarjvco1_250.gif is fine via http but not via https for example.

**Comment by J0WI** [comment] 2016-09-20 11:09
@ThiefMaster I get an "AccessDenied" XML response on both http and https.

**Comment by ThiefMaster** [comment] 2016-09-20 11:27
That's weird:

```
[adrian@blackhole:~]> http get http://24.media.tumblr.com/d2f87e51824a1afddfdee9036a5065bf/tumblr_mtf5uaTHZu1rarjvco1_250.gif
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Cache-Control: max-age=31536000
Content-Length: 1935
Content-Type: image/gif
Date: Tue, 20 Sep 2016 11:26:35 GMT
Etag: "0b4bbfb6d3a9c17062eaf3caecdb2551"
Last-Modified: Fri, 20 Sep 2013 10:15:48 GMT
Server: ECS (mxp/0FCC)
X-Cache: HIT
x-amz-id-2: TXzPoABvNCDE++yv6PBaaW4j2pdRvFdziI89xGJl8WCK6QMA2LA2lv+89dSHxvLqkcrQHbe4q/k=
x-amz-request-id: 3E9C61C73CC79123
x-amz-version-id: 1c.mIK4O_YehScp1PfVxzUM9KSQwGpe7



+-----------------------------------------+
| NOTE: binary data not shown in terminal |
+-----------------------------------------+

[adrian@blackhole:~]> http get https://24.media.tumblr.com/d2f87e51824a1afddfdee9036a5065bf/tumblr_mtf5uaTHZu1rarjvco1_250.gif
HTTP/1.1 403 Forbidden
Access-Control-Allow-Origin: *
Content-Length: 243
Content-Type: application/xml
Date: Tue, 20 Sep 2016 11:26:37 GMT
Server: AmazonS3
X-EC-Cache-Remote: TCP_MISS
x-amz-id-2: E+2YjFE4e5CsejEs4vUnWGzZ4DPB/JkhMZpUYYJrb5H/yGyjqw7oXylPB0sCD7gBw9Znbx+sKGQ=
x-amz-request-id: 92593EE5D65D6D44

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>92593EE5D65D6D44</RequestId><HostId>E+2YjFE4e5CsejEs4vUnWGzZ4DPB/JkhMZpUYYJrb5H/yGyjqw7oXylPB0sCD7gBw9Znbx+sKGQ=</HostId></Error>
```

**Comment by rEnr3n** [comment] 2016-09-23 05:01
@ThiefMaster I have the same problem with @J0WI regarding that link.

However, this one works using http but not https.
http://38.media.tumblr.com/22c813bc902acb4558c398a32d26442a/tumblr_n8j88a2DzM1r3kk98o1_400.gif

**Comment by J0WI** [comment] 2016-10-20 22:34
this works for me now.

**Comment by J0WI** [comment] 2017-03-29 22:52
I'm closing this again, because there was no more feedback on this and I cannot reproduce with the given examples.

**Closed by J0WI** 2017-03-29 22:52 UTC
Labels: ruleset-bug
