### ISSUE TITLE
label:ruleset-bug senate.gov

### ISSUE THREAD

**Issue by lukeyyang** [EFForg/https-everywhere#3233] opened 2015-11-19 07:16 UTC
Apparently at the moment senate.gov doesn't support HTTPS, while https-everywhere insists on https connection.

**Comment by fuglede** [comment] 2015-11-20 20:10
Thanks for the report. This one is a duplicate of https://github.com/EFForg/https-everywhere/issues/2596.

**Closed** 2015-12-17 21:55 UTC
