### ISSUE TITLE
http://fatlinesofcode.github.io/jquery.smoothwheel/demo/smoothwheel.html is not redirected to HTTPS

### ISSUE THREAD

**Issue by koops76** [EFForg/https-everywhere#11980] opened 2017-08-18 18:51 UTC

**Comment by jeremyn** [comment] 2017-08-19 02:35
Closing as duplicate of #11981 .

**Closed by jeremyn** 2017-08-19 02:35 UTC

**Comment by koops76** [comment] 2017-08-19 07:25
@jeremyn No, I've encountered this in Chrome.
