### ISSUE TITLE
lofter.com Fail to upload images

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#16988] opened 2018-10-26 12:38 UTC
Type: ruleset/website issue
Domain: lofter.com, nos.netease.com

Fail to upload images on lofter.com. The browser tried to upload images to nos.netease.com but failed.

**Comment by Bisaloo** [comment] 2018-10-27 17:56
Hi,

Thank you for your report! Unfortunately, I can't reach this website at all (`HTTP 503`). Maybe someone else will be able to reproduce and fix this. Otherwise, you can try and submit a fix yourself. We have a pretty thorough [contributing guide](https://github.com/EFForg/https-everywhere/blob/master/CONTRIBUTING.md) to help you get started.

**Comment by zoracon** [comment] 2019-02-13 02:29
I'm getting a `301 Moved Permanently` from `lofter.com` and a `403` from `nos.netease.com`

**Comment by pipboy96** [comment] 2019-04-07 10:07
Website not reachable, possibly reachable in Mainland China. Closing for now, since testing for this issue is impossible.

**Closed by pipboy96** 2019-04-07 10:07 UTC
Labels: ruleset-bug
