### ISSUE TITLE
[Firefox] Toolbar icon's new rule count looks too much like a notification

### ISSUE THREAD

**Issue by AgentME** [EFForg/https-everywhere#12308] opened 2017-09-01 08:57 UTC
Did HTTPS Everywhere recently have an update affecting the toolbar icon in Firefox? I thought it didn't look like this before tonight. (I just checked against the old version of the Tor Browser Bundle I had laying around, and its version of HTTPS Everywhere didn't have a counter like this in it.)

![screenshot from 2017-09-01 01-10-06](https://user-images.githubusercontent.com/577345/29961050-f7af3b48-8eb2-11e7-93d0-a82bd872bd73.png)

About literally every time I change tabs, the number either disappears, appears, or changes and distracts me. It's in about the same area of the screen and vaguely styled similar to how Facebook notifications are shown in Facebook, so I thought there was some notification there for me. The modern web has seriously trained me to click on notification icons like that as soon as possible to hopefully get something interesting or make sure my friend doesn't think I'm ignoring them, and *to make the notification go away*. It took me a minute of clicking different things in the dropdown menu looking for a notification before I realized the number was just a count of active rules, and that the ~~notification~~ count wasn't going to go away.

I guess I can just remove the toolbar icon, though I love the project and want it to have the best defaults and was curious if anyone else had this problem. Maybe it could default off, be a different color, or have the count have no background? (EDIT: I finally noticed the "Show Counter" option on the Add-ons page. Another possibility is to show that in the dropdown too.)

-----

... Heh, not really related, but if you right-click on the icon, hit customize, and then close the customize tab, then the HTTPS Everywhere toolbar icon's counter turns red until you switch to a different tab. I'm a little amused how right after I mention that I think the icon looks too much like a Facebook notification icon, I find a bug that makes it look even closer to one. I guess I'm just including this screenshot here as an (accidentally realized) example of a possible design that's undeniably close to Facebook notifications, and to possibly emphasize the similarity of HTTPS Everywhere's current design.

![screenshot from 2017-09-01 01-16-44](https://user-images.githubusercontent.com/577345/29961908-f6e5d674-8eb5-11e7-9f03-722abbf0c907.png)

**Comment by cschanaj** [comment] 2017-09-01 09:24
I can confirm the issue regarding the counter color turning red on "Customize".

Not sure if they are going to change the default behavior (or the color), but I agree it is sort of too catchy now. If possible, I prefer the counter to use a less "eye-catching" color. Best if it is consistent with uBlock. 

![too catchy now](https://i.imgur.com/Yiuswhj.png)

P.S. You can disable the counter by "Tool" > "Add-ons", then click the "Perference" button for "HTTPS Everywhere",.uncheck "Show counter"

**Comment by Bisaloo** [comment] 2017-09-01 10:35
> Maybe it could default off

+1

> EDIT: I finally noticed the "Show Counter" option on the Add-ons page. Another possibility is to show that in the dropdown too.

+1

----

I agree that it's too catchy right now and a white/grey background may be better but:

- it may seem now that way just because it's new and you're not used to it
- I think the color was chosen to match privacy badger's design (as per https://github.com/EFForg/https-everywhere/issues/2470)

**Comment by Bisaloo** [comment] 2017-09-01 10:42
Related discussion in https://github.com/EFForg/https-everywhere/issues/10002.

**Comment by koops76** [comment] 2017-09-01 10:43
It has the same color as Privacy Badger's badge. Won't fix I guess.

**Comment by koops76** [comment] 2017-09-01 10:44
@cschanaj I wonder what changes its color to red though.

**Comment by koops76** [comment] 2017-09-01 10:48
It's much more annoying on mostly dark UI, but browsers we support usually have bright UI.

**Comment by cschanaj** [comment] 2017-09-01 11:47
I think it should be at least default off if we ain't going to change the color. 

- default is a blue
- extension is disabled is grey
- no active ruleset for a website is pale blue (seeming this feature was gone)
- "Block all unencrypted connection" is red

IMHO, there is too many information on the icon of the extension and a default on counter add too much information.

> It has the same color as Privacy Badger's badge. Won't fix I guess.

Our icons have different colors, though. 

> I wonder what changes its color to red though. There's no code that changes the color to anything but green in the extension.

I haven't dig into the UI code at all. sorry.

**Comment by koops76** [comment] 2017-09-01 11:49
@cschanaj The color will be configurable soon. It has become clear that there's demand for it.

**Comment by cschanaj** [comment] 2017-09-01 11:53
@koops76 Personally, I don't recommend configurable colors. It also seem unnecessary for a 'privacy' extension which rewrite HTTP to HTTPS. I'd rather it is default off if the color isn't meant to be changed.

**Comment by koops76** [comment] 2017-09-01 11:55
@cschanaj For some users this color is annoying, for some it's not. We don't want to have the users disable the counter to get rid of annoying color. We want them to choose a color they prefer. Let's set the default the same as uBlock, a more neutral grey color or a less intense green. I prefer the current color though.

**Comment by cschanaj** [comment] 2017-09-01 12:04
What is the disadvantage of disabling the counter?

**Comment by koops76** [comment] 2017-09-01 12:10
@cschanaj The extension icon no longer shows if the extension has rewritten any requests for the current tab. The user will have to open the popup to see if it did.

**Comment by koops76** [comment] 2017-09-01 12:11
@cschanaj @Hainish had asked me to put it into options. He probably did so for a reason. Ask him if it could be moved to popup or is it better to leave it in options.

**Comment by koops76** [comment] 2017-09-01 12:41
@cschanaj I like the current green very much and it's also the color used by PB. Do you think the default should be different? Grey would be even more contrasting with the icon itself. The icon is very colorful and grey badge looks dull compared with it.

**Comment by cschanaj** [comment] 2017-09-01 13:10
@koops76 Honestly, I cannot judge which color is the best. From #1775, I got the impression a lot of https-everywhere user use uBlock as well. It will be great from my perspective to be consistent with that. 

I'd like to note that I am against adding configurable colors, because it seems a unnecessary feature for an extension of this type. (In particular, Privacy Badger does not have configurable colors). 

If a user find the counter more annoying than useful, they will disable it themselves. The best we can do is to make it convenient to change the setting via the popup UI if changing the default behavior is not an option.

**Comment by koops76** [comment] 2017-09-01 13:20
@cschanaj Disabling the counter leads to loss of information if anything is rewritten.

**Comment by J0WI** [comment] 2017-10-30 19:47
I think this has been fixed in #12552

**Closed by J0WI** 2017-10-30 19:47 UTC
