### ISSUE TITLE
Broken redirect for money.cnn.com

### ISSUE THREAD

**Issue by Aimhere2k** [EFForg/https-everywhere#13951] opened 2017-12-12 04:41 UTC
Type: ruleset issue
Domain: money.cnn.com

On the CNN.com homepage, there is a section labeled "Tech", where all the links are supposed to take you to pages on "money.cnn.com". Trouble is, with HTTP Everywhere enabled, those links are redirected to "https://money.cnn.com", which breaks these links. ("money.cnn.com" does not use/support https, "https://money.cnn.com" does not work when typed into a browser's address bar directly.) 

Oddly, this ONLY happens with the "Tech" section on the CNN homepage. There are other links to "money.cnn.com" throughout the homepage which work just fine (and result in a non-HTTPS URL being loaded). I suspect the "Tech" section is being passed through some external analytics tracker, and HTTPS Everywhere isn't coping with that.

**Comment by J0WI** [comment] 2018-01-23 13:33
I'm not able to reproduce this error. `money.cnn.com` is not redirected by HTTPS Everywhere and I can navigate through the site the site without any issues.

**Comment by Bisaloo** [comment] 2018-06-19 09:11
I can't reproduce either. Additionally, it seems that `money.cnn.com` supports HTTPS now. Closing this issue. @Aimhere2k please feel free to re-open or file a new issue if you are still having trouble.

**Closed by Bisaloo** 2018-06-19 09:11 UTC
