### ISSUE TITLE
blocking http://www.linksyssmartwifi.com 

### ISSUE THREAD

**Issue by sTeglo** [EFForg/https-everywhere#4206] opened 2016-02-22 21:58 UTC
I have version 5.1.3 running inside Firefox 44.0.2 and it will not load the Linkssys Smart Wifi page.  This page is used to gain access to my home router from outside my network.  It's sort of big deal for anyone that is using the Linksys Smart Wifi stuff to manage their home router.  I realize that I'm not in the same league as most of you guys but it has good enough functionality for me and it would be great if you could fix this problem. Thanks, love your work!

**Comment by funkydude** [comment] 2016-02-23 16:02
What page are you referring to exactly? I don't have an account, so I can't log in, but simply browsing to https://www.linksyssmartwifi.com/ works fine for me. It displays the account log-in screen.

**Comment by sTeglo** [comment] 2016-02-23 23:10
thanks for taking interest in this issue.  I have uploaded a 90 second video showing you the details   http://1drv.ms/1QBUIrw  (note that you may need to set the resolution to see it clearly - attached screen grab showing the resolution control)

![set resolution on video playback](https://cloud.githubusercontent.com/assets/17417268/13269927/8499aa36-da3f-11e5-9e80-640382783e62.png)

**Comment by funkydude** [comment] 2016-02-24 14:51
Thanks a lot for the video. Unfortunately, I still can't reproduce this. I tried in Chrome on Windows and Firefox on Android, both work over HTTPS fine and both are updated.

I then tried accessing the HTTPS version over a proxy that allows scripts, which also worked.

As a final step I tested the website against the SSL Labs test, and both IPs returned results fine.

I *think* uninstalling an addon removes all related settings? Maybe give that a try.

**Comment by stevenbenner** [comment] 2016-04-16 00:43
@sTeglo Just for clarification, do you experience this problem at home? If not, are you on a network controlled by a Linksys router when this is happening?

**Comment by stevenbenner** [comment] 2016-05-30 17:57
@sTeglo @J0WI - Since pr #4699 has been merged, this issue should be fixed in the next HTTPS Everywhere release.

**Closed** 2016-05-30 17:58 UTC
Labels: ruleset-bug

**Comment by shallowham7** [comment] 2021-05-26 10:58
Nice post..Linksys Smart Routers Installation and Setup  - Setup your linksys router.If you have any query related linksys router, feel free to contact us. We are available 24/7 to help our customers.visit us our site -[]( https://linksyssmartwifinet.com/)

**Comment by shallowham7** [comment] 2021-05-26 10:59
Nice post..Linksys Smart Routers Installation and Setup - Setup your linksys router.If you have any query related linksys router, feel free to contact us. We are available 24/7 to help our customers.visit us our site - **https://linksyssmartwifinet.com/**

**Comment by shallowham7** [comment] 2021-05-26 11:00
I like the efforts you have put in this,regards for all the great blog posts.Thank you,bless you for the article,I might come back later to view out your other posts.We provide router technical help. If you need any help, visit our site: https://l-inksyssmartwifi.com/

**Comment by shallowham7** [comment] 2021-05-26 11:00
Thanks for sharing such a nice post. I really appreciate that please keep on posting more posts like this Thank you.We provide router technical help. If you need any help, visit our site: https://smart-linksyssmartwifi.com/

**Comment by shallowham7** [comment] 2021-05-26 11:01
Nice..Thanks for sharing such a nice post. I really appreciate that please keep on posting more posts like this Thank you.We provide router technical help. If you need any help, visit our site: https://linksyssmartwifi-net.net

**Comment by shallowham7** [comment] 2021-05-26 11:01
Thanks for sharing a great article ...Also if you are Facing issues while accessing Linksys wifi extender setup , you can contact us. or visit us our site:  https://lin-ksyssmartwifi.com/
