### ISSUE TITLE
Breaks some pages of WDR (Westdeutscher Rundfunk) 

### ISSUE THREAD

**Issue by Septa9** [EFForg/https-everywhere#4227] opened 2016-02-26 15:44 UTC
Firefox 43.0.4
Https Everywhere 5.1.4

Filter:
Westdeutscher Rundfunk

Some pages, i.e. https://www.wdr.de/programmvorschau/, are using resources from http://www1.wdr.de/resources/, which FF refuses to load with "Blocked loading mixed active content"

**Comment by funkydude** [comment] 2016-02-26 18:54
The problem is that www1.* doesn't support HTTPS. There's 2 solutions to this.

1) Gather a list of all the broken pages and put them in the ruleset as exclusions

2) Disable the rule for wdr.de

I would lean towards the latter.

**Comment by Septa9** [comment] 2016-02-27 08:50
Thanks for your quick reply.

>2) Disable the rule for wdr.de
>I would lean towards the latter.

Yeah, that's what I'm currently doing. Lazy as I am, I just was hoping that someone else might already have collected an exception list.

**Comment by numismatika** [comment] 2016-02-27 09:58
www1 is using a valid cert but that server redirects to plain.

-  blog.wdr.de
- containerids-id1.wdr.de
- containerids-id2.wdr.de
- containerids-id3.wdr.de
- containerids-id4.wdr.de
- containerids.wdr.de
- deviceids-meda-id1.wdr.de
- deviceids-meda-id2.wdr.de
- deviceids-meda-id3.wdr.de
- deviceids-meda-id4.wdr.de
- deviceids-meda.wdr.de
- deviceids-medp-id1.wdr.de
- deviceids-medp-id2.wdr.de
- deviceids-medp-id3.wdr.de
- deviceids-medp-id4.wdr.de
- deviceids-medp.wdr.de
- deviceids-meds-id1.wdr.de
- deviceids-meds-id2.wdr.de
- deviceids-meds-id3.wdr.de
- deviceids-meds-id4.wdr.de
- deviceids-meds.wdr.de
- deviceids-medt-id1.wdr.de
- deviceids-medt-id2.wdr.de
- deviceids-medt-id3.wdr.de
- deviceids-medt-id4.wdr.de
- deviceids-medt.wdr.de
- exporte.wdr.de
- freundeskreis.einslive.de
- static.freundeskreis.einslive.de
- wdr.de
- www.einsfestival.de
- www.einslive.de
- www.einslivekrone.de
- www.funkhauseuropa.de
- www.lindenstrasse.de
- www.planet-wissen.de
- www.sportschau.de
- www.wdr.de
- www.wdr2.de
- www.wdr3.de
- www.wdr4.de
- www.wdr5.de
- www.wdrmaus.de
- www1.sportschau.de
- www1.wdr.de

Could be supported, but their customer service says it is work in progress.

**Comment by DavidLiedke** [comment] 2018-03-17 16:39
@jeremyn this can be closed. WDR rule updated with PR #14926

**Comment by jeremyn** [comment] 2018-03-18 14:33
@DavidLiedke I can confirm that the example URL https://www.wdr.de/programmvorschau/ looks okay now, even without PR #14926, so I'm closing this issue.

**Closed by jeremyn** 2018-03-18 14:33 UTC
Labels: Good Volunteer Task, broken MCB, ruleset-enhancement
