### ISSUE TITLE
Automatically add HTTPS?!

### ISSUE THREAD

**Issue by maralyndt** [EFForg/https-everywhere#3230] opened 2015-11-19 03:59 UTC
Hi,

I don't really understand why this is not implemented. When I click "block all HTTP", then it simply won't open HTTP pages, and I have to manually type HTTPS in front of them?! Why? Why not simply do this yourself, it would make this plugin actually useable. But when I have to enter HTTPS manually for almost every website I visit, it kinda sucks.

Any ideas?

I am on Chrome. Please give us a way to auto-upgrade ANY non-https request. I don't care if it fails, I can deal with it. I just want to reject all non-HTTPS connections without having to manually fix every 80% of urls...

Thanks!

**Comment by fuglede** [comment] 2015-11-20 20:06
This should be a duplicate of https://github.com/EFForg/https-everywhere/issues/2718.

**Closed** 2015-11-29 21:32 UTC
