### ISSUE TITLE
Add support for Microsoft Edge

### ISSUE THREAD

**Issue by YuriBoiko** [EFForg/https-everywhere#6087] opened 2016-08-06 20:25 UTC
Bring support for Microsoft Edge. You can use converter from Microsoft: https://www.microsoft.com/en-us/store/p/microsoft-edge-extension-toolkit/9nblggh4txvb. Please convert and upload it to store.

**Comment by fuglede** [comment] 2016-08-07 10:54
Duplicate of #5101.

**Closed** 2016-08-09 00:59 UTC
