### ISSUE TITLE
Disable HTTPS Everywhere rule for senate.gov

### ISSUE THREAD

**Issue by dholbert** [EFForg/https-everywhere#7542] opened 2016-11-11 20:41 UTC
HTTPS Everywhere has a rule for senate.gov, but senate.gov appears to be misconfigured for HTTPS.

Right now, these HTTP sites work fine (as plain HTTP, without HTTPS Everywhere installed)
 http://www.senate.gov/index.htm
 http://www.reid.senate.gov/

...but they don't work as HTTPS, and hence HTTPS Everywhere breaks them. Here are the broken HTTPS versions:
  https://www.senate.gov/index.htm (BROKEN)
  https://www.reid.senate.gov/  (BROKEN)

Right now all HTTPS requests at senate.gov subdomains seem to redirect to https://www.senate.gov/ which currently just has an error page that says:
> Request unable to be completed.
> The submitted https request was not able to be completed at this time.
> Please retry your request using http. This may require disabling some browser based plug-ins. "

**Comment by jeremyn** [comment] 2016-11-12 00:03
Thanks for the report, but this is a duplicate of https://github.com/EFForg/https-everywhere/issues/2596 , so I'm closing this.

**Closed by jeremyn** 2016-11-12 00:03 UTC
