### ISSUE TITLE
Custom/debug ruleset UI inaccessible on Firefox 63 on macOS

### ISSUE THREAD

**Issue by markshep** [EFForg/https-everywhere#17128] opened 2018-12-05 13:38 UTC
Type: code issue
Browser: Firefox 63.0.3
OS: macOS 10.13.6

I followed the instructions for accessing the secret UI for editing custom rules:

* Went to `about:addons`
* Clicked "General Settings"
* Pressed Ctrl-Z

Nothing happened.  I also tried ⌘-Z and ⌥-Z but they didn't work either, so I think it's broken on macOS :-(.  Please can this be fixed?

**Comment by Bisaloo** [comment] 2019-01-10 16:33
I want to try to reproduce this but I keep forgetting. Please feel free to ping me if you don't hear back from me soon.

**Comment by Bisaloo** [comment] 2019-01-14 20:39
After thinking it through, I think this issue actually a duplicate of #13731. It's being handled upstream in https://bugzilla.mozilla.org/show_bug.cgi?id=1429624

**Comment by pipboy96** [comment] 2019-03-28 20:16
Duplicate of #13731, solved either upstream by https://bugzilla.mozilla.org/show_bug.cgi?id=1429624 or by #17352.

**Closed by pipboy96** 2019-03-28 20:16 UTC
Labels: firefox
