### ISSUE TITLE
Firefox now disables HTTPS everywhere

### ISSUE THREAD

**Issue by cfr42** [EFForg/https-everywhere#4438] opened 2016-03-21 16:42 UTC
Firefox and HTTPS everywhere are both installed from Fedora 23's repositories.

HTTPS Everywhere is 5.1.4 (although this seems not to be listed among the available releases at https://www.eff.org/https-everywhere which is worrying).

In any case, Firefox reports 

  Nid oedd modd dilysu HTTPS-Everywhere i'w defnyddio yn Firefox ac mae wedi ei analluogi.

Roughly:

  There was no way to validate HTTPS-Everywhere which is used in Firefox and Firefox has disabled it.

There is a link for further information which (as per usual with Mozilla) takes me to a 'Sorry page not found' error on Mozilla's site.

**Comment by funkydude** [comment] 2016-03-24 16:49
@cfr42 If you did not install it from the Firefox store, remove it, and install it from https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/

**Comment by J0WI** [comment] 2016-05-10 17:22
Dupe of #4721

**Closed by J0WI** 2016-05-10 17:22 UTC
