### ISSUE TITLE
Add CSP "upgrade-insecure-requests; block-all-mixed-content"

### ISSUE THREAD

**Issue by intchloe** [EFForg/https-everywhere#3343] opened 2015-11-30 17:29 UTC
Why is this not implemented? It's better than HTTP Nowhere because with this you can visit HTTP-sites, but while you're on HTTPS-sites you will only see content delivered over HTTPS so no mixed content whatsoever. 

Is there a reason behind this?

**Comment by rugk** [comment] 2015-12-05 19:14
duplicate of https://github.com/EFForg/https-everywhere/issues/2115

**Comment by rugk** [comment] 2015-12-05 19:15
As for why HTTPS Everywhere does not just tries HTTPS for every site in normal (not-http-blocking) mode here are more information: https://www.eff.org/https-everywhere/faq#faq-Why-use-a-whitelist-of-sites-that-support-HTTPS?-Why-can%27t-you-try-to-use-HTTPS-for-every-last-site,-and-only-fall-back-to-HTTP-if-it-isn%27t-available?

**Comment by rugk** [comment] 2015-12-05 19:23
Okay, finally I have to admit you mean something else: Do you want to ad the behaviour of "upgrade-insecure-requests" to every website so it always tries to load the mixed content over HTTPS?

However a CSP which would look like `upgrade-insecure-requests; block-all-mixed-content` is actually contradictory, because `upgrade-insecure-requests` tells the browser to try HTTPS and block it if it does not work (or - respectively - fall back to the default behaviour) and `block-all-mixed-content` says the browser should instantly block all mixed content (which is the default for active mixed content, where "active" means all non-static [images] resources are affected).
So only `upgrade-insecure-requests` is the better choice as I do not know what browsers do when both directives are defined.

Related: https://scotthelme.co.uk/migrating-from-http-to-https-ease-the-pain-with-csp-and-hsts/

**Comment by intchloe** [comment] 2015-12-06 21:07
I did not know that `upgrade-insecure-requests` blocked HTTP-requests if the upgrade was not successful. So in that case the `block-all-mixed-content` is unnecessary in this manner.

**Comment by intchloe** [comment] 2015-12-06 21:09
Also, I don't know if it's a good idea to replace this with HTTP Nowhere. The CSP-header should be added (opt-in) on HTTPS-links. This will - like I wrote - block mixed content.

**Comment by rugk** [comment] 2015-12-06 21:45
Just FYI: https://scotthelme.co.uk/migrating-from-http-to-https-ease-the-pain-with-csp-and-hsts/#comment-2395046331 :smiley:

**Comment by jeremyn** [comment] 2017-12-27 20:14
@intchloe Thanks for your suggestion, however I'm closing this issue as a duplicate of issue https://github.com/EFForg/https-everywhere/issues/8506, which has more discussion.

**Closed by jeremyn** 2017-12-27 20:14 UTC
