### ISSUE TITLE
"Connectin not secure" error on aliexpress.com

### ISSUE THREAD

**Issue by mzso** [EFForg/https-everywhere#4786] opened 2016-05-14 11:20 UTC
Hi!

I get this error: https://support.mozilla.org/en-US/kb/what-does-your-connection-is-not-secure-mean?lang=en-US

It's apparently due to the aliexpress.com(partial) rule.
I can't order, add to the cart, or view the shopping cart.

**Comment by J0WI** [comment] 2016-05-14 15:37
Hi

Thanks for you report.
Could you provide an URL of the affected website?

**Comment by J0WI** [comment] 2016-05-14 15:41
This is maybe related to #4772

**Comment by mzso** [comment] 2016-05-14 15:45
?
The website is in the issue name.
The shopping cart url points here: http://shoppingcart.aliexpress.com/shopcart/shopcartDetail.htm

**Comment by davidhedlund** [comment] 2016-07-16 02:36
@fuglede I can confirm that @mzso is right. This bug is 2 months old.

Aliexpress have Alexa global rank 55 so this bug should be fixed ASAP.

**Comment by davidhedlund** [comment] 2016-07-16 02:47
I will move back HTTPS Everywhere from http://directory.fsf.org/wiki/Free_Software_Directory:IceCat_extensions_%28proposed%29#Unstable to the main list once this issue have been solved.

**Comment by J0WI** [comment] 2017-03-06 23:44
This seems to be fixed now.

**Closed by J0WI** 2017-03-06 23:44 UTC
Labels: ruleset-bug

**Comment by davidhedlund** [comment] 2017-03-08 01:11
Great.

**Comment by adilshoukat** [comment] 2021-03-11 21:59
@J0WI the issue seems to be back now
![Screenshot_63](https://user-images.githubusercontent.com/1608798/110860701-ec13c000-82de-11eb-8c0a-602fb347acd1.png)

**Comment by J0WI** [comment] 2021-03-13 19:11
Please open a new one with details.
