### ISSUE TITLE
HTTPS Everywhere broken on Chrome Dev

### ISSUE THREAD

**Issue by ajthemacboy** [EFForg/https-everywhere#6633] opened 2016-08-28 13:39 UTC
HTTPS Everywhere is reported as 'corrupt' on Chrome Dev (my exact version was 54.0.2837.0 dev-m (64 bit)) but works fine on the stable channel. I've tested on two different browsers. I have not tested the Beta or Canary channels. Clicking "Repair" reinstalls the extension with the same error.

This does not occur with any other extensions.

This occurs even when "Extension content verification" is set to Bootstrap in chrome://flags.

This issue also occurs with Privacy Badger and has been reported on its GitHub as well.

**Comment by fuglede** [comment] 2016-08-28 14:04
Possible duplicate of #6506? That one was solved but unfortunately without an explanation of the root cause.

**Comment by ajthemacboy** [comment] 2016-08-28 16:03
Doesn't seem to be the same; both extensions work fine for me on the stable Chrome release, but not on the developer. Possibly some change in the extension API?

**Comment by Hainish** [comment] 2016-08-29 21:52
This is a duplicate of #5874

**Closed** 2016-08-29 21:53 UTC
