### ISSUE TITLE
HTTPS Everywhere does not remember settings

### ISSUE THREAD

**Issue by eternal-sorrow** [EFForg/https-everywhere#15098] opened 2018-04-07 12:10 UTC
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: code issue

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

HTTPS Everywhere conflicts with extension Decentraleyes, which replaces common CDN-served files (scripts, css etc.) with local ones. Issue is pretty much the same as https://github.com/EFForg/https-everywhere/issues/14961.

Also, I tried adding exceptions to HTTPS Everywhere, so that it did not redirect these resources, but they didn't persist. For example, I added several times exception for ajax.googleapis.com, but still getting errors about it.

**Comment by Bisaloo** [comment] 2018-04-07 13:28
Thank you for your report! This sounds like a duplicate of #9404.

Did you follow the instructions here: https://decentraleyes.org/configure-https-everywhere/?

**Comment by eternal-sorrow** [comment] 2018-04-07 13:42
I used search but have not found that issue for some reason. Anyway, I did uncheck rules for CDN domains. I don't remember if I used this convinient page https://decentraleyes.org/configure-https-everywhere/ when I first installed Decentraleyes or not (now I did), but I certainly unchecked some of them (e.g. ajax.googleapis.com) later.

**Comment by Bisaloo** [comment] 2018-04-07 13:55
This sounds like a different issue then. You are saying that HTTPS Everywhere did not remember your settings. Could you edit this issue title to reflect this?

**Comment by eternal-sorrow** [comment] 2018-04-07 22:15
![screenshot from 2018-04-08 08-11-35](https://user-images.githubusercontent.com/4847726/38460797-cd90e05a-3ab0-11e8-9579-ff9f1b0db2dc.png)
Here you are after I disabled them all yesterday. I did not even close browser since then.

**Comment by Bisaloo** [comment] 2018-04-08 12:53
I can't reproduce. Do you have unusual browser settings that may cause this?

**Comment by eternal-sorrow** [comment] 2018-04-08 13:01
A lot of them. Which ones for example can cause this?

**Comment by Hainish** [comment] 2018-09-07 16:51
@eternal-sorrow are you still seeing this?  I'm going to close this but just let us know and I can re-open.

**Closed by Hainish** 2018-09-07 16:51 UTC
