### ISSUE TITLE
ugly icon on status bar

### ISSUE THREAD

**Issue by machinewu** [EFForg/https-everywhere#5719] opened 2016-07-20 13:02 UTC
After auto update 5.2.0 by firefox, I found https erverwhere change the icon. But the icon has no small size.
The large icon show on the status bar is very ugly! Can you set a small size?

before show the icon on status bar:
![bar_before](https://cloud.githubusercontent.com/assets/4166753/16987099/00388828-4ebd-11e6-94c9-588125d74ed5.jpg)

after show on the status bar:
![bar_after](https://cloud.githubusercontent.com/assets/4166753/16987122/1d59bc42-4ebd-11e6-839e-01c9affaa4fc.jpg)

The status bar was stretched!

**Comment by moriar7y** [comment] 2016-07-20 13:45
Confirming this affects Iceweasel 38 on Debian Jesse x64. I attempted to simply remove the additonally-sized icons found in /home/matt/.mozilla/firefox/02las5sc.default/extensions/https-everywhere@eff.org/chrome/skin/, and copy the "icon-active-16.png" file with it renamed to "icon-active-48.png", which is the one that Firefox is using, however it simply re-seized the icon. At this time, I have simply copied the icons into an "old" dir, which causes there to simply be no icon in my toolbar.

![before](https://cloud.githubusercontent.com/assets/10794489/16988499/3723e5a6-4e56-11e6-90d7-02b2545a4bfd.png)

![after](https://cloud.githubusercontent.com/assets/10794489/16988509/3d5e2300-4e56-11e6-95a8-9687340dba8a.png)

**Comment by moriar7y** [comment] 2016-07-20 13:55
Looks like a small change the the "/home/matt/.mozilla/firefox/02las5sc.default/extensions/https-everywhere@eff.org/chrome/skin/https-everywhere.css" file fixes the issue. I'm not sure what sets that file's contents, so I'll leave it to the maintainers to determine. These lines are all I needed to edit to correct the issue (changing the 32 to a 16):


#https-everywhere-button[state="inactive"] > .https-everywhere-button {
  list-style-image: url("chrome://https-everywhere/skin/icon-inactive-16.png");
}
#https-everywhere-button[state="active"] > .https-everywhere-button {
  list-style-image: url("chrome://https-everywhere/skin/icon-active-16.png");
}
#https-everywhere-button[state="disabled"] > .https-everywhere-button {
  list-style-image: url("chrome://https-everywhere/skin/icon-disabled-16.png");
}
#https-everywhere-button[state="blocking"] > .https-everywhere-button {
  list-style-image: url("chrome://https-everywhere/skin/icon-blocking-16.png");
}

**Comment by Hainish** [comment] 2016-07-20 21:44
Can anyone else confirm this fix works for them?

**Comment by Hainish** [comment] 2016-07-20 21:59
@moriar7y can you provide your screen resolution as well?

**Comment by Hainish** [comment] 2016-07-20 22:09
@igorvasnitsky can you confirm this fix works for you?

**Comment by Hainish** [comment] 2016-07-20 23:31
This should be fixed with v 5.2.1.  Open another issue if you see it is not

**Closed by Hainish** 2016-07-20 23:31 UTC

**Comment by igorvasnitsky** [comment] 2016-07-21 00:02
@Hainish, it works for me. Checked in firefox 45.2.0 and chromium 51.0.2704.79, see attached screenshot
![issue5719](https://cloud.githubusercontent.com/assets/20564046/17007208/62272d3c-4eef-11e6-9d13-88dc5fd18bef.png)

**Comment by moriar7y** [comment] 2016-07-21 13:42
Just in case this needs to be revisited, I run two monitors at 1920x1080. Let me know if there are any other details you end up needing.

**Comment by Hainish** [comment] 2016-07-21 17:58
Thanks for the quick work fixing this yesterday @igorvasnitsky, @moriar7y.  I was unable to reproduce but we were getting a fair amount of reports of this, so the quick response is very appreciated.
