### ISSUE TITLE
https://microsoft.com/ uses a wildcard subdomain cert

### ISSUE THREAD

**Issue by nealey** [EFForg/https-everywhere#3234] opened 2015-11-19 17:07 UTC
If you go to http://microsoft.com/, something other than their web server (I am guessing HTTPS everywhere, I can't reproduce it, unfortunately, even in incognito mode) redirects to https://microsoft.com/, which uses a cert issued for *.microsoft.com: this triggers a security message in Chrome and FF.

**Comment by fuglede** [comment] 2015-11-21 21:52
Yep, that's a problem with HTTPS Everywhere. You can reproduce it by disabling the ruleset in the dropdown menu and going to http://microsoft.com. It looks like this could be fixed by redirecting instead http://microsoft.com to https://www.microsoft.com.

**Closed** 2015-11-28 23:57 UTC
Labels: ruleset-bug
