### ISSUE TITLE
Reset to default option?

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#13186] opened 2017-10-16 14:10 UTC
Type: feature request

I recall in older versions of HTTPSE that there used to be a reset to default option to restore sites to their original settings.  This was handy when messing around with things and just wanting to get back to the default, but I haven't seen that setting in multiple versions now.  Any chance we could get it back?

**Comment by bardiharborow** [comment] 2017-10-16 15:50
Duplicate of #10004.

**Closed** 2017-10-16 20:00 UTC
