### ISSUE TITLE
Firefox toolbar toggles bugged when toolbarbutton not in toolbar

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#2016] opened 2015-06-28 14:52 UTC
When the toolbarbutton is in the hamburger menu rather than the toolbar, one can cause the counter toggle to behave badly. It's a bit finicky but this seems to be reproducable on the current master:

Steps to reproduce:
- Move the toolbarbutton from the toolbar to the hamburger menu.
- Disable "show counter"
- Restart browser
- Go to some page with active rulesets.

Expected result:
- The label displaying the number of active rulesets is shown iff "show counter" is checked.

Actual result:
- The label displaying the number of active rulesets is shown iff "show counter" is _not_ checked.

Edit: The same issue occurs with the HTTP Nowhere option.

Edit 2: In fact, this might not even have anything to do with the hamburger menu; I seem to be able to reproduce the above even skipping the first step. It does not seem entirely consistent.

**Comment by fuglede** [comment] 2015-06-28 17:02
Yeah, okay, it seems like [toolbar_button.js#L69](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/toolbar_button.js#L69) is never executed if the toolbarbutton is moved to the hamburger menu

**Comment by fuglede** [comment] 2015-06-28 20:16
Okay, the following monstrosity works. There's probably an easier way.

    var showCounter = tb.shouldShowCounter();
    var counterItem = document.getElementById('https-everywhere-counter-item');
    if (counterItem) {
      counterItem.setAttribute('checked', showCounter);
    } else {
      let palette = document.getElementById("navigator-toolbox").palette;
      for (let c of palette.children)
        if (c.id == 'https-everywhere-button')
          for (let d of c.children)
            if (d.id == 'https-everywhere-context') 
              for (let e of d.children)
                if (e.id == 'https-everywhere-counter-item')
                  e.setAttribute('checked', showCounter);
    }

I can include this with #2009 if you want?

**Comment by NewEraCracker** [comment] 2015-07-20 17:20
I have an, I think, related bug.

With HTTPS Everywhere 5.0.5 the button to open the activation/deactivation menu (the one that has a reset to default option too) worked. Starting from 5.0.6 that button does nothing, you click the menu and nothing happens.

Using Firefox 38.1.0 ESR. At the moment I've downgraded to 5.0.5 which works and disabled automatic updates.

**Comment by NewEraCracker** [comment] 2015-07-20 17:32
Also not working on Tor Browser 4.5.3 (Firefox 31.8.0 ESR). Had to revert to 5.0.5 there as well.

**Comment by jsha** [comment] 2015-07-20 17:56
@NewEraCracker: That popup has been removed in the latest version, and its functionality moved into the icon menu. If you'd like to view the rulesets you've toggled state on, you can visit about:config?filter=https_everywhere.rule_toggle. To search for specific rulesets, you can visit https://www.eff.org/https-everywhere/atlas/.

**Comment by NewEraCracker** [comment] 2015-07-20 20:05
5.0.5 (Functionality works):
https://i.imgur.com/RdDyGnL.png
https://i.imgur.com/Tf2MlU0.png

5.0.7 (Click & does nothing):
https://i.imgur.com/rVCItR5.png

**Comment by jsha** [comment] 2015-07-20 20:15
@NewEraCracker: Yes, that's working as intended. I have a pending pull request (https://github.com/EFForg/https-everywhere/pull/2231) to clarify in the new UI that that menuitem is descriptive rather than clickable.

**Comment by Hainish** [comment] 2017-10-05 22:12
Closing as issue that affected the legacy (deprecated) codebase.

**Closed by Hainish** 2017-10-05 22:12 UTC
