### ISSUE TITLE
[Feature Request] In built rule creator

### ISSUE THREAD

**Issue by zero77** [EFForg/https-everywhere#11728] opened 2017-08-07 12:11 UTC
Rule creating is easy but, for less technical users who want to help by creating and submitting rules to https-everywhere.

Can you please add a simple wizard that creates a rule that can be copied and submitted to GitHub.

Thanks

**Comment by koops76** [comment] 2017-08-07 13:31
Duplicate of #7691.

**Comment by jeremyn** [comment] 2017-08-07 14:53
@koops76 is right that #7691 covers the need for a robust solution and so I'm going to close this issue. However there is also a small script that will generate a minimal ruleset, which is documented [here in `CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/a50b6f21347039b92a12dcebc3d4465fad7167a5/CONTRIBUTING.md#new-rulesets), which may be useful.

**Closed by jeremyn** 2017-08-07 14:53 UTC
