### ISSUE TITLE
3-state logic per-site: encrypt everything, apply rulesets, disable

### ISSUE THREAD

**Issue by mikhaelkh** [EFForg/https-everywhere#18055] opened 2019-06-04 03:23 UTC
Type: code issue

There's 3 possible states of HTTPS Everywhere: EASE, rulesets, disabled.
But only 2 of them are available at any given moment: either rulesets & disabled or EASE & disabled.
I want to use EASE by default, and when it breaks the site, I don't want to completely disable HTTPS Everywhere on the site straightaway, I want to apply rulesets on the site. And then if rulesets are breaking the site, only then I want to disable extension on the site until the ruleset issue is being resolved.

**Comment by Bisaloo** [comment] 2019-06-04 09:21
Thanks for your report!

This sounds like a duplicate of https://github.com/EFForg/https-everywhere/issues/17554. Could you please post there? It may help prioritize this issue.

**Closed by Bisaloo** 2019-06-04 09:21 UTC
