### ISSUE TITLE
Add New ruleset for www.whatreallyhappend.com & www.greatis.net

### ISSUE THREAD

**Issue by rugabunda** [EFForg/https-everywhere#16302] opened 2018-08-16 03:40 UTC
Type: new ruleset

Domain:

www.whatreallyhappened.com
www.greatis.net

**Comment by rugabunda** [comment] 2018-08-16 03:56
Just noticed that enabling https on whatreallyhappened.com causes some youtube videos to break. Please fix this if possible.

**Comment by Bisaloo** [comment] 2018-12-27 13:37
Thank you for your message, I'm closing this as a duplicate of #17060

**Closed by Bisaloo** 2018-12-27 13:37 UTC
Labels: new-ruleset
