### ISSUE TITLE
[Bug] [Chrome Dev Tools] Dark Theme text color

### ISSUE THREAD

**Issue by vikaspotluri123** [EFForg/https-everywhere#9394] opened 2017-04-03 03:03 UTC
Chrome Dev Tools has a dark theme, and when the HTTPS Everywhere Panel is loaded in the dark theme it is almost impossible to read, because it's black text over a grey background. The text color needs to be changed.

**Comment by gloomy-ghost** [comment] 2017-09-01 10:26
duplicate of #4707

**Closed by gloomy-ghost** 2017-09-01 10:26 UTC
Labels: chrome, ui
