### ISSUE TITLE
Enable/Disable rules

### ISSUE THREAD

**Issue by FakeFBI** [EFForg/https-everywhere#2493] opened 2015-08-08 16:05 UTC
I can't open Enable/Disable rules in HttpsEverywhere. Can you fix it at 5.0.8 ?

On windows : http://i.hizliresim.com/OZ7QR5.gif

**Comment by fuglede** [comment] 2015-08-09 21:14
You can enable/disable rules by clicking on the relevant labels from the dropdown menu. The popup menu was removed on purpose in #2121; see that PR for details more details.

**Comment by jsha** [comment] 2015-08-10 19:10
Thanks @fuglede! Closing as duplicate of https://github.com/EFForg/https-everywhere/issues/1683

**Closed** 2015-08-11 14:42 UTC
