### ISSUE TITLE
EASE interstitial page strips some parameters from URLs

### ISSUE THREAD

**Issue by Bisaloo** [EFForg/https-everywhere#17983] opened 2019-05-22 09:21 UTC
Type: code issue

Test page: http://cancerres.aacrjournals.org/cgi/pmidlookup?view=long&pmid=11830520

Result: 
![Screenshot from 2019-05-22 11-20-02](https://user-images.githubusercontent.com/10783929/58163066-9c848000-7c83-11e9-97e9-fdd96544341d.png)

Expected result: the URL listed on the interstitial page should be http://cancerres.aacrjournals.org/cgi/pmidlookup?view=long&pmid=11830520, not http://cancerres.aacrjournals.org/cgi/pmidlookup?view=long

**Comment by pipboy96** [comment] 2019-05-22 15:18
The issue is lack of urlencoding of `&` character in the URL.

**Comment by pipboy96** [comment] 2019-05-22 16:56
Closed by #17985.

**Closed** 2019-05-22 16:56 UTC
Labels: EASE, bug, high priority
