### ISSUE TITLE
CA Extended Validation Indication Disappears (blocking all HTTP request)

### ISSUE THREAD

**Issue by Heyom** [EFForg/https-everywhere#1004] opened 2015-01-31 20:11 UTC
I use HTTPS-Everywhere in Firefox with enabled "Block all HTTP requests" option and I don't get any indication that the website I browse support CA - Extended Validation like Twitter.com or Mega.co.nz nor indicates the Owner of the website, "Owner: This website does not supply ownership information.".

**Comment by jsha** [comment] 2015-02-06 22:45
I believe this is because we block the OCSP request, which is made over HTTP. Since OCSP checking is part of the requirements for EV, the browser downgrades the security indicator to "just plain HTTPS."

This may be a difficult bug to fix. We have a rough idea of which URLs are used for OCSP requests, but so far we have not found a 100% accurate way of doing so.

**Comment by jsha** [comment] 2015-02-06 22:49
Also, note for reproducing: Firefox appears to cache both positive and negative OCSP results, so the best way to test this is to use a fresh profile each time you try to reproduce. The easiest way to do that is with `./test.sh --justrun`.

**Comment by jsha** [comment] 2018-03-02 03:11
Closing; I don't think this is important enough to fix.

Note, in case somebody decides differently in the future: One could probably identify outbound OCSP requests by checking the POST body (if the WebExtension APIs allow that) to see whether it matches the first few bytes of an OCSP structure.

**Closed by jsha** 2018-03-02 03:11 UTC
