### ISSUE TITLE
bitsnoop.com does not work with HTTPS Everywhere enabled

### ISSUE THREAD

**Issue by trubul** [EFForg/https-everywhere#7932] opened 2016-12-20 16:04 UTC
Hey, bitsnoop.com doesn't work with your extension (after you try to search something).

Greets.

**Comment by jeremyn** [comment] 2016-12-21 02:08
Thanks for your report. Please clarify what you mean by "doesn't work". This will help a future reviewer understand the problem even if, for example, the site behavior later changes or you're not available to provide more information.

**Comment by trubul** [comment] 2016-12-22 11:37
After you wrote the phrase you search, it gives you message "This site can’t provide a secure connection
bitsnoop.com sent an invalid response." and link looks like this "https://bitsnoop.com:8080/search/all/searched_text/c/d/1/"

**Comment by advaith1** [comment] 2017-03-29 00:31
I can confirm the issue, but strangely, without the extension it loads fine with TLS.

**Comment by jeremyn** [comment] 2017-03-29 15:39
From browser development tools, it looks like https://bitsnoop.com makes these requests when searching, without HTTPS Everywhere active:

`302`: https://bitsnoop.com/search?q=a&t=all 
`301`: http://bitsnoop.com:8080/search/all/a/c/d/1/
`200`: https://bitsnoop.com/search/all/a/c/d/1/

It seems that it gets a `Secure connection failed` error when rewriting the `8080` URL to HTTPS.

A solution would be to add an `exclusion` for `:8080` URLs.

**Comment by Bisaloo** [comment] 2018-02-22 10:14
According to the landing page on https://bitsnoop.com/, this website shut down. I think it's safe to close this issue.

**Comment by jeremyn** [comment] 2018-02-22 14:38
@Bisaloo I agree and I'm closing this issue accordingly.

@trubul Please let us know if you disagree.

**Closed by jeremyn** 2018-02-22 14:38 UTC
