### ISSUE TITLE
various broken rulesets

### ISSUE THREAD

**Issue by diracdeltas** [EFForg/https-everywhere#4705] opened 2016-05-02 17:55 UTC
Brave excludes these rulesets due to brokenness: https://github.com/brave/browser-laptop/blob/4ba20a2aedde716277fad856e7000538fa9faa44/preload-httpse.js#L15

**Comment by jeremyn** [comment] 2016-08-30 16:47
* Problem: `'Nike.com.xml': 'breaks nikeplus.com'`
Status: http://nikeplus.com is not included in [the rule](https://github.com/EFForg/https-everywhere/blob/f163a0e59e3d65b4ef4860a33bf6e00ec6d92cce/src/chrome/content/rules/Nike.com.xml).

* Problem: `'PJ_Media.xml': 'mixed content on https://pjmedia.com/instapundit/'`
Status: http://pjmedia.com/instapundit/ is excluded [here](https://github.com/EFForg/https-everywhere/blob/a49f7dd1a1f88b921070e05302953a00dc7dca48/src/chrome/content/rules/PJ_Media.xml#L18-L20).

* Problem: `'Slashdot.xml': 'redirect loop on mobile slashdot.org'`
Status: http://m.slashdot.org is not included (see [here](https://github.com/EFForg/https-everywhere/blob/69c44f612773494091ca6be3c4f3a6ed571f9327/src/chrome/content/rules/Slashdot.xml#L44)), and http://mobile.slashdot.org is included [here](https://github.com/EFForg/https-everywhere/blob/69c44f612773494091ca6be3c4f3a6ed571f9327/src/chrome/content/rules/Slashdot.xml#L46) and works for me on Android (redirects to http://slashdot.org ).

* Problem:`'Delta.com.xml': 'https://delta.com does not redirect to https://www.delta.com'`
Status: https://delta.com times out without HTTPS Everywhere, and I'm not sure it's appropriate for the add-on to redirect it when the site itself does not. (Rule is [here](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/Delta.com.xml).)

* Problem: `'Cargo.xml': 'breaks cargocollective.com'`
Status: The rule doesn't match http://cargocollective.com , see [here](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/Cargo.xml#L150-L151).

* Problem: `'TMZ.com.xml': 'breaks www.tmz.com'`
Status: This is a duplicate of issue #4704.

It looks like everything in the reported issue is addressed one way or another. Is there anything left to do on this issue before it's closed?

**Comment by diracdeltas** [comment] 2017-05-15 23:55
i tried this out with the chrome 5.8.2017 version of https everywhere. http://pjmedia.com/instapundit/ is still broken. other things seem fine except the TMZ issue.

**Comment by jeremyn** [comment] 2017-05-19 15:51
Thanks for following up. I'm not really sure what you're saying is still broken, but I'm closing this issue since you say it's okay to do so.

**Closed by jeremyn** 2017-05-19 15:51 UTC
Labels: ruleset-bug
