### ISSUE TITLE
New icons not loading on Chrome

### ISSUE THREAD

**Issue by TheRyuu** [EFForg/https-everywhere#5590] opened 2016-06-30 07:30 UTC
After updating my unpacked extension (to 0822f0a)  I noticed the icon wouldn't load for a second until it finally showed the old icon.  I assume this was because it cached the old icon from the previous version or something like that.  After deleting and freshly installing the extension again now there isn't any icon, just the default Chrome extension symbol.

There are two errors listed for the extension dealing with the failure to load these icons:
- icons/icon-active-38.png
- icons/icon-inactive-38.png

Which were changed/added in bd44a9c.

It's not just the icon in the extension toolbar which is missing, the icon on the extensions page is also missing (I believe that's a bigger version of the one for the extension toolbar).

I'm using the latest Chrome version from the dev branch (53.0.2783.2).  It also occurred on the previous dev version as well (53.0.2774.3).  I don't know if this issue also occurs on the beta/stable release branches.

**Comment by J0WI** [comment] 2016-07-13 11:48
cc @Hainish @jsha

**Comment by Hainish** [comment] 2016-07-13 22:18
@TheRyuu can you provide your OS & version as well?

**Comment by Hainish** [comment] 2016-07-13 22:36
I can not reproduce this as of Google Chrome 53.0.2785.8 dev

**Comment by TheRyuu** [comment] 2016-07-13 22:43
Sorry about that, I should've included that info in the original report.

I'm on Windows 10 64-bit (10.0.10586, i.e. what is fully up to date as of posting this).  The Chrome version I did list but it's the 64-bit version of Chrome although I'm not sure that matters.  I have not yet tested the latest dev version (53.0.2785.8) that I'm currently running so I could try it again.

I use cygwin to "build" HTTPS Everywhere and I load it as an unpacked extension.  There are no permission issues with the files in question as I own all of them and have at least read privileges for all files.

I'm not sure other extensions matter here but I'm also using uBlock and uMatrix.

**Comment by TheRyuu** [comment] 2016-07-13 23:45
Just tried the latest dev version (53.0.2785.8) still the same result.  I should note that I tried it on a completely clean profile with no changes save for loading the unpacked extension.  By default it was using the material design UI although that doesn't matter as the issue occurs even when that's disabled.

**Comment by Hainish** [comment] 2016-07-14 00:04
I'm trying to get ahold of a Win10 development machine to test on.  In the meantime, @J0WI @fuglede @jsha do any of you have access to Win10 x64 to look at this?

**Comment by TheRyuu** [comment] 2016-07-14 00:15
If you need me to test anything just let me know although first it would probably be a good idea to reproduce it to ensure it's not an issue somehow specific to my setup.  Just keep in mind I may not be that familiar with the Chrome developer tools or developing Chrome extensions since web development really isn't my thing.  I am familiar with the other tools involved on Windows (e.g. git, msys2/cygwin, etc).

**Comment by fuglede** [comment] 2016-07-14 07:35
@Hainish: I'm afraid I don't.

**Comment by J0WI** [comment] 2016-07-14 19:42
No Windows here too.

**Comment by Hainish** [comment] 2016-07-15 22:12
I just downloaded the [Windows 10 Stable Microsoft Edge VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and installed Chrome 53.0.2785.8 dev-m (64-bit) and installed HTTPS Everywhere using the method described below.  I could not reproduce the issue - the icons look fine for me, even after uninstalling and re-installing.  Marking this as closed for now.

**Closed by Hainish** 2016-07-15 22:12 UTC
Labels: bug, chrome, ui

**Comment by MisterT87** [comment] 2016-07-19 23:42
Same problem here.

OS: Windows 10 x64 (Build 1511 - with newest updates)
Chrome: 51.0.2704.106 x64 (Stable tree)

In additional: I cant use it anymore. Installation through Chrome Store and on eff.org not possible anymore.
If I want to install it, I am getting: Invalid package - Symbol "icons/icon-active-38.png" couldnt be loaded
