### ISSUE TITLE
Squash and merge

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#5838] opened 2016-07-28 17:26 UTC
@J0WI I think we should squash and merge by default, especially for ruleset changes.  This will make the git history a bit cleaner, especially since PRs are tending to add additional commits just to get the tests to re-run.

https://help.github.com/articles/about-pull-request-merge-squashing/

**Comment by Hainish** [comment] 2016-07-28 17:29
cc @fuglede

**Comment by luixxiul** [comment] 2016-07-28 17:34
like this: https://github.com/EFForg/https-everywhere/pull/5788

**Comment by Hainish** [comment] 2016-07-28 17:37
Ah right, so it looks like this is already being done for the most part.

**Comment by luixxiul** [comment] 2016-07-28 17:41
Hi, I usually squash my commits by myself locally before/after I create a PR. On #5788 commits are not squashed at all

**Comment by Hainish** [comment] 2016-07-28 17:44
I think it's fine if contribs don't squash their PRs, as long as the maintainers do it upon merge.  The end result is the same, but with our range of contributors it's more difficult to enforce on their end.

**Comment by luixxiul** [comment] 2016-07-28 17:52
@Hainish the reason why I do locally is that I tend to forget to pull the squashed commit before making any change on the local repo and mess it up quite badly. It is OK if you do not forget to do that.

**Comment by fuglede** [comment] 2016-07-28 18:36
Noted; I've typically asked contributors to do it themselves for long-winded PRs with more than, say, 3-4 trivial commits, but I'm fine with just doing it upon inclusion. Any hard limits for what is acceptable?

**Comment by Hainish** [comment] 2016-07-28 19:25
@fuglede no universal rule can be made here.  If greater granularity is required, it may make sense to break it out into more than a few commits.  But I mostly envision this happening for features and code changes, and less for ruleset changes.  I could see a PR that, say, included multiple types of sites across a few different rulesets having multiple commits that may make sense.  But in that case it's probably more appropriate to have those changes in multiple PRs and not just one.

**Comment by J0WI** [comment] 2016-07-28 22:49
I like to have unsquashed commits in PR to see what changed since the last feedback.
Squash before merge seems good to me and I'll do this in future.

**Comment by Hainish** [comment] 2016-07-29 00:58
Thanks!

**Comment by fuglede** [comment] 2016-07-29 14:10
Could you activate the GitHub feature to do this automatically for the repo? I never tried it but it looks like it will make the process quite a bit easier.

**Comment by Hainish** [comment] 2016-07-29 16:59
It looks like in the admin UI, I don't have the option to make it default.  I only have the option to uncheck either of the merging methods, which we don't want to do.

**Comment by fuglede** [comment] 2016-07-29 17:38
Ah, I thought it wasn't even on: I can't choose it here:

![github](https://cloud.githubusercontent.com/assets/6169306/17257795/ffa5f6da-55c3-11e6-81e6-43c6390a8008.png)

**Comment by Hainish** [comment] 2016-07-29 18:04
@fuglede after clicking "Merge pull request" an additional dialogue will appear where you can choose the merge methodology

**Comment by fuglede** [comment] 2016-07-29 18:18
Ah, of course, sorry about the confusion.

**Comment by jeremyn** [comment] 2016-08-24 16:00
Reopening because I'm confused.

Up to now I've been doing regular merge commits without squashing. I just tried the web-based squash-and-merge behavior and it seems to make commits like this:

```
commit abcd...
Author: merger_first_name merge_second_name <merger_email@example.com>
Date:   date

    pr_name (#pr_number)

    * first commit message

    * second commit message
```

But when I look at the HTTPS Everywhere git history, it looks like `Author:` is the committer's name and email, not the merger's name and email.

This matters because I feel mildly strongly that we should not be creating commits in other people's names, where `Author:` is the committer.

**Comment by Hainish** [comment] 2016-08-24 18:46
Hey @jeremyn,

As long as the squashed commit has the same code changes as the series of commits, we haven't changed any code from the author.  If we maintain the high-level commit message (perhaps removing some of the interstitial commit messages for clarity's sake) and code made by the original committer, I don't see any problem.

**Comment by jeremyn** [comment] 2016-08-24 21:09
A strong argument against it is that some people GPG-sign their commits, which GitHub can mark as `Verified`. If we squash the commits then we are losing the signatures.

Also, what if one pull request has multiple contributors?

Beyond that though, if someone submits a pull request then they are giving us something specific: code and history. I don't think we should change what we're given at all, code or history.

Anyway, is this really needed? If someone wants to understand unsquashed merge history, they can use a history parser tool like `gitk`. I don't think we should optimize for people trying to understand this codebase's huge history using `git log`.

**Comment by jeremyn** [comment] 2016-08-24 21:15
Also I'm still confused why my own testing of squash-and-merge puts the merger's name on the squashed commit while squash-and-merge in this repository seems to put the committer's name on the squashed commit. Is that a GitHub setting for the repository?

**Comment by Hainish** [comment] 2016-08-24 21:15
These are edge cases.  If someone has GPG-signed commits, we can ask them to squash it themselves.  I've hardly seen any PRs with multiple contributors.

Many pull requests come in with dozens of commits, especially as people are trying to get their rulesets to pass tests.  We should squash these.  It's not necessary to squash merge if there are only a few commits, or if the commits are granular (as described above).

**Comment by jeremyn** [comment] 2016-08-24 21:49
The only thing that requires no discussion between the contributor and maintainer and can have a completely consistent policy among 3+ rule maintainers is to accept the commits we're given without squashing. No edge cases involved.

I started as a rule maintainer only last week. At first I asked contributors to squash their commits to keep the history clean, like you're talking about in this issue. In that short time:

* I had to explain to one contributor what squashing is.
* Another contributor closed their pull request without merging following what I think was a disagreement between them and me about the possible contents of the squashed commit message. This outcome is still a lot better than the alternative (which didn't happen) of me squashing and merging their commits only to find out later, when it's too late, that this made them unhappy.
* Another contributor squashed their own commits and introduced an error, so basically user-squashes have to be completely re-reviewed.

This is in less than a week.

I don't ask users to squash their commits anymore. I really think that contributors should be strongly discouraged from squashing (to avoid regressions and increased review time per pull request) and maintainers should not do any squashing (to avoid surprising users, and to avoid the need for discussing this with them, and to avoid the need for maintainers to have to constantly make judgment calls about squashing).

Is there any significant technical reason why squashing is a good idea, other than to make it easier to review the history using `git log` or other simple tools?

**Comment by J0WI** [comment] 2016-08-25 01:20
see also #6582 btw.

> Is there any significant technical reason why squashing is a good idea, other than to make it easier to review the history using git log or other simple tools?

We have tenthousands of commits and rules. This already results in a huge repository and it takes minutes to produce a git log for a specific file.

**Comment by jeremyn** [comment] 2016-08-25 13:44
I can run a command-line `git blame` on different ruleset files in seconds on a VM with 4GB RAM allocated.

**Comment by jeremyn** [comment] 2016-08-27 16:03
After some more thought, here's what I think we can do:

1. A lot of rulesets come from only a few people. If we clear the squash-and-merge approach with those contributors, that will cut down on a lot of excess commits.
2. If a pull request from an infrequent contributor has a lot of trivial commits, perhaps more than three `Update X`, then we can specifically ask them if squash-and-merge is fine for that specific pull request.
3. Otherwise, for infrequent contributors with the usual two commits, one initial commit and one to fix problems found on review, we just do a regular merge.

This way, we can squash a lot of commits, we reduce the number of conversations with contributors about squashing, and we don't surprise anyone with a squash. What do you all think?

**Comment by fuglede** [comment] 2016-08-27 20:27
I'm a heavy user of `git log -p` for bug fixing. This certainly takes a lot more than seconds to do for a given ruleset; more importantly, it is a pain if one has to browse through a collection of trivial fixes to get to the meat). I've always asked contributors to squash their commits when PRs grow too large. I also do not see, why it would need to be cleared; the contributions are already clearly attributed.

> I don't think we should change what we're given at all, code or history.

I disagree. One can come of with diffs that may be interesting locally for the lifetime of a PR ("here's a typo in your ruleset, could you fix that?"), but which are not interesting for the global history.

**Comment by jeremyn** [comment] 2016-08-27 22:25
@fuglede What's a worst-case `git log -p` ruleset for you? I checked `Google.xml` and it took under 15 seconds to get to the end, and `Baidu.xml` took under 8 seconds on a Debian Jessie VM with 4GB RAM and 1 CPU allocated. I consider 15 seconds slightly annoying but manageable.

As I said, I definitely don't want contributors squashing their own commits because it makes it harder to review. In addition to the reasons I gave [here](https://github.com/EFForg/https-everywhere/issues/5838#issuecomment-242219405), earlier today ([here](https://github.com/EFForg/https-everywhere/pull/5239)) I had a contributor squash commits and they added some extra stuff. You can see I'm doing checklists now, the idea being when the checklist is complete then it's ready to merge. So when a contributor squashes their commits, the checklist can be complete but I have to rely on my memory of the original changes to "diff" the new stuff to check, which is obviously a problem.

To be clear, I'm not blaming this contributor at all. In normal code reviews or just code modification in general, it's usually fine to slip in some minor extra changes, which is what they're doing here. The problem is that each line in a ruleset is important so ruleset changes require line-by-line review, so minimal, visible diffs are crucial. So, it's on us to let the contributors know what's best for us.

Whether you personally see it or not, commits do matter to some people. I would be annoyed if my commits were paraphrased in some fashion before being merged. Also I told you that one contributor closed their pull request due to a disagreement about the commit message (see [here](https://github.com/EFForg/https-everywhere/pull/5814)), so it matters to others too.

By the way, I'm not blaming this contributor either. It was their code and work and they had every right to withdraw it for any reason. One of the worst things I think we can do as maintainers is to merge something in that a contributor doesn't want us to merge in for any reason.

**Comment by jeremyn** [comment] 2016-08-27 22:39
Also, for what it's worth, I think I'm saying the same thing Linus is saying [here](https://www.mail-archive.com/dri-devel@lists.sourceforge.net/msg39091.html):

> You must never EVER destroy other peoples history. You must not rebase commits other people did. Basically, if it doesn't have your sign-off on it, it's off limits: you can't rebase it, because it's not yours.

**Comment by fuglede** [comment] 2016-08-28 12:16
`Google.xml` takes 17 seconds.

**Comment by jeremyn** [comment] 2016-08-28 13:45
I'm assuming by the way that all of the maintainers in this discussion are okay with squash-and-merging of their own commits, but please let me know if that's not the case.

**Comment by jeremyn** [comment] 2016-09-08 23:01
Okay after more thought: I still think merge commits are better than squash-and-merge but I guess I'm alone in that, and that's fine. In that case, it's too tedious to ask individual contributors if they're comfortable with squash-and-merge, but they should still be warned. So, I think we need to do two things:

* put a note in the development documentation, either https://www.eff.org/https-everywhere/development or https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md , probably the first one. I can write the text if we agree this is a good idea.
* confirm with contributors who have `Verified` (signed) their commits that are okay with squash-and-merge, if we haven't checked with them previously.

What do you think?

**Comment by Hainish** [comment] 2016-09-09 00:27
@jeremyn this sounds fine to me.  Feel free to write something up and I can review & add to the site.

For those with `Verified` commits, I'd first ask them to squash it, and that way they can maintain the ability to sign their commit.  If they are unwilling to do that, then ask if it's okay if we squash-and-merge.  If they are unwilling to do *that*, then we can deal with the issue on a case-by-case basis.  If there are 100 verified commits for a single ruleset PR, that's a problem and may be the basis of rejecting the PR altogether.

**Comment by jeremyn** [comment] 2016-09-09 15:58
I don't want to ask users to squash their own commits for the reasons described in [this comment](https://github.com/EFForg/https-everywhere/issues/5838#issuecomment-242219405), specifically it can introduce regressions and requires extra review.

Does a GitHub squash-and-merge maintain the user's commit exactly (and signed) if there is only one commit?

**Comment by jeremyn** [comment] 2016-09-15 15:00
> Does a GitHub squash-and-merge maintain the user's commit exactly (and signed) if there is only one commit?

I tested this and it looks like GitHub rewrites a commit (assigns a new hash) even if there is only one commit and the squash-and-merged commit message is the same. So the answer is "no".

**Comment by Hainish** [comment] 2016-09-15 23:19
> I tested this and it looks like GitHub rewrites a commit (assigns a new hash) even if there is only one commit and the squash-and-merged commit message is the same. So the answer is "no".

This is inescapable.  Because squash-and-merge commits are staged on top of HEAD, they change their place in the git log.  This means that the git hash - which is actually a checksum - has to change.

**Comment by jeremyn** [comment] 2016-09-15 23:51
You're right. I had the confused idea that maybe GitHub would do a simple rebase for single commits but since it goes on the (presumably new) HEAD, even a rebase gets a new hash. One could argue that in the specific case that a squash-and-merge is both only one commit and the HEAD for master hasn't changed -- basically a fast-forward merge -- then the hash of that one commit shouldn't change. This was the case in my simple test repository. But that would be a weird edge case for GitHub to code for and it wouldn't help a fast-moving repository like HTTPS Everywhere anyway.

**Comment by gloomy-ghost** [comment] 2016-09-22 07:12
How about to use a [PR Template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) and explain more details using [Guidelines](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)?

If commits are not too much, just leave a checkbox and let contributors choose what they want. If commits are more than that and they disagree to squash-and-merge, ask them to rebase by themselves or consider to rejecte.

**Comment by jeremyn** [comment] 2016-09-22 14:43
Those are good ideas @gloomy-ghost . Also @J0WI [mentioned](https://github.com/EFForg/https-everywhere/pull/6868#issuecomment-248765694) creating a CONTRIBUTING.md file related to their updates to `make-trivial-rule`.

**Comment by jeremyn** [comment] 2016-09-22 14:46
Though I again want to say that I think contributors should be strongly discouraged from squashing their own commits. Also even if they squash down to one commit, the GitHub pull request merge process still (I think) creates a separate merge commit.

**Comment by numismatika** [comment] 2016-10-30 09:45
If you squash commits and the PR has something like

1) add rule for site.com
2) add b,c&d subdomains for site.com
3) remove c & d for serving incomplete chains

do you adjust the commit log for the squashed commit?
2&3 are not necessary to go on record in this case in my opinion

**Comment by jeremyn** [comment] 2016-10-30 14:25
@numismatika It depends on the reviewer. In https://github.com/EFForg/https-everywhere/issues/5838#issuecomment-242169062 @Hainish is okay with removing commit messages from the log like (2) and (3). On the other hand, I want to minimize any changes to what the contributor has given us, so I would leave them in.

**Comment by gloomy-ghost** [comment] 2016-11-06 07:44
Found a strange one here, only reviewer's name is shown.
![image](https://cloud.githubusercontent.com/assets/13086421/20036083/83226b1a-a461-11e6-978d-b36856339015.png)

**Comment by jeremyn** [comment] 2016-11-06 16:03
@gloomy-ghost That user deleted their account. They're listed as @ghost in https://github.com/EFForg/https-everywhere/pull/7506 .

**Closed** 2017-01-07 04:37 UTC
