### ISSUE TITLE
Allow whitelisting domains from "Block all unencrypted requests"

### ISSUE THREAD

**Issue by Ryujinra** [EFForg/https-everywhere#13237] opened 2017-10-20 06:22 UTC
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: feature request

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

Right now, if "Block all unencrypted requests" is enabled, there is no way to whitelist trusted domains that might need to make an unencrypted request.

It would be nice to have a whitelisting option in the "Add rule" dialog that allows you to disable the block for a domain.

Perhaps "Block all unencrypted requests _by default_" would be a more useful feature.

**Comment by Bisaloo** [comment] 2017-10-20 06:41
Duplicate of https://github.com/EFForg/https-everywhere/issues/2299.

**Comment by jeremyn** [comment] 2017-10-20 16:57
I'm closing this as a duplicate of #2299 as @Bisaloo said.

@Ryujinra , please feel free to add comments to that issue if you like.

**Closed by jeremyn** 2017-10-20 16:57 UTC
