### ISSUE TITLE
Nightly extension builds for Chrome and Firefox

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#12015] opened 2017-08-20 16:13 UTC
I think it would be good to have nightly builds for Chromium and Gecko-based browsers generated each day from Git repository snapshots by Travis or another CI solution.

**Comment by koops76** [comment] 2017-08-21 12:06
ping @Hainish.

**Comment by J0WI** [comment] 2017-08-22 00:38
Duplicate of #11805

**Comment by koops76** [comment] 2017-08-22 08:52
@J0WI You probably confused nightly builds with Firefox Nightly update channel.

**Comment by J0WI** [comment] 2017-08-22 13:06
You didn't add any description, so it's hard to guess what you mean.

**Comment by koops76** [comment] 2017-08-22 13:54
@J0WI Re-open please.

**Comment by J0WI** [comment] 2017-08-24 22:18
Please add a description.

**Comment by koops76** [comment] 2017-08-25 16:39
@J0WI Did we have any identical issues?

**Comment by J0WI** [comment] 2017-08-25 16:57
Please clarify how this issue differs from #11805

**Comment by koops76** [comment] 2017-08-25 17:00
@J0WI Done. Remove the duplicate tag please.

**Comment by J0WI** [comment] 2017-08-26 00:37
That's exactly what I would expect from #11805. Maybe not daily, but regular snapshots or prereleases to test new features.

**Comment by koops76** [comment] 2017-08-26 00:45
@J0WI Then ask @Hainish to add the clarification if it is what his issue means.

**Comment by Hainish** [comment] 2017-08-26 00:47
I see a nightly build being different from a dev version.  Usually nightlies are based on the master branch, but the `dev` version is actually pulling from the (as yet unreleased) WebExtensions branch.

**Comment by koops76** [comment] 2017-08-26 00:48
Both should have nightlies built by Travis CI.

**Comment by Hainish** [comment] 2017-08-26 00:51
I'm working on https://github.com/EFForg/https-everywhere/issues/11805 on Monday.

**Comment by koops76** [comment] 2017-08-26 00:54
@Hainish Can you give the list of all rule reviewers? I think there are 5. Needed for #12096. Also is @cowlicks a code reviewer for HTTPS Everywhere?

**Comment by cowlicks** [comment] 2017-08-26 20:19
@koops76 I might be reviewing some code soon, so yes.

**Comment by koops76** [comment] 2017-08-26 20:57
@cowlicks How good are you at crypto? I need more opinions on #12087.

**Closed** 2019-03-28 20:34 UTC
Labels: duplicate
