### ISSUE TITLE
breaks website zattoo.com

### ISSUE THREAD

**Issue by tscpd** [EFForg/https-everywhere#8799] opened 2017-02-25 16:57 UTC
https everywhere 5.2.10 firefox addon breaks website zattoo.com

​https://zattoo.com/login
after login it leads to
​https://zattoo.com/highlights
which is reloading endless than

note its german website: issues for german IP. opening zattoo.com from other coutry-ip's may get redirected to other underside after login.

and also ​https://zattoo.com/logout
is reloading endless after logout

thanks. this a Duplikate of https://trac.torproject.org/projects/tor/ticket/21517

**Comment by Hainish** [comment] 2017-03-11 04:42
Duplicate of https://github.com/EFForg/https-everywhere/issues/8167

**Closed by Hainish** 2017-03-11 04:42 UTC
