### ISSUE TITLE
HTTPS-E rules seem to be ignored when url is in CSS

### ISSUE THREAD

**Issue by pmaziere** [EFForg/https-everywhere#1175] opened 2015-03-09 21:31 UTC
Hi,

I'm using HTTPS-Everywhere along with a private cache ( available at https://github.com/Oros42/CDN_cache ) to cache google fonts. This requires that HTTPS-E hijacks , at first, the requests to fonts.googleapis.com to cache the CSS, and then the CSS requests to fonts.gstatic.com to cache the fonts themselves. The following rules are used:

[target host="fonts.googleapis.com" /]
[rule from="^https?://fonts\.googleapis\.com/css\?(.*)" to="https://MY_HOSTNAME/mycdn/fonts/$1"/]
[target host="fonts.gstatic.com" /]
[rule from="^https?://fonts.gstatic.com/(.*)" to="https://MY_HOSTNAME/mycdn/gstatic-fonts/$1"/]

While the requests to fonts.googleapis.com are redirected to the cache as expected, it seems that the requests to fonts.gstatic.com, initiated from urls located in the just downloaded CSS code, are not redirected. 
Requests to fonts.gstatic.com are correctly put on hold, but they are not replaced by requests to the cache server.

a test case is given here https://github.com/Oros42/CDN_cache/issues/5

Does HTTPS-Everywhere is expected to only hijack requests initiated by HTML code, or should it also do its job on requests initiated by CSS code ? If the later, then can someone help me to fix what I may have done wrong.

Thanks

**Comment by jsha** [comment] 2015-03-09 21:37
It should rewrite all URLs, not just those in HTML. I'll take a look, though it may be a few days. What browser are you on?

**Comment by pmaziere** [comment] 2015-03-09 21:42
Firefox 36.0.1 + HTTPS-E 4.0.3

**Comment by jsha** [comment] 2015-03-17 02:17
Can you provide a URL to load your example HTML?

There may be an issue if your example HTML is hosted on an HTTPS site. Firefox's Mixed Content Blocking will block the request before HTTPS Everywhere gets a chance to rewrite it.

**Comment by pmaziere** [comment] 2015-03-17 08:45
Sorry this is not a public server.

Regarding your suggestion, I verified that every content of my example HTML was sent via HTTPS, and I have set both Firefox settings security.mixed_content.block_active_content and security.mixed_content.block_display_content to false, but the issue is still there

**Comment by jsha** [comment] 2015-03-17 18:58
Do you have a public server you can put your HTML on? For instance, I believe github allows you to host HTML on github.io.

**Comment by pmaziere** [comment] 2015-03-17 22:21
the HTML is available here: http://pastebin.com/yEZ90UGu

**Comment by jsha** [comment] 2015-03-17 22:24
I need a URL that serves it raw and with content-type: text/html in order to test.

**Comment by pmaziere** [comment] 2015-03-17 23:52
that would be there then: https://pmaziere.github.io/cdncachetest/

**Comment by pmaziere** [comment] 2015-03-18 09:53
ok, forget about the above test: it fails because of a Cross domain issue.
this one: https://pmaziere.github.io/cdncachetest/test2.html has everything you need: 
- when https-e rules are inactive, the fonts are downloaded correctly.
- when https-e rules are active, the css request is correctly redirected, but the font urls contained in the css are not even requested, therefore not redirected at all (from what firebug net panel tells me)

**Comment by pmaziere** [comment] 2015-03-18 10:09
Apologies... this is not a HTTPS-E issue, but a cdn_cache issue: the css is not sent with the text/css content-type, which means it is not loaded (downloaded but not injected in the page). And when this is fixed, we are back to the cross domain issue

**Comment by pmaziere** [comment] 2015-03-18 10:52
the cross domain issue seems to happen before HTTPS-E redirection is made:
1/ the css is downloaded from the redirected url and then used
2/ the font url given in the css triggers this error in firefox:
>Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGNNE-IuDiR70wI4zXaKqWCM.ttf. This can be fixed by moving the resource to the same domain or enabling CORS.

So I guess HTTPS-E is not triggered and has not the opportunity to even generate the redirected url.
In this specific case, would it not be more relevant if HTTPS-E ignores this error to get the data from the redirected url ?

**Comment by jsha** [comment] 2015-03-18 19:27
Thanks for digging in further! It looks like this is a duplicate of #49. Please follow that, and when we fix it your issue should be fixed.

**Closed by jsha** 2015-03-18 19:27 UTC
Labels: CORS-bugs
