### ISSUE TITLE
No provision for NON-HTTPS connection on LAN such as for router maintenance

### ISSUE THREAD

**Issue by Jimbazuka** [EFForg/https-everywhere#13511] opened 2017-11-07 07:58 UTC
Type: ruleset issue
Type: other

if "block all unencrypted requests" is set - you can **not** create a rule to connect to
a LAN address such as 192.168.1.1  (for router maintenance etc.) - there is no way to
make a rule (or none I could figure) for such a case. If you uncheck "block all unencrypted requests"
you may encounter unwanted issues such as redirecting to http when you wanted https

**Comment by koops76** [comment] 2017-11-07 08:55
@Jimbazuka You cannot always assume LAN is safe, for example on Wi-Fi connections.

**Comment by jeremyn** [comment] 2017-11-07 14:32
@Jimbazuka Thanks for your report, but I'm closing this issue as a duplicate of issue https://github.com/EFForg/https-everywhere/issues/2323, particularly the whitelist comment in https://github.com/EFForg/https-everywhere/issues/2323#issuecomment-167173181. Please feel free to add comments to that issue if you like. See also issue https://github.com/EFForg/https-everywhere/issues/9142.

**Closed by jeremyn** 2017-11-07 14:32 UTC
