### ISSUE TITLE
 Block all unencrypted requests don't work

### ISSUE THREAD

**Issue by heubergen** [EFForg/https-everywhere#10150] opened 2017-06-04 15:53 UTC
STR:
1. Install the latest Webextensions Version of HTTPS Everywhere for Firefox
2. Activate the option _Block all unencrypted requests_
3. Open http://http.badssl.com/

Expected result:
Site should be blocked

Actual result:
Site ist loaded fine and the option _Block all unencrypted requests_ is deactivated again

**Comment by heubergen** [comment] 2017-06-04 19:26
I think the issue is more that when I activate the option _Block all unencrypted requests_, close the popup and reopen it again, the option is deactivated again...

I did a test with a complety fresh profile and deactivated e10s: ( hope I catch all the important information)
![https-everywhere](https://cloud.githubusercontent.com/assets/5529410/26764706/674c64a8-496c-11e7-8ffd-a18ed80ce074.png)

**Comment by jeremyn** [comment] 2017-06-04 19:58
I'm using Firefox 53.0.3 (stable), not 55 (nightly). Does this happen for you in 53?

**Comment by heubergen** [comment] 2017-06-04 20:06
With FF53 it seems to work for me:
![https-everywhere-stable](https://cloud.githubusercontent.com/assets/5529410/26764979/1ebab5a4-4972-11e7-9117-df3a49cb1b06.png)

**Comment by Hainish** [comment] 2017-06-05 23:58
The WebExtensions version will not be deployed to Firefox < 52.  In your original test, which version were you using?

**Comment by gloomy-ghost** [comment] 2017-06-06 01:10
I can't reproduce this on Firefox 54.0b13 and 55.0a1 (20170605).

@heubergen: It would be great if you could provide some debugging logs. Can you try the following steps and post the outputs?

1. Open about:debugging, turn on "Enable add-on debugging"
2. Find HTTPS Everywhere and click the "Debug" button. Allow connection to open a debugging window
3. Click "Console", type `DEFAULT_LOG_LEVEL=1`, and then try to reproduce the issue.

**Comment by heubergen** [comment] 2017-06-06 20:19
Here we are:
![https-everywhere-1](https://user-images.githubusercontent.com/5529410/26849876-fbb1fe60-4b05-11e7-91cd-4178e53b1a30.png)

This time after I started the debug mode and clicked on the icon the popup was empty:
![https-everywhere-2](https://user-images.githubusercontent.com/5529410/26849943-22c50272-4b06-11e7-82c5-110361a1bd92.png)
after try one more time the popup (seems) works again.

**Comment by Hainish** [comment] 2017-06-06 20:56
@heubergen it is possible that other extensions are interfering with the functionality of HTTPS Everywhere.  The `Error: runtime.sendMessage's extensionId argument is invalid` leads me to believe this may be the case.

Is there a particular other extension which is installed whenever you encounter the issue?

**Comment by heubergen** [comment] 2017-06-06 21:00
@Hainish Just tested again with a fresh profile, sorry for that!  Here the result:
![https-everywhere-3](https://user-images.githubusercontent.com/5529410/26851716-f84835a4-4b0b-11e7-914e-e1362e1553b1.png)

**Comment by Hainish** [comment] 2017-06-06 22:04
I can reproduce this reliably in 55.0a1 (64-bit, Linux).  Still not sure what the underlying problem is, though.  This may be an issue with the `Nightly` channel.  Google comes up with little relevant results.  I'll try to find a Firefox dev to look at this.

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment] 2017-08-18 20:46
i can also confirm this issue on chrome. very strange

**Comment by ivan-kolmychek** [comment] 2017-08-29 13:07
I've encountered this issue both on Chromium (Version 60.0.3112.113 (Developer Build) (64-bit)) and on Firefox (55.0.2 (64-bit)), both on Arch Linux.

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment] 2017-08-29 18:10
opened #12190 as well

**Comment by J0WI** [comment] 2017-09-07 18:41
I think this was a duplicate of #11943. Please reopen if the issue is still around with up to date versions.

**Closed by J0WI** 2017-09-07 18:41 UTC
Labels: webextensions-firefox
