### ISSUE TITLE
Link to privacy policy from about page.

### ISSUE THREAD

**Issue by gerroon** [EFForg/https-everywhere#2179] opened 2015-07-14 15:17 UTC
I cant find the privacy and data collection policy for this addon. It is not clear what kind of data you collect and how you aggregate that data.

thanks

**Comment by jsha** [comment] 2015-07-14 19:05
HTTPS Everywhere is covered under the EFF Privacy Policy: https://www.eff.org/code/privacy/policy, linked from the HTTPS Everywhere homepage: https://www.eff.org/https-everywhere/. But you make a good point: we should also link to it from the About page of each version of the extension. Leaving this ticket open for that purpose and renaming.

**Comment by gerroon** [comment] 2015-07-14 21:41
@jsha 

Thanks for the reply. 

There is one more point. The data retention policy is not clear. I hope that an organization like EFF does not hold on to information gathered from this addon more than couple days.

**Comment by jsha** [comment] 2015-07-14 22:04
@pde was involved in the drafting of the privacy policy, can you answer regarding the data retention question?

**Comment by pipboy96** [comment] 2019-03-28 17:20
Duplicate of #299.

**Closed by pipboy96** 2019-03-28 17:20 UTC
Labels: ui
