### ISSUE TITLE
Enabling SSL Observatory slows down HTTP/2

### ISSUE THREAD

**Issue by lieryan** [EFForg/https-everywhere#4119] opened 2016-02-10 02:05 UTC
To reproduce:
1. disable SSL observatory
2. open https://www.cloudflare.com/http2/
3. note load times of HTTP/1.1 vs HTTP/2
4. enable SSL Observatory, and test again

In my machine, when SSL Observatory is disabled, HTTP/2 Load time consistently takes less than 1s; when SSL Obvservatory is enabled, HTTP/2 Load time is consistently greater than 8s.

As far as I can tell, HTTP/1.1 load time is not noticeably affected.

Firefox 44.0.1, Ubuntu 15.10.

**Comment by blendmaster** [comment] 2016-03-04 06:14
I can reproduce, both this and #4251 . Firefox 44.0.2, Ubuntu 15.10, on a clean profile.

![screenshot from 2016-03-03 23-13-42](https://cloud.githubusercontent.com/assets/546560/13519507/96d3f1a4-e195-11e5-8b79-8b1a28affe8e.png)

**Comment by Jspain** [comment] 2016-07-24 10:24
This is still an issue July 2016, had to disable observatory to have a usable firefox (44.0 for ubuntu)

**Comment by gloomy-ghost** [comment] 2017-11-06 05:52
Closing as obsolete since we have migrated to WebExtension.

**Closed by gloomy-ghost** 2017-11-06 05:52 UTC
