### ISSUE TITLE
Bypassing HTTPS-Eveywhere EASE warning page 

### ISSUE THREAD

**Issue by TNTBOMBOM** [EFForg/https-everywhere#19664] opened 2020-10-10 20:07 UTC
Hi There
I have minor issue for HTTPS-Everywhere blockage requests through EASE, As enabling it should prevent you to go to http/non-https sites without manual confirmation but you can bypass that through running FF or TB in shell + an http version of a website.  to do that for e.g run in terminal: 

`firefox stallman.org`
or
`./start-tor-browser.desktop stallman.org `

We will see that TorBrowser/FF will connect to the website directly and insecurely (plain http regardless to EASE) .

The test done on debian 10 with TB 10.0&FF 78.3.0esr with https-everywhere 2020.8.13

**Comment by pipboy96** [comment] 2020-10-10 20:14
Duplicate of #17716 and #19513.

**Closed** 2020-10-10 21:37 UTC
Labels: bug, duplicate
