### ISSUE TITLE
Feature: temporarily disable HTTPS enforcement on this site, until the session ends

### ISSUE THREAD

**Issue by geekley** [EFForg/https-everywhere#17217] opened 2019-01-04 19:53 UTC
Type: feature request

### Feature
Please make a feature to "Disable HTTPS Everywhere on this site **temporarily**", i.e., only for the current browsing session.
So it would be just like #10041, but instead of adding the site to the list of permanently disabled sites, it would add it to a separate list which lasts only until you close the browser window - after that, this "disabled for current session" list resets to empty.

### Why
I like to leave the "block unencrypted requests" option on, so that I don't enter a HTTP-only website without being warned first. However, when I decide to disable the restriction, I only have the option to do it permanently, and this is often not what I want. I often want to be warned about the site being unencrypted **before** I browse it and **everytime** I browse it, except when I'm OK with adding it as a permanent exception.

### UI Considerations
I suggest to show the option in the extension popup in the following way:
> - [x] Enable HTTPS Everywhere
> - [x] Block all unencrypted requests
>
>
> ### **example.com**
>
> Disable HTTPS enforcement on this site:
> [Permanently](#) | [Only during this session](#)
>
> [Add a new rule for this site](#)

On the warning that shows up when you are about to enter a site that doesn't support HTTPS:
> HTTPS Everywhere noticed you were browsing to blah blah blah ...
>
> URL: **http:/\/example.com**
> Disable HTTPS enforcement on this site:
> [Permanently](#) | [Only during this session](#)

It would be recommended to also change the extension icon when the site is only temporarily disabled.
For example, you can just use a lighter shade of gray, or make it half gray, half normal color:
![image](https://user-images.githubusercontent.com/38332912/50705017-8792b180-1040-11e9-9820-28240d0c9810.png)

**Comment by Bisaloo** [comment] 2019-01-04 20:35
Hi, thanks for reaching out and providing interesting solutions. I'm going to close this as a duplicate of #16998. Please let me know if I misunderstood something and this is a separate issue.

I'd also like to point out that the UI is likely to be completely overhauled at some point. Feel free to comment on #16669 if you have any suggestions.

**Closed by Bisaloo** 2019-01-04 20:35 UTC
