### ISSUE TITLE
Firefox version breaks CORS requests

### ISSUE THREAD

**Issue by PikadudeNo1** [EFForg/https-everywhere#12136] opened 2017-08-27 02:43 UTC
http://brackets.io/#features attempts to load a cross-origin file from s3.amazonaws.com to determine what to show in the New Features section. With HTTPS Everywhere installed and its AmazonWebServices enabled, brackets.io is denied that file and this error appears in the Browser Console:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://s3.amazonaws.com/files.brackets.io/updates/stable/en.json?_=1503800261251. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘(null)’).

Firefox 55.0.3, HTTPS Everywhere 2017.8.19.

**Comment by koops76** [comment] 2017-08-27 02:47
@PikadudeNo1 WebExtensions?

**Comment by cschanaj** [comment] 2017-08-27 03:30
Related #11640

**Comment by gloomy-ghost** [comment] 2017-08-27 06:14
Duplicate of #49

**Closed by gloomy-ghost** 2017-08-27 06:14 UTC
