### ISSUE TITLE
Yandex or Yandex.ru ruleset breaks Yandex search paging 

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#1373] opened 2015-04-06 20:12 UTC
Cross-posting from https://trac.torproject.org/projects/tor/ticket/15396.

>    With the "Yandex" (for HTTPS-E 5.0dev3) or "Yandex.ru" (for HTTPS-E 4.0.3) ruleset enabled (at least that's what shows up green in the menu),
>    search for something,
>    click "Следующая" ("Next"). 
> I am getting an error like "Не удалось получить результаты" or about a network error. Trying from the beginning does not work.

@2d1 can you take a look at this one?

**Comment by 2d1** [comment] 2015-04-07 07:36
@jsha I cannot reproduce, it's working perfectly for me.

**Comment by jsha** [comment] 2015-04-07 16:40
Thanks! Closing source ticket.

**Comment by J0WI** [comment] 2015-05-31 12:21
We can close this: https://trac.torproject.org/projects/tor/ticket/15396#comment:3

**Closed** 2015-12-17 20:57 UTC
Labels: ruleset-bug
