### ISSUE TITLE
Extension may have been corrupted

### ISSUE THREAD

**Issue by jmauss** [EFForg/https-everywhere#6696] opened 2016-09-01 13:15 UTC
I have seen the other threads here about the extension being corrupted, but none of the fixes posted have worked for me. After install, I still get an error saying "This extension may have been corrupted." I am on the most current stable release of Chrome on Windows 10 x64

**Comment by jeremyn** [comment] 2016-09-01 15:11
What fixes have you tried?

**Comment by jmauss** [comment] 2016-09-01 15:17
I have tried removing and reinstalling the addon, installing directly from the site, and modifying the flag (extension verification - enforce strict, enforce, and bootstrap) all with no luck.

**Comment by jmauss** [comment] 2016-09-01 19:41
I am able to get it to work just fine on my linux laptop and in my Firefox installation, just not my installation of chrome.

**Comment by tbyerly52102** [comment] 2016-09-01 19:42
Same here, tried uninstalling the extension, even tried uninstalling chrome itself and installing again, I still receive that error, other extensions install without a problem.

**Comment by jeremyn** [comment] 2016-09-01 19:58
I just uninstalled and re-installed HTTPS Everywhere in Chrome on Windows 10 and don't see the error.

Here is a URL that should work:

https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp?hl=en-US

Nothing secret, just what I found searching in the web store. Are you using that URL or something different?

**Comment by jeremyn** [comment] 2016-09-01 20:06
I also can install it without error from the link on https://www.eff.org/https-Everywhere , which is:

https://chrome.google.com/webstore/detail/gcbommkclmclpchllfjekcdonpmejbdp

That looks like it should be the same thing as the URL in my previous comment anyway.

**Comment by jmauss** [comment] 2016-09-01 20:18
Reinstallation of Chrome didn't fix this issue either. Using the links you provided also didn't work. No clue why this isn't working on windows for me.

**Comment by jeremyn** [comment] 2016-09-01 20:26
When did the problem start? After a Chrome update, OS update, extension update, etc?

**Comment by jmauss** [comment] 2016-09-01 20:28
Updated windows 10 to the most recent update (I think the anniversary build, but HTTPSE works on the home computer on the same build). Clean installed a few apps (including chrome) and ran into this.

**Comment by jeremyn** [comment] 2016-09-01 20:31
It might be interesting to know whether you have the same problem with HTTPS Everywhere and Chromium (not Chrome) on that computer, if you're willing to try it.

**Comment by jeremyn** [comment] 2016-09-01 20:32
Or you could try Chrome's bleeding edge version Canary.

**Comment by jeremyn** [comment] 2016-09-01 20:33
For what it's worth, my Chrome version ( chrome://help ) is `52.0.2743.116 m (64-bit)`.

**Comment by jmauss** [comment] 2016-09-01 20:35
I installed chromium on this machine and it works fine. I uninstalled chrome, but I do remember that it was version 53 that was installed (directly from their website). Did the update from 52 -> 53 break it? Although the chromium version I am using is 55.0.2842.0

**Comment by jmauss** [comment] 2016-09-01 20:38
I just reinstalled chrome from google's site and it is `53.0.2785.89 m (64-bit)` while chromium (where it works) is `55.0.2842.0 (64-bit)`

**Comment by jmauss** [comment] 2016-09-01 20:44
Looks as though 53 was released just yesterday. Tried on Chromium 53 and it works. Chrome 53 does not work.

**Comment by jeremyn** [comment] 2016-09-01 20:54
I'm getting the problem now too after upgrading to `53.0.2785.89 m (64-bit)`. After the update, the extension looked okay, but when I uninstalled and reinstalled it, I now get `This extension may have been corrupted.` in red text when I look at chrome://extensions/ .

@Hainish @jsha Can one of you take a look at this please? It looks like HTTPS Everywhere might be generally broken for some group of Windows users on the latest version of Chrome.

**Comment by jmauss** [comment] 2016-09-01 20:56
Thanks! Glad I am not the only one, I was starting to think I was going insane.

**Comment by Hainish** [comment] 2016-09-01 20:57
This should be fixed as of https://github.com/EFForg/https-everywhere/commit/d45ccb1b8874e43116c82382e727a3a6407ab49c, but we'll have to do a release to make sure the fix worked.  I'll try to make a release today.  If I'm not able to make a release, I'll have to hold off until Monday

**Comment by jeremyn** [comment] 2016-09-01 20:57
@Hainish Is this a duplicate of issue #5874?

**Comment by Hainish** [comment] 2016-09-01 20:58
@jeremyn it is, yes

**Comment by jeremyn** [comment] 2016-09-01 20:59
Thanks @Hainish .

@jmauss I'm going to close this issue and add a comment in #5874 . Please feel free to report problems with the fix etc in that issue going forward.

**Closed by jeremyn** 2016-09-01 20:59 UTC
Labels: chrome, High Priority
