### ISSUE TITLE
Icon changes count based on current active tab in all windows 

### ISSUE THREAD

**Issue by smarek** [EFForg/https-everywhere#12770] opened 2017-09-26 08:11 UTC
Hi, thanks for this extension, really great work!

I've found out, that having open two windows of Chrome (does not matter if those are same, or different - ie. incognito/standard), and changing focus between windows, changes count shown by the icon of https-everywhere extension in all windows to count for window currently in focus.

This does not happen with uBlock Origin extension, in same scenarios, so I don't think this is not-solvable issue.

Cheers!

**Comment by cschanaj** [comment] 2017-09-26 12:36
Duplicate of #12449, resolved in #12450 which is scheduled the in next release. thanks.

**Comment by jeremyn** [comment] 2017-09-26 15:37
Thanks for the report, but I'm closing this as a duplicate.

**Closed by jeremyn** 2017-09-26 15:37 UTC
