### ISSUE TITLE
Rules randomly not loading when visiting site immediately after browser startup

### ISSUE THREAD

**Issue by C4K3** [EFForg/https-everywhere#19513] opened 2020-08-23 03:24 UTC
Type: code issue

Hi.

There's a site I use ([webdiplomacy.net](webdiplomacy.net): [rule](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/WebDiplomacy.net.xml)) that has a working http and https version, but the http version does not redirect on its own to the https version. I noticed that sometimes while visiting this site, I would still be on the http version. When this happens, if I click the https everywhere plugin, it shows no rules for the site.

Through some testing, it appears that when I open my browser, if the first thing I do is go to webdiplomacy.net then the majority of the times it will not redirect me to https. If I wait a bit or first go to another site and then to webdiplomacy.net, it will correctly redirect to https (and list the rule when I click https everywhere.)

I am on linux, firefox 79.0 (64-bit). HTTPS everywhere Version: 2020.8.13. I am able to replicate this with a fresh profile with no changes except https everywhere installed, though I've noticed that on the fresh profile I have to be faster to go to webdiplomacy.net for it not to redirect than I do on my main profile.

The following screenshots were taken minutes apart from the same firefox profile, just by restarting the browser.
![a](https://user-images.githubusercontent.com/4582830/90970092-cc0de200-e4ef-11ea-88ca-abdec868fee5.jpg)
![b](https://user-images.githubusercontent.com/4582830/90970094-cf08d280-e4ef-11ea-888a-6156188aa711.jpg)

The same thing happens with [deb.li](http://deb.li) and I suspect any website that has an https everywhere rule but doesn't do https redirects on its own.

**Comment by zoracon** [comment] 2020-08-24 23:56
This seems to be a latency issue between first browser open and the rulesets loading.

**Comment by pipboy96** [comment] 2020-08-29 19:58
Duplicate of #17716.

**Closed** 2023-01-09 20:13 UTC
Labels: bug, duplicate
