### ISSUE TITLE
winxp firefox CPU / MEM hog and crash

### ISSUE THREAD

**Issue by gitrev** [EFForg/https-everywhere#1859] opened 2015-06-06 13:21 UTC
Hello,

Since some good versions ago (starting 4.x and 5.x) I can not seem to use the extension on latest firefox on winxp without crashes / total computer freeze due to CPU / MEM hogging when I visit certain https sites including https://www.eff.org/https-everywhere/development

I have a lot of extensions (and I mean A LOT) including TLS and HTTPS finder, adblock, noscript, etc, however the crashes started to appear since one of your extensions update and disappear after I disable it.

If further info is needed please ask.

Cheers.

**Comment by jsha** [comment] 2015-06-17 21:00
Duplicate of #1775. HTTPS Everywhere definitely consumes too much memory and CPU. We need to take some time to optimize it. Thanks for the report!

**Closed by jsha** 2015-06-17 21:00 UTC
