### ISSUE TITLE
Chrome v63 - extension flagged as corrupted

### ISSUE THREAD

**Issue by linepoint** [EFForg/https-everywhere#14278] opened 2018-01-12 17:22 UTC
Type: other

Upgraded Chrome from v62 to v63 on a Debian/Linux install and https-everywhere and privacy badger were both flagged as corrupted by Chrome.  (This issue/ticket is probably more of a info issue than anything, since it looks to be more of a chrome issue than eff one).

Delete + reinstall extensions, same thing.

Additional chrome issue that happened was it's inability to keep google account logins active between sessions (ie: had to delete profile each time before starting Chrome).

Finally tracked down a solution: run chrome with --password-store=basic, as chrome is probably having issues detecting a working OS based key storage systems correctly.  (Which can be dependent on windowing system in use)

**Comment by Hainish** [comment] 2018-01-12 17:55
Thanks for this report @linepoint.  We've encountered others reporting this, as well.  Looking into it currently.

**Comment by Hainish** [comment] 2018-01-12 18:39
Also reported [here](https://github.com/EFForg/https-everywhere/issues/7456#issuecomment-351634747).

**Comment by Hainish** [comment] 2018-01-12 19:08
I'm unable to reproduce this error using either: `Chrome 63.0.3239.132 (Official Build) (64-bit)` or `65.0.3315.3 (Official Build) dev (64-bit)` on Debian 8.

This corruption error comes up periodically for a few users, but most users are unaffected.  It seems like it's becoming a more frequent problem though.  This morning we received a separate report of this error, with `63.0.3239.132 (Official Build) (64-bit)` on Windows 7 Home.

I'm going to keep my eye on this and see if we can gather more details, and prepare a report for the Chromium bug tracker if this keeps coming up.

**Comment by linepoint** [comment] 2018-01-12 20:03
I think it's more of a installation/site specific issue, and not an extension issue.  (I'm on Chrome 63.0.3239.132 - Debian v9.3/xfce).  I filed this issue so the eff team and other users have something to check into since it generates an error for it.

Another telling error log (if running chrome from the commandline) is the following error which alludes to a dbus/interprocess communications error: "Gkr-Message: secret service operation failed: The name org.freedesktop.secrets was not provided by any .service files."

Feel free to close the issue if you'd like - I'm out of ideas at this point.  :-)

**Comment by pipboy96** [comment] 2019-03-28 17:40
Extremely old Chrome version, closing.

**Closed by pipboy96** 2019-03-28 17:40 UTC
Labels: chrome
