### ISSUE TITLE
Overhaul repo rule storage

### ISSUE THREAD

**Issue by semenko** [EFForg/https-everywhere#3999] opened 2016-01-25 18:45 UTC
Our ruleset storage is chaotic. Let's ponder overhauling it. (cc @fuglede)

**Comment by jsha** [comment] 2016-01-27 18:27
I agree! Do you mean storage in the repo, or the XML format, or the SQLite format, or ...? :-)

I was thinking recently that it's probably time to move the rulesets to a new repo that gets included into the main one. Submodules would be one way, but I would also like to have the property that if you check out latest https-everywhere and build, you get the latest rulesets, without needed to constantly update the submodule head in the code repo. If we do this, I think it makes sense to start the new repo as a fork of https-everywhere, deleting everything but the XML files, and moving the rulesets higher in the tree. That way we retain the commit history for the rulesets, which is important. We would also need to make sure that the ruleset tests get run in the ruleset repo in addition to the main repo.

It may also be time to split up the rulesets directory by first letter.

**Comment by semenko** [comment] 2016-01-27 18:46
I was pondering ... all of the above! But primarily the repo storage / XML format.

I think we should:
- Move away from XML
- Preserve separate files per-rule (so git merges don't become insane)
- Develop a simpler way for people add "trivial rule" sites
- Preserve a history of "broken" sites, rather than a complex git log

I've been pondering some YAML style rules, or perhaps simple, empty files for non-complex rules.

What if someone could ```touch somedomain.tld && git add somedomain.tld``` and have their rule added as a simple rule?

**Comment by jsha** [comment] 2016-01-28 04:32
> Move away from XML

I disagree on this one. I've thought about it a number of times, but I think there's nothing fundamental about the XML format that makes it unsuitable, and programmatically reformatting all our XML into YAML or JSON would lose all history. I am not a huge fan of XML, but it's not bad enough to kill.

That said, I'm totally into improving our build-time transforms of the XML to improve stored size, in-memory size, and speed of access.

> Develop a simpler way for people add "trivial rule" sites

Yes. Caveat: This will increase the total volume of submissions greatly. We need to do two things first: 1. Decide on a scope for ruleset inclusion in HTTPS Everywhere. Let's Encrypt has issued for ~450,000 unique domains. Even if we assume all those domains work perfectly, it's clearly not suitable to include them all in HTTPS Everywhere. It's just too much data.  2. Improve our fetch testing so that it runs at the time a PR is submitted, and checks for mixed content both on the root page of a domain and on a small set of pages crawled from the root.

> Preserve a history of "broken" sites, rather than a complex git log

I'm not sure what you mean here.

**Comment by semenko** [comment] 2016-01-28 04:36
>> Preserve a history of "broken" sites, rather than a complex git log

> I'm not sure what you mean here.

e.g. https://github.com/EFForg/https-everywhere/pull/3983 -- we sometimes `git rm` very broken rules. Since rule .xml names aren't always equal to the domain, the history can be hard to find.

**Comment by vgturtle127** [comment] 2016-02-24 01:59
@semenko @jsha Has any work been done on this? I was just curious. This seems cool.

**Comment by jsha** [comment] 2016-03-13 23:07
Only one small part of it: Now we ship the extension with a .json file containing XML rulesets, instead of a .sqlite file containing XML rulesets.

**Comment by vgturtle127** [comment] 2016-03-14 08:45
@jsha That is a step in the right direction, I would say. :smile:

**Comment by pipboy96** [comment] 2019-06-05 23:01
We already moved to JSON.

**Comment by J0WI** [comment] 2019-06-05 23:06
The issue is more about the format used in the repo where we still use XML.

**Comment by pipboy96** [comment] 2019-06-05 23:13
@J0WI we discussed it in https://github.com/EFForg/https-everywhere/issues/12620. Seems that we decided to not adopt it for now.

**Comment by J0WI** [comment] 2019-06-07 17:41
This issue discusses more points than just JSON/YML formats: https://github.com/EFForg/https-everywhere/issues/3999#issuecomment-175788780
I'd rather close #12620.

**Comment by pipboy96** [comment] 2019-06-07 17:53
@J0WI Should we restart this discussion?

**Comment by J0WI** [comment] 2019-06-10 21:11
This could be mentioned in #18069 but I'm currently not aware of any new input to solve this.

**Comment by pipboy96** [comment] 2019-06-11 00:22
@J0WI I also have not many ideas, but I am still thinking on how this may be done.

**Comment by zoracon** [comment] 2020-01-09 20:36
Closing for now, But tagging in #17268 to keep this in mind. And also, we now have a Rust library for fetching rulesets. Not quite the same topic of discussion, but it's related.

**Closed by zoracon** 2020-01-09 20:36 UTC
Labels: question
