### ISSUE TITLE
Whitelist HTTP

### ISSUE THREAD

**Issue by ttqghzar** [EFForg/https-everywhere#4795] opened 2016-05-14 23:44 UTC
Add option to allow HTTP on a per site basis similar to noscript when in "block all HTTP requests mode".

Alternatively, prompt the user to confirm if they want to access a site insecurely rather than the current behavior of showing an blank page.

This solves the problem of disabling the feature entirely (possibly making insecure connections to sites open in other tabs) when wanting to access an insecure page.

**Comment by fuglede** [comment] 2016-05-15 14:26
Very interesting idea, in my opinion; this could provide a different approach to #4370.

**Comment by Bisaloo** [comment] 2017-03-04 09:47
Duplicate of https://github.com/EFForg/https-everywhere/issues/2299

**Comment by jeremyn** [comment] 2017-07-29 15:54
@ttqghzar I'm closing this as a duplicate of issue https://github.com/EFForg/https-everywhere/issues/2299. Please feel free to comment on that issue if you want.

**Closed by jeremyn** 2017-07-29 15:54 UTC
