### ISSUE TITLE
Breaks foxnews.com

### ISSUE THREAD

**Issue by cooperq** [EFForg/https-everywhere#1629] opened 2015-05-04 20:09 UTC
I feel dirty even reporting this, but httpse breaks foxnews.com. Specifically images fail to load. Found while testing privacy badger (I swear I wasn't reading fox news).

**Comment by reedy** [comment] 2015-05-04 20:25
Lol.

**Comment by reedy** [comment] 2015-05-04 20:27
Seems to be WFM though in Chrome w/ 2015.4.23. Lot of noise in the console, but I see images

**Comment by cooperq** [comment] 2015-05-04 20:43
interesting, I am also running chrome w/2015.4.23 and it's definitely broken. Disabling the rule for foxnews fixes the problem.

**Comment by reedy** [comment] 2015-05-04 20:51
![screenshot 2015-05-04 at 16 49 41](https://cloud.githubusercontent.com/assets/67615/7462173/a6fffbde-f27d-11e4-83d8-4a88a12221f8.png)

Chrome OS 43

Noting that it's loading via HTTP, and if I manually add HTTPS

This server could not prove that it is www.foxnews.com; its security certificate is from a248.e.akamai.net. This may be caused by a misconfiguration or an attacker intercepting your connection.

**Comment by semenko** [comment] 2015-12-17 20:52
lulz... working for me.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.

**Closed by semenko** 2015-12-17 20:52 UTC
Labels: ruleset-bug
