### ISSUE TITLE
[firefox] no ruleset for wikipedia?

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#12456] opened 2017-09-04 16:41 UTC
Whenever I'm accessing Wikipedia via firefox there seems to be no https ruleset for it. 
Strangely enough, when I access Wikipedia via chrome, there IS a ruleset for it.

Is it normal?

**Comment by koops76** [comment] 2017-09-04 16:47
Preloaded I guess.

**Comment by Bisaloo** [comment] 2017-09-04 17:32
Can you provide a specific URL where we can reproduce this observation?

**Comment by koops76** [comment] 2017-09-04 17:48
https://hstspreload.com/api/v1/status/wikipedia.org

You have an obsolete version of HTTPS Everywhere installed on Firefox. Update please.

**Comment by jack2228** [comment] 2017-09-04 17:53
It happens pretty much on any wikipedia page. For the sake of the argument I will provide this one: 
https://en.wikipedia.org/wiki/Main_Page

My https everywhere is definitely up-to-date (I just uninstalled and installed the extension to be sure). It even has the '2017.8.31' date in the name.

For the record I have the latest firefox 55.0.3 version. I also use ublock origin if it makes any differance (on both firefox and chrome).

**Comment by Bisaloo** [comment] 2017-09-04 18:06
There is nothing that should trigger a ruleset on https://en.wikipedia.org/wiki/Main_Page. The issue is definitely on chrome side. Is HTTPS-Everywhere up-to-date on chrome?

**Comment by jack2228** [comment] 2017-09-04 18:15
The extension is up-to-date on chrome as well.

**Comment by Bisaloo** [comment] 2017-09-04 18:18
Can you tell me that name of the active ruleset?

As far as I can tell, only domains on https://en.wikipedia.org/wiki/Main_Page are `wikipedia.org` and `wikimedia.org`, neither of which has a ruleset.

**Comment by jack2228** [comment] 2017-09-04 18:53
The ruleset is simply called 'wikipedia' under the stable rules section.

**Comment by Bisaloo** [comment] 2017-09-04 19:32
That shouldn't happen. The only slightly related ruleset is `Wikimedia` but it shouldn't even be enabled.

Is that possible that you created this rule yourself? Do you see a tooltip saying `user rule` when you hover the ruleset name?

Other than that, I am clueless. Let's just wait for someone else that could have another idea of what's causing this.

**Comment by jack2228** [comment] 2017-09-04 20:39
You are right, it was a custom rule (created by my brother who uses chrome).
Sorry for wasting your time. Please close this issue.

**Closed** 2017-09-05 04:40 UTC
