### ISSUE TITLE
Opening the bottom "see more" menu reloads the page

### ISSUE THREAD

**Issue by j-james** [EFForg/https-everywhere#17892] opened 2019-05-04 08:58 UTC
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

~~This issue occurs at the "Settings for this site" See more menu. In between "See more" and the arrow "v", there's a little bit of white space. Clicking it reloads the current page.~~

~~Kinda strange bug! It doesn't happen on the EASE menu. This is an issue with the popup menu.~~

The reload error occurs on the whole menu dropdown text. The clickable space between is now its own separate bug at #17893.

Firefox Developer Edition 67.0b12, Manjaro 18.0.4 Illyria. I did disable extension verification earlier today as a temporary workaround for all extensions vanishing, but that likely had no impact on this

**Comment by Bisaloo** [comment] 2019-05-04 10:42
Thank you for your report! I'm going to close this as a duplicate of #17866. Please let me know if I got it wrong and this is actually a different issue.

**Closed by Bisaloo** 2019-05-04 10:42 UTC
