### ISSUE TITLE
Switch over from Github or at least give an alternative way to contribute to HTTPS-E

### ISSUE THREAD

**Issue by Giltyhub2** [EFForg/https-everywhere#18118] opened 2019-06-24 17:28 UTC
I don't think it will be possible for me to continue contributing to a project when I risk that my effort gets lost. For no reason I can no longer access my @Giltyhub account since I need to "confirm my identity" by receiving some code in my email whereas I had used a guerrillamail scrambled email address which means that I can't receive their confirmation code. As a result I can no longer maintain my other previous PRs. This isn't the first time Github screwed up badly, they did flag my account multiple times simply because I keep using Tor, and when I wanted to make this new account they stopped accepting throwaway mail services (guerrillamail and co) and they flagged my new account for 3 days. Note that gitlab isn't a good option either since they don't accept throwaway mails and you have to go through the impossible ReCAPTCHA.

**Comment by pipboy96** [comment] 2019-06-24 17:40
Sorry, but this is a duplicate of #15615. I do understand your concerns, but I have to close this. I will make sure to notify EFF about your situation.

**Closed by pipboy96** 2019-06-24 17:40 UTC

**Comment by pipboy96** [comment] 2019-06-24 17:42
@Giltyhub2 Do you want your old PRs be closed so you can re-create them from this account?

**Comment by Giltyhub2** [comment] 2019-06-24 18:04
> @Giltyhub2 Do you want your old PRs to be closed so you can re-create them from this account?

thanks @pipboy96 as usual, please if you can merge the ones that don't require any modification and keep a list of those that should be closed and post it here so that I can start recreating them and you can then close them

**Comment by pipboy96** [comment] 2019-06-24 18:53
@Giltyhub2 I can't merge anything, sorry! I do not have the requisite access.

**Comment by Giltyhub2** [comment] 2019-06-24 18:56
@pipboy96 ok i will make the list myself and then i will give you the signal to close everything

**Comment by Giltyhub2** [comment] 2019-06-24 21:04
@pipboy96 you can close them now

**Comment by Hainish** [comment] 2019-06-25 21:10
@Giltyhub2 thanks for raising this issue, sorry for all the troubles you've been having.  This is indeed concerning.  The developer community that Github gives us access to is indispensable for the project, but that doesn't mean that's the only way to contribute.  Please feel free to email patches directly to https-everywhere-owner@eff.org for now - I've also opened https://github.com/EFForg/https-everywhere/issues/18134 to address this in a more streamlined fashion.

**Comment by Hainish** [comment] 2019-06-25 21:12
If you email the patch to that address I'll open a GitHub PR from my account and email you back the PR #.

**Comment by Giltyhub2** [comment] 2019-06-25 22:50
thank you so much @Hainish  for taking my concerns seriously and into account. note that i'll continue making and maintaining my PRs with this new account.
