### ISSUE TITLE
Report of site not working 

### ISSUE THREAD

**Issue by Hotwheelz79** [EFForg/https-everywhere#4307] opened 2016-03-09 11:01 UTC
news.com.au  was workig fine but when using the following  version of the extenison it no longer does. Please fix this thanks. 

https://www.eff.org/files/https-everywhere-chrome-2016.2.23.crx .

**Comment by J0WI** [comment] 2016-05-11 10:59
dupe of #4561

**Closed by J0WI** 2016-05-11 10:59 UTC
Labels: ruleset-bug
