### ISSUE TITLE
UI/UX feedback for latest release

### ISSUE THREAD

**Issue by jadchaar** [EFForg/https-everywhere#17868] opened 2019-05-03 03:27 UTC
Big fan of the update that dropped today--really makes the menu more visually appealing.

Two things though that stood out to me and I thought I would mention:

1) When first navigating the menu, I thought the settings cog looked like a clickable icon since it was in-line with the toggle switches. I tried clicking it before realizing that it was just an icon. It may be better if it is placed somewhere else on the menu (like before the string "Settings for this site") so it is not mistaken for a button.

2) The new toolbar icon may be a bit misleading. I understand that you guys are going for a lock, but it looks a bit like a shopping bag now. Small issue, but I thought I'd mention it. I think the icon before was unique and very recognizable.

**Comment by Foorack** [comment] 2019-05-03 05:40
Yes, I was also confused where the modern logo "S" had gone. The shopping bag looks more like the Skype logo...

**Comment by Jon-guy30** [comment] 2019-05-03 05:56
I also want to add some initial experience with the new version.

When you click the "See more" below "Settings for this site" it refreshes the webpage! Could you make it not reset the page? It's very annoying on certain webpages, I just want to look at the rules, please. I would prefer that it would function like the old one, just click on the toolbar icon and it shows you all the information you need, there were no extra buttons before.

I also liked the old icon, you didn't have to change that. Another thing is that counters are missing in the new version, like in the icon itself. I do have it checked in the settings.

Great effort, but there are a few regressions.

**Comment by TheFinalCut83** [comment] 2019-05-03 13:21
Counter is gone, even when "Show counter" option is on. It's reproduceable in 3 browsers - Firefox 67b15, Waterfox 56.2.9 and Cent Browser 3.9.2.45.

**Comment by zoracon** [comment] 2019-05-03 17:35
@jadchaar Thanks for the feedback! I can see how the icon placement can be misleading.

@TheFinalCut83 
The Counter is now next to "stable rules". The "why" for shifting placement is that there was feedback that it was too small and the average user didn't get the context of the counter.

**Comment by TheFinalCut83** [comment] 2019-05-03 17:57
@zoracon 
So it means that "Show counter" option is unnecessary from now. In the previous version, user could see the number of stable rules directly on the icon, now you need to make extra clicks. That's disgusting.

**Comment by jadchaar** [comment] 2019-05-03 21:10
@zoracon I'd love to help contribute to help fix some of these UI/UX issues. Any task in need of contributors?

**Comment by zoracon** [comment] 2019-05-03 21:14
@jadchaar  I'm currently prioritizing some tasks for the community and will put up a task list soon. Thank you for volunteering!

**Comment by s-i-m-s** [comment] 2019-05-04 15:07
I also think it looks like a shopping bag and thought I had accidentally installed one of those spammy coupon extensions when I first saw it.

**Comment by Jon-guy30** [comment] 2019-05-07 11:29
I have an idea. Instead of having the stable rules counter on the icon itself, potentially making it hard to see, why not make it so it displays when you hover the mouse over the icon? It already says "HTTPS Everywhere" when you mouse over it.

**Comment by Giltyhub** [comment] 2019-05-12 09:36
@Jon-guy30 

> The new icon doesn't turn red when EASE mode is enabled, I think that functionality should return. That was a nice feature.

+1, the new icon used is highly ineffective in communicating the intent of EASE mode

**Comment by zoracon** [comment] 2019-05-13 22:01
@Giltyhub, @Jon-guy30 thank you for your feedback. In terms of the red for EASE. It was determined through UX research and even within this thread that "red" isn't a clear indicator of intent. We are still tweaking what the EASE icon should be but we are moving away from just colors as an indicator because it's not good for accessibility. Many thought "red" equated to disabled during our research, or something "bad". The added description text with EASE was added to clear up misunderstanding of what it does.

**Closed** 2023-01-09 20:15 UTC
Labels: ui
