### ISSUE TITLE
Redirect error with ublock origin

### ISSUE THREAD

**Issue by jordanelii** [EFForg/https-everywhere#15008] opened 2018-03-28 04:41 UTC
Type: other

I am getting this error from ublock origin: 
This extension failed to redirect a network request to chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/web_accessible_resources/f1df24e1f123b1137cec098dab038b34.javascript?secret=n4b83nqqryih because another extension (HTTPS Everywhere) redirected it to https://www.googletagservices.com/tag/js/gpt.js.
Saw the previous issue but mine is stemming from Ublock, not https everywhere. Also, I have no idea what I am looking at, hopefully someone can help me. Thanks.

**Comment by cschanaj** [comment] 2018-03-28 07:55
related #14961

**Comment by Bisaloo** [comment] 2018-03-28 09:31
Thank you for your report. This is actually the same issue as #14961.

See https://github.com/EFForg/https-everywhere/issues/14961#issuecomment-376127444 to understand why you have a slightly different message than other posters.

Closing as duplicate of #14961.

**Closed by Bisaloo** 2018-03-28 09:31 UTC
