### ISSUE TITLE
Hire more people as ruleset librarians and maintainers

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#13022] opened 2017-10-08 17:53 UTC
Right now the rate at which rulesets are written is higher than the rate at which rulesets are merged into master. There's only one person (whose username starts with a J) who does most of the work. I know that this is non-payed job but there are many people who follow, engage, contribute and make rulesets in this repository who can make good ruleset librarians and it may be a good idea to add somewhere that a ruleset librarian is needed to hire them.

Again to re-iterate there are many PRs that aren't merged and some can be critical such as those fixing some ruleset bugs, so there's this need to be up to date with incoming PRs.

**Comment by bardiharborow** [comment] 2017-10-09 03:31
Duplicate of #9111.

**Comment by koops76** [comment] 2017-10-09 19:55
@bardiharborow Not really.

**Comment by jeremyn** [comment] 2017-10-09 22:43
The specific issue "hire more ruleset maintainers" is covered by `CONTRIBUTING.md`. I closed an earlier issue about this with the comment https://github.com/EFForg/https-everywhere/issues/12448#issuecomment-326826981:

> Ruleset maintainers are unpaid volunteers. See the third paragraph of [`CONTRIBUTING.md`](https://github.com/EFForg/https-everywhere/blob/04b4e1df08543be683655c67652b8d337d61daf7/CONTRIBUTING.md) for information on becoming a ruleset maintainer.

I'm going to close this issue for the same reason.

However a more interesting question is how the EFF sees this project, that is, what priority they attach to it. If they wanted more people involved, they could make that happen somehow. Since more people aren't getting involved, HTTPS Everywhere must not be a big priority for them. If someone wants to create an issue about that, that wouldn't be a duplicate.

**Closed by jeremyn** 2017-10-09 22:43 UTC
