### ISSUE TITLE
Error "This extension may have been corrupted"

### ISSUE THREAD

**Issue by dmarkos** [EFForg/https-everywhere#7132] opened 2016-09-25 22:19 UTC
I am having this issue for a month now and fixing or removing and reinstalling doesn't help. 

Chrome stable 53.0.2785.116 (64-bit) on openSUSE Leap 42.1

EDIT:

On the same computer, chrome unstable (now 55.0.2868.3 dev) had the same problem but now is fixed.

**Comment by jeremyn** [comment] 2016-09-25 22:34
Thanks for the report, but I'm closing this as a duplicate of #5874 .

**Closed by jeremyn** 2016-09-25 22:34 UTC
