### ISSUE TITLE
Use WebExtensions for the Firefox addon as well

### ISSUE THREAD

**Issue by dralley** [EFForg/https-everywhere#8275] opened 2017-01-30 23:10 UTC
Firefox is transiioning to the WebExtensions API for addons going forward.  Support for addons based on XUL / XPCOM will most likely be removed in Firefox 57, which will be out before the end of the year.  Therefore, it would make sense to begin exploring how much effort would be involved in porting the Chrome addons to Firefox, or perhaps using the same codebase for both addons.

**Comment by jeremyn** [comment] 2017-01-31 00:01
Thanks for your comment, however this is a duplicate of the issue and discussion in https://github.com/EFForg/https-everywhere/issues/7389, so I'm closing this issue.

**Closed by jeremyn** 2017-01-31 00:01 UTC
