### ISSUE TITLE
Giant icon in address bar on Android

### ISSUE THREAD

**Issue by heftig** [EFForg/https-everywhere#6611] opened 2016-08-26 06:00 UTC
As of 5.2.3, issue #5719 still affects Firefox for Android, placing a giant icon into the address bar.

In addition, I have to question the wisdom of taking up valuable space for functionality that is seldomly accessed. There is no way to remove the icon, whose functions would be better placed behind the also existent menu item.

**Comment by fuglede** [comment] 2016-08-26 19:39
This looks like a duplicate of #6036.

**Comment by heftig** [comment] 2016-08-26 21:16
Well, in a recent release (5.2.1?) the icon doubled in size, so this is also acute.

**Comment by Hainish** [comment] 2016-08-27 04:17
@heftig https://github.com/EFForg/https-everywhere/issues/6617 will fix this issue, hiding ux controls in the menu rather than url bar

**Comment by Hainish** [comment] 2016-08-31 01:37
Fixed in https://github.com/EFForg/https-everywhere/pull/6617

**Closed by Hainish** 2016-08-31 01:37 UTC
