### ISSUE TITLE
Cloudfront ruleset breaks duolingo.cn

### ISSUE THREAD

**Issue by yfdyh000** [EFForg/https-everywhere#13255] opened 2017-10-20 20:07 UTC
Type: ruleset issue
Domain: duolingo.cn
The website blank if the Cloudfront ruleset enabled.
Similar to #102.
https://www.duolingo.com/ is redirected to http://www.duolingo.cn/ for Chinese users.
https://www.duolingo.cn/ is not available.

**Comment by Bisaloo** [comment] 2017-10-21 06:51
Thanks for your report! It's caused by https://github.com/EFForg/https-everywhere/issues/12579.

**Comment by pipboy96** [comment] 2019-10-04 14:28
Likely closed by #15157.

**Closed by pipboy96** 2019-10-04 14:28 UTC
Labels: top-100k
