### ISSUE TITLE
Toolbar button gone on Firefox/38.0 Iceweasel/38.4.0

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#3727] opened 2016-01-01 15:30 UTC
At some point recently, the HTTPS Everywhere toolbar button disappeared from the latest Debian stable version of Firefox, Firefox/38.0 Iceweasel/38.4.0.

Tested on two systems; on both systems, the button reappears if one uses the same profile settings on the most recent version of Firefox from Mozilla.

**Comment by fuglede** [comment] 2016-01-30 11:28
For what it's worth, I also just tested this on the current Tor Browser Bundle release, based also on Firefox/38.0, and there the toolbar button works as intended.

**Comment by jsha** [comment] 2016-01-30 23:55
I can't reproduce this on Debian 8.3 / Iceweasel 38.6.0, through `./test/firefox.sh --justrun`

**Comment by fuglede** [comment] 2016-01-31 09:22
I'm still seeing the issue with <code>justrun</code> on Iceweasel 38.6.0 and the current master branch:

![skaermbillede fra 2016-01-31 10 18 45](https://cloud.githubusercontent.com/assets/6169306/12701258/15ef610e-c804-11e5-99b9-594476add5d5.png)
![skaermbillede fra 2016-01-31 10 18 48](https://cloud.githubusercontent.com/assets/6169306/12701257/15ea5812-c804-11e5-8b49-063e8b21ca6b.png)

That's pretty weird; any ideas for what the difference in our setups could be? How is #2801 behaving in your setup?

**Comment by HTTPSNowhere** [comment] 2017-07-16 11:58
This seems to no longer be an issue with current versions of Firefox, @J0WI can you please close this issue? Thanks!

**Closed** 2017-07-17 21:19 UTC
Labels: firefox
