### ISSUE TITLE
click.e.twitter.com does not support HTTPS

### ISSUE THREAD

**Issue by lfaraone** [EFForg/https-everywhere#7415] opened 2016-10-22 22:09 UTC
A URL from some Twitter emails goes through the domain `click.e.twitter.com`. This is behind Akamai, and does not have a valid cert. 

However, the ruleset for Twitter doesn't have this exclusion.

**Comment by jeremyn** [comment] 2016-10-24 22:06
Thanks for the report. This is a duplicate of https://github.com/EFForg/https-everywhere/issues/7137 , however since there is a PR associated with this issue I won't close it. Please see that issue for related discussion.

**Closed** 2016-10-24 22:50 UTC
