### ISSUE TITLE
Option to Disable Onboarding

### ISSUE THREAD

**Issue by john7200** [EFForg/https-everywhere#19210] opened 2020-04-30 06:37 UTC
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: feature request

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

HTTPS Everywhere used to be discreet with update. Now it advertises the update/changelog. This is the only add-on/extension in my browser that opens new tab and access new link/page/site without user's permission. And it comes from the add-on/extension (onboarding), which makes it impossible to block. A user **should and must be able** to choose or decide whether they want to view or read the changelog.

Edit: I changed the title to point directly to the specific issue/cause.

**Comment by pipboy96** [comment] 2020-04-30 09:01
This is a duplicate of #19030. Please read https://github.com/EFForg/https-everywhere/issues/19030#issuecomment-606012621 for explanation why we can't make a release fixing this right now.

**Closed by pipboy96** 2020-04-30 09:01 UTC
Labels: duplicate
