### ISSUE TITLE
Is there now way to view/edit/manage all rules?

### ISSUE THREAD

**Issue by mzso** [EFForg/https-everywhere#4938] opened 2016-05-27 13:44 UTC
Hi!

I wanted to disable some rules for testing, because google/youtube pages ar hanging.
A bunch of them appeared for a spammy google on-click url that redirects. But I couldn't disable them. Because HTTPS-E reloads as soon as I disable one. And it loaded an empty page.
And now it looks like the rule manager is gone. There used to be a window where I could disable any rule. But now there's only a menuitem that redirects to this useless url: https://www.eff.org/https-everywhere/atlas/

**Comment by rugk** [comment] 2016-05-28 10:44
See https://github.com/EFForg/https-everywhere/issues/2258 for previous discussion on this topic.

**Comment by J0WI** [comment] 2016-06-01 22:19
I would say that this is a dupe of #2258.
As a workaround you can type `about:config` on the url bar (Firefox only) and set a bool for `extensions.https_everywhere.rule_toggle.[rulename]`.

**Closed by J0WI** 2016-06-01 22:19 UTC
Labels: duplicate

**Comment by rugk** [comment] 2016-06-02 21:03
@J0WI Wow, interesting. I think this is exactly the answer the OP has searched for.

**Comment by mzso** [comment] 2016-06-04 17:42
[**@rugk**](https://github.com/rugk) commented on [2016. jún. 2. 23:03 CEST](https://github.com/EFForg/https-everywhere/issues/4938#issuecomment-223421717 "2016-06-02T21:03:28Z - Replied by Github Reply Comments"):
> [@J0WI](https://github.com/J0WI) Wow, interesting. I think this is exactly the answer the OP has searched for.

Not really. You can't search or manage rules here. You need to find the rules and create about config entries for them to disable them. And that's all that you can do.

**Comment by rugk** [comment] 2016-06-04 17:48
Yes, but it's better than nothing and it should work for his problematic situation with hanging youtube videos.
