### ISSUE TITLE
Google Video ruleset breaks some parts of Google Image Search

### ISSUE THREAD

**Issue by ZongMan** [EFForg/https-everywhere#1494] opened 2015-04-16 05:45 UTC
![firefox_screenshott](https://cloud.githubusercontent.com/assets/11972834/7174794/ccfa9e18-e3c1-11e4-8ce8-43088900fe7e.png)

Google image search and right clicking images to open in new tab not working shoots me to a 404 page with errors

heres a screen shot , works when a disable the extension though

EDIT; the fix
"!Unchecking Google video in HTTPS-Everywhere fixes this little problem!"

**Comment by reedy** [comment] 2015-04-16 16:43
Where was the image actually located? e.g. what url was it supposed to load, to end up with that one?

**Comment by ZongMan** [comment] 2015-04-16 19:27
no its all and i emphasize all images locations that return this error, well what i do is take any image you have on your comp then go google image drag and drop this image into the searh bar wait for it to load click the tab then pick any image square right click it and open in new tab. Thats when i get the error404. happens to all images locations always with the right click open in new tab option.
It doesn't matter where the image url is directed to happen anyways.

**Comment by ZongMan** [comment] 2015-04-16 19:30
reall in any instance you could just type the letter D and image search then right click the first image and open in new tab; same thing goolge 404 error page hope that clarify what i just said even more

**Comment by reedy** [comment] 2015-04-16 22:07
WFM fine on Google UK, Chrome 42, HTTPSE 2015.4.7 with all Google rules enabled

**Comment by reedy** [comment] 2015-04-16 22:14
Seems to be a dupe of #1449 ?

**Comment by mopquill** [comment] 2015-04-17 20:04
I've had this going on for a while, and had been too busy to try figuring it out. It took me some research to even figure out that this was HTTPS Everywhere causing this. Disabling HTTPS for Google Video fixes this issue for me: http://mpql.net/i/p/ss/2015-04-17_t9pQF.png

**Comment by ZongMan** [comment] 2015-04-17 20:21
Well im using firefox 36.0.0.1 and haven't had a issue until upgraded this extension to the latest update so something broke not sure what or a check mark happened somewhere that i need to uncheck even though i tried all that.
Its a annoying problem especially  when your trying to do image work and searches quick this hinders that immensely.

**Comment by mopquill** [comment] 2015-04-17 20:23
It's happening for me on Chrome 42.0.2311.90 m.

**Comment by ZongMan** [comment] 2015-04-17 20:25
i did what you said and unchecked google video and it works fine now

**Comment by synthetichuman** [comment] 2015-04-17 23:02
Wish I had checked here weeks ago. I've been having the same issue and only came here to report the problem and the fix I just figured out. But the "unchecking google videos" workaround is already here.

**Comment by reedy** [comment] 2015-04-18 22:43
In which case, the Google Video ruleset disabling and/or fixing

**Comment by notfoss** [comment] 2015-04-19 03:19
I can confirm that disabling the Google Video ruleset fixes this problem.

**Comment by jsha** [comment] 2015-04-23 19:28
Duplicate of https://github.com/EFForg/https-everywhere/issues/1096

**Closed** 2015-04-23 19:28 UTC
Labels: ruleset-bug
