### ISSUE TITLE
Https Everywhere breaks pbs.org videos

### ISSUE THREAD

**Issue by random6969** [EFForg/https-everywhere#4017] opened 2016-01-28 04:28 UTC
example vid: http://www.pbs.org/wgbh/frontline/film/vaccines/

Seems to be an issue with the "Cloudfront" rule. Disabling it from the extension drop down menu allows the videos to play as expected. I've noticed this isn't an issue on Firefox, but it is on chrome. 

- running Chrome v48 64-bit, Win10 64-bit.

**Comment by semenko** [comment] 2016-01-28 22:35
Duplicate of #1508 -- will try to fix before next release

**Closed by semenko** 2016-01-28 22:35 UTC
