### ISSUE TITLE
Transparent youtube player controls hidden.

### ISSUE THREAD

**Issue by tomlut** [EFForg/https-everywhere#2429] opened 2015-08-05 00:45 UTC
Enabling HTTPS everywhere in FF 39.0 stops the video controls appearing on youtubes new transparent player, see: https://i.imgur.com/O66vT2h.png

**Comment by Deadmoo5e** [comment] 2015-10-06 19:47
Hey, two months passed and it's still not fixed. Come on guys.

**Comment by semenko** [comment] 2015-12-17 20:31
Do you still see this bug? Can you please share a link where you see it?

**Comment by semenko** [comment] 2016-01-20 02:43
Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if this is still a bug.

**Comment by blerner** [comment] 2016-01-21 02:27
http://arstechnica.com/science/2016/01/scientist-who-killed-pluto-now-concludes-there-is-a-ninth-major-planet/ currently triggers this bug with HTTPS Everywhere 5.1.0.  VERY bizarrely, if I disable the extension and restart Firefox, then re-enable the extension and restart Firefox, the Youtube player controls appear again.  But, if I then refresh the ArsTechnica page (without doing anything else at all), the controls disappear.

**Comment by blerner** [comment] 2016-01-21 02:47
Some more information for you, since this doesn't appear to be a 100% reliable reproduction scenario: I'm on Fx43.04, on Win7, using v5.1.0 of HTTPS Everywhere.  I've got a bunch of other extensions installed (NoScript, AdBlock, etc.), but toggling HTTPS Everywhere was enough to bring back and then remove the Youtube controls, so it appears to be this extension.  Am happy to try a beta version to test if it's fixed, but I have limited ability to massively tinker with my Firefox profile as it's my main workday machine and I don't want to destabilize it.

**Comment by ememoho** [comment] 2016-02-21 15:04
Appears to be caused by https://bugzil.la/1247733 (and https://bugzil.la/1244495 has more YouTube specifics).
I was able to get a 100% reliable scenario using a video embedded with a HTTP URI iframe.

This problem does not happen if the [YouTube rulesets](https://www.eff.org/https-everywhere/atlas/domains/youtube.com.html) are disabled in HTTPS Everywhere, and something like https://github.com/einaregilsson/Redirector is used instead, as it replaces the HTTP address without invoking the HSTS/upgrade-insecure-requests mechanism.

**Comment by HTTPSNowhere** [comment] 2017-07-16 11:53
https://bugzil.la/1247733 and https://bugzil.la/1244495 have been fixed, and this issue no longer appears with latest Firefox versions (esr, stable and nightly), @J0WI can you close this issue? Thanks.

**Closed** 2017-07-17 21:21 UTC
Labels: ruleset-bug
