### ISSUE TITLE
Notify user if "Block all unencrypted requests" ticked and no HTTPS version of domain exists

### ISSUE THREAD

**Issue by kwill** [EFForg/https-everywhere#16046] opened 2018-07-09 09:05 UTC
Type: feature request

**User story:** I am an everyday user with "Block all unencrypted requests" ticked. I want to be notified when a domain has no HTTPS available, so I understand why it isn't loading.

**Steps to reproduce:**

* Start browser with HTTPS Everywhere installed and "Block all unencrypted requests" ticked
* Enter a domain in the address bar (where the domain is HTTP-only, no HTTPS version is available)
* An example at the time of writing is http://wikiba.se

**What should happen:**

* Notification that no HTTPS version is available

**What happens instead:**

* After a very long time, browser reports that "The connection has timed out"
* It appears as though the website is down, rather than it is up but not available over HTTPS

**Suggested solution:**

* Display a simple message in the content window, similar to a browser message (not a pop-up or dialog box): "www.example.com is not accessible over HTTPS"

**Comment by Bisaloo** [comment] 2018-07-09 10:38
Thank you for your report! I'm closing this as duplicate of #8239. Please let me know if you think this issue differs significantly from #8239.

**Closed by Bisaloo** 2018-07-09 10:38 UTC
