### ISSUE TITLE
[Feature Request] Support Upgrade-Insecure-Requests Headers

### ISSUE THREAD

**Issue by zero77** [EFForg/https-everywhere#12774] opened 2017-09-26 14:07 UTC
Can you please add support for the upgrade insecure requests header for all content on web sites regardless of the domain and type, i.e. iframes, images, fonts and java script.

Thanks

w3.org/TR/upgrade-insecure-requests

**Comment by Bisaloo** [comment] 2017-09-26 14:48
Duplicate of https://github.com/EFForg/https-everywhere/issues/3343 and https://github.com/EFForg/https-everywhere/issues/8506.

**Comment by jeremyn** [comment] 2017-09-26 15:36
Thanks for the report, but I'm closing this as a duplicate.

**Closed by jeremyn** 2017-09-26 15:36 UTC
