### ISSUE TITLE
HTTPS Everywhere 09.21.2016 This extension may have been corrupted.

### ISSUE THREAD

**Issue by strykenKN** [EFForg/https-everywhere#7149] opened 2016-09-28 11:00 UTC
slowly sucks it with you!

- HTTPS Everywhere 09.21.2016
This extension may have been corrupted.

finally gets the problem fixed!

Google Chrome: 53 (x64)

**Comment by jeremyn** [comment] 2016-09-28 14:38
Thanks for the report, but I'm closing this issue as a duplicate of issue #5874 .

**Closed by jeremyn** 2016-09-28 14:38 UTC
