### ISSUE TITLE
Chrome Version 55.0.2883.75 (64-bit) will not run HTTPS Everywhere extension

### ISSUE THREAD

**Issue by ASleepingZeep** [EFForg/https-everywhere#7819] opened 2016-12-08 23:23 UTC
The extension shows up as 'may have been corrupted' and I cannot get it to work in Chrome Version 55.0.2883.75 (64-bit). Have tried removing and re-installing with no luck. Also tried repair.

![chrome version](https://cloud.githubusercontent.com/assets/24465187/21031759/08dd803a-bd5a-11e6-88b7-fc978324408c.png)

![repair](https://cloud.githubusercontent.com/assets/24465187/21031761/0a1dd012-bd5a-11e6-869d-ec84f16ce387.png)

![https everywhere corrupt](https://cloud.githubusercontent.com/assets/24465187/21031789/313ab336-bd5a-11e6-9a81-b929994bc93e.png)

**Comment by jeremyn** [comment] 2016-12-09 00:16
Thanks for the report, however this is a duplicate of issue #7456, so I'm closing this issue.

**Closed by jeremyn** 2016-12-09 00:16 UTC
