### ISSUE TITLE
HTTPS not supported error

### ISSUE THREAD

**Issue by jaydeflix** [EFForg/https-everywhere#14154] opened 2018-01-01 00:16 UTC
Type: feature request

I'd like to have an option to get the same sort of error I'd get if I simply typed https://<problem domain> into the address bar. 

Example: If (until it is fixed) I disable https everywhere and I type https://expatriatepdx.com, I get "Your connection is not secure

The owner of expatriatepdx.com has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website."

I would like to get some sort of message if https everywhere is enabled that some problem was encountered. As it is now, I don't even get a padlock with an exclamation point and am left with the site unusable. 

I've also seen this on other websites, where hosted photos wouldn't load with no evidence it was the extension that ended up blocking it.

**Comment by jeremyn** [comment] 2018-01-02 16:33
@jaydeflix Thanks for your issue. If I understand you correctly, you want some kind of indication that HTTPS Everywhere is responsible for breakage when it rewrites a request to HTTPS for a URL that doesn't work with HTTPS. This is both technically and "philosophically" challenging. Some of the problems have been discussed in issue https://github.com/EFForg/https-everywhere/issues/8239. Please take a look there and make a comment there if you like. I'm closing this issue as a duplicate of that one.

**Closed by jeremyn** 2018-01-02 16:33 UTC
