### ISSUE TITLE
Regularly check CDN rewrites

### ISSUE THREAD

**Issue by numismatika** [EFForg/https-everywhere#6624] opened 2016-08-27 10:25 UTC
There are a lot of rules that rewrite their hosts to a cdn.
Be it akamai, amazon webservices, cloudfront, cloudflare or llnwd.
Pages and CDNs are slowly rolling out proper certificates for the real hostname.
Going through all rules manually and check if the rule can be fixed is a long and annoying task.
Could someone maybe write a script for that?

**Comment by jeremyn** [comment] 2016-09-14 00:01
Can you please give an example of one CDN entry that should be updated, to show what you mean?

**Comment by numismatika** [comment] 2016-09-14 18:50
9gag rewrites images-cdn.9gag.com to https://d24w6bsrhbeh9d.cloudfront.net/ although there is a valid cert for *.9gag.com in use on the original domain.


```
<rule from="^http://cdn1\.360cities\.net/"
to="https://d2dw0c606n9zn3.cloudfront.net/" />
<rule from="^http://cdn2\.360cities\.net/"
to="https://d3tllcxe89i3i3.cloudfront.net/" />
```
as well. Both hosts use a certificate that is valid for *.360cities.net. No need for cloudfront in the rewrites here.

**Comment by jeremyn** [comment] 2016-09-14 20:12
Oh I see, thanks. Yes, it would definitely be nice to reduce CDN rewrites.

**Comment by pipboy96** [comment] 2019-08-11 19:04
Duplicate of #2709, being worked on by @cschanaj.

**Closed by pipboy96** 2019-08-11 19:04 UTC
