### ISSUE TITLE
Make new ruleset for new New York Times Onion Service https://www.nytimes3xbfgragh.onion/

### ISSUE THREAD

**Issue by ghost** [EFForg/https-everywhere#13366] opened 2017-10-27 13:58 UTC
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: new ruleset

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: nytimes3xbfgragh.onion

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

-------

URL: https://www.nytimes3xbfgragh.onion/

You can check that it's legit from the EV certificate that is in use.

**Comment by Hainish** [comment] 2017-10-31 19:44
Great, thanks.  No `www` though.

**Comment by libBletchley** [comment] 2017-11-11 10:42
It's not working on ungoogled-chromium.  That is, when I go to nytimes.com, the host is not replaced with nytimes3xbfgragh.onion.

Or is the rule to switch from HTTP to HTTPS?  If so, that makes no sense.  Onion sites do not need SSL because e2e crypto is inherent in Tor `.onion` connections.

**Comment by ihave100openPRs** [comment] 2017-11-11 22:50
@libBletchley It already self-redirects to HTTPS.

(Also ungoogled-chromium most probably leaks the DNS request for that onion when you visit it)

**Comment by libBletchley** [comment] 2017-11-12 09:31
> It already self-redirects to HTTPS.

In that case there's no reason at all to even have this rule.

> (Also ungoogled-chromium most probably leaks the DNS request for that onion when you visit it)

Onion sites _can't_ be leaked; they must be resolved via tor.  I think you're trying to say that the clearweb domain is leaked.  But that wouldn't be correct either, because the Chromium leaks apply to non-HTTP(S) URLs, like ftp://.

**Comment by ihave100openPRs** [comment] 2017-11-12 11:13
@libBletchley 

> In that case there's no reason at all to even have this rule.

It saves some time I guess. There may be additional benefits to it that I'm not aware of.

> Onion sites can't be leaked; they must be resolved via tor.

That doesn't mean that browsers that don't respect RFC7686 won't do DNS requests to them: https://bugs.chromium.org/p/chromium/issues/detail?id=562265

**Comment by Hainish** [comment] 2017-11-13 21:59
@ihave100openPRs @libBletchley 

>> In that case there's no reason at all to even have this rule.

> It saves some time I guess. There may be additional benefits to it that I'm not aware of.

Typically, including rules which auto-redirect to HTTPS serves as a mitigation against an [ssltrip](https://moxie.org/software/sslstrip/)-style attack, where a MITM can interrupt the initial redirect and force a downgrade of the connection.

This attack scenario is altered by the fact that the original .onion address is not so easily MITM-able, due to the cryptographic guarantees of onion services.  However, it is still the case that traditional onion services provide only 80 bits of entropy in the address, less than is adequate for TLS.  As we already include other services, such as `facebookcorewwwi.onion`, which auto-redirect, it would be in keeping with pre-established precedents to include this onion service in the rulesets as well.

**Comment by pipboy96** [comment] 2019-03-30 15:38
It seems the issue is about redirecting from clearnet to onion, which is not the scope of this extension. Closing.

**Closed by pipboy96** 2019-03-30 15:38 UTC
Labels: new-ruleset
