### ISSUE TITLE
"Allow access to file URLs"

### ISSUE THREAD

**Issue by corobin** [EFForg/https-everywhere#6794] opened 2016-09-07 05:28 UTC
Hello,

I'm a little confused about this checkbox, and Google hasn't  turned up the answer.

What's it for?

Since the checkbox only shows up if an extension requests it, HTTPS-Everywhere must have some part that touches file:// URLs, but since it's an HTTPS redirect extension I can't think of a reason why it would need to.

What is the purpose of requesting file URL access? Should I check that box?

Thanks!

**Comment by jeremyn** [comment] 2016-09-13 23:34
I can't think of any reason why HTTPS Everywhere needs to check file URLs, so I wouldn't check it.

I don't know much about Chrome extension development. Do you mean that the extension itself has a flag somewhere in it saying "Allow user to opt into allowing file URLs"?

**Comment by semenko** [comment] 2016-09-17 20:42
Hm, this is a good question -- we request `<all_urls>` in manifest.json:
https://github.com/EFForg/https-everywhere/blob/master/chromium/manifest.json#L45

I'm not sure we need to intercept file:///, so we could just specify `http://*/*` and `https://*/*`

That said, I vaguely recall chrome just ignoring the `file:///` permission anyway -- I'll take a look.

**Comment by advaith1** [comment] 2017-03-29 00:42
@jeremyn: It is a checkbox on the Extensions page.

**Comment by jeremyn** [comment] 2017-03-29 15:13
@advaith1 Thanks, I see it now.

**Comment by pipboy96** [comment] 2019-03-28 20:20
Can't reproduce, but can verify that the checkbox used to exist. Closing.

**Closed by pipboy96** 2019-03-28 20:20 UTC
Labels: chrome
