### ISSUE TITLE
radiotimes.com mistakes HTTPS Everywhere for an ad-blocker

### ISSUE THREAD

**Issue by HarryCutts** [EFForg/https-everywhere#14879] opened 2018-03-10 05:02 UTC
Type: other
Domain: radiotimes.com

Going to a Radio Times article ([like this one](http://www.radiotimes.com/news/tv/2018-03-09/his-dark-materials-bbc-cast-director-lyra-revealed/)) with HTTPS Everywhere enabled brings up a prompt asking you to turn off your ad-blocker ([screenshot](https://screenshots.firefox.com/AcIfua4RutPyEi9O/www.radiotimes.com)). (All the more annoyingly, it only appears after the page has fully loaded, which may take a while.) Turning off HTTPS Everywhere altogether and reloading makes it go away.

**Comment by Bisaloo** [comment] 2018-03-10 08:09
Thank you for your report!

This sounds similar to #14835. I hope we are not going to see a surge of broken sites because of anti-adblocking strategies.

I could not reproduce your issue at first and I had to disable uBlock to get the result in your screenshot so I am assuming this is fixed by using the `UblockAssets` filter in you adblocker (according to https://github.com/EFForg/https-everywhere/issues/14835#issuecomment-369910279).

In the meantime, I will try to see if that's something we can fix on our side for users that don't / don't want to use an adblocker.

**Comment by numismatika** [comment] 2018-03-12 13:05
@Bisaloo it is not good if we have to add more and more exclusion to fastly for every site that uses this adblock detection solution. (Still wonder who produced it).
Is that a fastly issue or a HTTPS-Everywhere problem that causes CORS?

**Comment by Bisaloo** [comment] 2018-03-12 13:11
@numismatika, I'm not sure what you mean.

Anyways, we now have a solution to fix all CORS issues (https://github.com/EFForg/https-everywhere/issues/49#issuecomment-357693254) and stop adding exclusions but we need to implement it.

**Comment by jeremyn** [comment] 2018-03-15 14:08
I can't reproduce the original problem -- getting a "turn off your adblocker" prompt at http://www.radiotimes.com/news/tv/2018-03-09/his-dark-materials-bbc-cast-director-lyra-revealed/ -- in a Firefox profile with HTTPS Everywhere, no uBlock Origin, with the `Fastly.net (partial)` ruleset active. Is this still an issue?

**Comment by HarryCutts** [comment] 2018-03-15 20:22
I just tried again on a different computer (with Firefox ESR (52.6.0) on Debian), and I didn't get the prompt, even though both HTTPS Everywhere and Privacy Badger were enabled, so maybe they've just removed that prompt.

**Comment by Bisaloo** [comment] 2018-03-19 12:54
I can't reproduce anymore either. It looks like they fixed it on their side.

**Closed by Bisaloo** 2018-03-19 12:54 UTC
Labels: top-10k
