### ISSUE TITLE
split https-everywhere to repo with rulesets and repo with code

### ISSUE THREAD

**Issue by klensy** [EFForg/https-everywhere#9104] opened 2017-03-16 13:46 UTC
One repo with code, one repo with rules (repo with rules connected as git submodule, for example).

Why?

99% (not checked) commits in this repo is ruleset change:

**Pros**:

1. Ruleset repo: separate repo with separate access rights, maintainers should check rules, no https-everywhere source code 
2. Source code repo: the same - separate access rights, maintainers only change source code
3. Source code repo: ruleset commits don't mess with source code history, so reviewing code will be much easier
4. Ruleset repo: possible to create issue template for submitting rulesets (like [this](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)). Sure, creating template now also possible.

**Cons**:

1. After splitting repo, need changes in build process
2. First time after split: people will create issues in https-everywhere, so they should be redirected from https-everywhere to https-everywhere-rules(or better name)
3. First time after split: somehow move issues\pull requests to new repo

something related https://github.com/EFForg/https-everywhere/issues/3999

upd.
and this https://github.com/EFForg/https-everywhere/issues/2697

**Comment by Bisaloo** [comment] 2017-03-16 14:03
duplicate of https://github.com/EFForg/https-everywhere/issues/2697

**Comment by klensy** [comment] 2017-03-16 14:05
I'm checked search, i swear )

**Comment by Hainish** [comment] 2017-03-16 20:26
Feel free to add to #2697, closing this issue

**Closed by Hainish** 2017-03-16 20:26 UTC
