### ISSUE TITLE
Unable to access internal SAS company resources while this Chrome extension is enabled

### ISSUE THREAD

**Issue by Pysis868** [EFForg/https-everywhere#4910] opened 2016-05-25 14:11 UTC
This extension has been interfering with our access to internal company resources.  I am unable to say whether this worked before and I suddenly encountered the problem 'one day', or if after a Chrome profile sync, I finally received this extension and it would have always failed earlier if installed then.

Namely, I experience an error when navigating to any internal resource web page, which redirects me to the login screen.  Once logging in, I receive this error:

https://swwopenam.sas.com/opensso/UI/Login?realm=/sww&goto=http%3A%2F%2Fsww.sas.com%2F net::ERR_TOO_MANY_REDIRECTS

It is possible something should be done to this authentication service URL in the extension by modifying the [`SAS_Institute.xml`](https://www.eff.org/https-everywhere/atlas/domains/sas.com.html) ruleset file.

I have also received other problems, such as accessing the internal wiki, encountering that same redirect error, but eventually landing on the correct page, and having the stylesheets not load.  I have not singled out the cause of the problem yet, but it would be the result of not loading or running a script correctly that would make the proper stylesheet requests.  It runs MediaWiki.

**Comment by jeremyn** [comment] 2016-09-06 00:05
Thanks for the report. Is there a way to reproduce this problem using a public URL?

**Comment by pipboy96** [comment] 2019-04-05 13:47
Can't reproduce using the URL in the issue. No extension maintainer had account for SAS intranet. Issue opened in 2016. Closing.

**Closed by pipboy96** 2019-04-05 13:47 UTC
Labels: ruleset-bug
