### ISSUE TITLE
Firefox dev tools tab off option not sticking

### ISSUE THREAD

**Issue by Hlsgs** [EFForg/https-everywhere#13685] opened 2017-11-21 01:50 UTC
Type: other

As per title. It reverts to checked after closing and reopening the dev tools.

Related: Any way to disable the dev tools tab in Chrome?

**Comment by jeremyn** [comment] 2017-11-21 13:57
@Hlsgs Thanks for your report, however I'm closing this as a duplicate of issue https://github.com/EFForg/https-everywhere/issues/13611.

I'm not sure if there is a way to disable any dev tool tab in Chrome.

**Closed by jeremyn** 2017-11-21 13:57 UTC
