### ISSUE TITLE
Cannot download anything from NexusMods.com while on HTTPS

### ISSUE THREAD

**Issue by BeneathThePlass** [EFForg/https-everywhere#11970] opened 2017-08-18 01:07 UTC
This just started happening withing the last couple days; anytime I try to download anything from www.nexusmods.com, I receive an error message. This has been verified on three computers; my laptop, my desktop, and my wife's desktop, with both Windows 10 and Windows 7.

![http everywhere nexusmods error](https://user-images.githubusercontent.com/31116667/29440029-bba4dd98-838f-11e7-8eac-9eba75c1486c.png)

**Comment by koops76** [comment] 2017-08-18 15:18
Duplicate of #11953, already fixed, please close.

**Comment by jeremyn** [comment] 2017-08-19 02:36
Closing as duplicate of #11953 .

**Closed by jeremyn** 2017-08-19 02:36 UTC
