### ISSUE TITLE
Compatibility issue with Smile Always plugin in Chrome. Request option feature for URL ignore whitelist.

### ISSUE THREAD

**Issue by tastyratz** [EFForg/https-everywhere#7666] opened 2016-11-22 13:41 UTC
Hello,
I wanted to report an issue with the smile always plugin in chrome.
http://www.smilealways.io/

It seems they both fight for attention and chrome tells me I have extension errors. Unfortunately, I don't see an options field to tell https-e to ignore specific sites and avoid the conflict.

This is what shows on the extension page when I go to amazon:

HTTPS Everywhere 2016.11.8
Encrypt the Web! Automatically use HTTPS security on many sites.
Details
Warning:
This extension failed to redirect a network request to https://www.amazon.com/ because another extension (Smile Always) redirected it to http://smile.amazon.com/?sa-no-redirect=1.

**Comment by jeremyn** [comment] 2016-11-22 16:00
Thanks for the report, however I'm closing this issue as a duplicate of issue https://github.com/EFForg/https-everywhere/issues/6034 .

**Closed by jeremyn** 2016-11-22 16:00 UTC
