### ISSUE TITLE
Firefox Nightly's settings dark mode

### ISSUE THREAD

**Issue by rugk** [EFForg/https-everywhere#17841] opened 2019-04-27 16:22 UTC
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

I've discovered a big CSS problem in my add-on and checked some other add-ons, to see you are also affected.

In Firefox 68 (Nightly), the system' dark mode is governed by `prefers-color-scheme` is also applied to `about:addons`.

That includes add-on options page (presumably only if they use `browserStyle`?).

This is how your add-on looks like then:
![image](https://user-images.githubusercontent.com/11966684/56852266-51dc4600-6919-11e9-80af-e9e33ec835ba.png)

### See https://github.com/rugk/offline-qr-code/issues/190 for details.

----

So I've opened https://discourse.mozilla.org/t/firefox-68-nightly-added-dark-version-to-about-addons-breaking-many-add-ons/38716 for discussing this with Mozilla, as I currently have no idea what their plan in this direction is.

In any case, you likely will have to adjust your add-on.

**Comment by pipboy96** [comment] 2019-04-27 21:47
Duplicate of #12484.

**Closed by pipboy96** 2019-04-27 21:47 UTC

**Comment by pipboy96** [comment] 2019-04-28 12:54
I will release a PR for this issue soon.

**Comment by rugk** [comment] 2019-04-28 13:47
Okay, but remember this is currently only implemented in Nightly. So to not make it look awkward, you possibly also have to wait some time until that change hits Firefox Stable, before releasing it.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1544212

**Comment by pipboy96** [comment] 2019-04-28 13:57
@rugk It won't do anything unless dark mode is actually on.

**Comment by rugk** [comment] 2019-04-28 14:31
It will. If you use `prefers-color-scheme` that is supported since Firefox 67, but the dark mode in `about:addons` is currently just in Nightly.

**Comment by pipboy96** [comment] 2019-04-28 14:35
My current solution is to simply make a forced white bg on this page.

**Comment by rugk** [comment] 2019-04-28 16:15
Well if you do that, then possibly you need to do nothing/adjust nothing, because maybe Firefox may do so anyway for all add-ons, see https://phabricator.services.mozilla.com/D28369.

Again: We speak about **Nightly**. Everything may still change.

**Comment by pipboy96** [comment] 2019-04-28 20:33
@rugk That's not really "handling" dark mode, more like a stopgap. I guess Nightly users should expect possible breakage, so fixing on our side immediately is not a priority, even though it's not very difficult.

**Comment by rugk** [comment] 2019-04-29 06:41
That's what I've said… :blush:

**Comment by pipboy96** [comment] 2019-04-29 15:23
@rugk Is it fine for us to not make any fixes until FF fixes that upstream?

**Comment by rugk** [comment] 2019-04-29 15:49
To my judgement (I am nobody official here.) yes. When it is in beta, you should possibly have a look and tweak it, so it looks nice.
