### ISSUE TITLE
Chromium plugin: Optimize memory consumption

### ISSUE THREAD

**Issue by stokito** [EFForg/https-everywhere#2954] opened 2015-09-22 08:39 UTC
I'm using Chrome and HTTPS Everywhere cosumes more that 100mb on my machine. It's more that all others extensions in my Chrome.
Maybe this is some kind of memory leak.
Could you optimize it?

Thanks

**Comment by fuglede** [comment] 2015-09-22 11:13
This should be a duplicate of #1775.

**Closed** 2015-09-22 11:51 UTC
