### ISSUE TITLE
mac: PDF document not loading in Chrome

### ISSUE THREAD

**Issue by tgdn** [EFForg/https-everywhere#17620] opened 2019-03-21 11:46 UTC
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)

Type: code issue

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

Cannot load PDF document in Google Chrome (v73.0.3683.75) on macOS (v10.14).

HTTPS everywhere Google Chrome extension (v2019.1.31).

Link to PDF: http://www.yildiz.edu.tr/~aktas/courses/CE-0112822/20-05-3-2.pdf

Steps to reproduce:

1. Enable HTTPS Everywhere on Google Chrome with both settings enabled: (Enable HTTPS Everywhere, Encrypt All Sites Eligible (EASE))
2. Enter PDF url in url bar and try to access it
3. HTTPS Everywhere will warn that HTTPS cannot be enabled and thus you will have to add an exception.
4. Once the exception is added, the pdf reader on Chrome is opened but does not load the PDF even after reloading the page.

When disabling the extension and reloading the page, the PDF is loaded.

**Comment by pipboy96** [comment] 2019-03-22 18:17
@tgdn Can't reproduce on Firefox Nightly, Linux.

**Comment by pipboy96** [comment] 2019-03-27 22:50
Can't reproduce on Chrome, Linux either.

**Comment by pipboy96** [comment] 2019-03-27 23:12
Can't reproduce on macOS Chrome, closing.

**Closed by pipboy96** 2019-03-27 23:12 UTC
