### ISSUE TITLE
Text missing in UI in Firefox when using non-"English (US)" language

### ISSUE THREAD

**Issue by jony0008** [EFForg/https-everywhere#12009] opened 2017-08-20 10:04 UTC
![strings](https://user-images.githubusercontent.com/23194385/29493883-b29e6af4-859f-11e7-860f-880e773b7105.png)

**Comment by koops76** [comment] 2017-08-20 10:35
Looks like an i18n issue.

**Comment by Cynnexis** [comment] 2017-08-20 16:01
![bug](https://user-images.githubusercontent.com/2932967/29496339-e9b81f4a-85d0-11e7-9b6f-f527f23520ba.png)
I have the same problem on Firefox 52.3.0 on Ubuntu: There is nothing but the check boxes and the version string.

**Comment by jeremyn** [comment] 2017-08-21 23:51
What's an example URL or ruleset where this happens?

**Comment by Cynnexis** [comment] 2017-08-22 06:06
In my case, this bug appears regardless of the URL, even in the Start Page `about:home`. For the ruleset, I noticed that each time I try to check/uncheck a box, the panel close, and when I reopen it, the configuration did not change (same config as the image below: first box checked, this other uncheck).

![](https://user-images.githubusercontent.com/2932967/29496339-e9b81f4a-85d0-11e7-9b6f-f527f23520ba.png)

**Comment by koops76** [comment] 2017-08-22 08:58
@Cynnexis Send me a developer console log.

**Comment by koops76** [comment] 2017-08-22 08:59
It looks like JavaScript in `popup.html` have crashed.

**Comment by Bisaloo** [comment] 2017-08-22 14:21
I can reproduce on Tor Browser 7.0.4.

**Comment by Cynnexis** [comment] 2017-08-23 06:12
@koops76 How can I access to the console log?

**Comment by koops76** [comment] 2017-08-23 10:13
@Cynnexis `F12` > Console

**Comment by mkjorling** [comment] 2017-08-23 18:30
I had the exact same result at first as @Cynnexis showed a screenshot of above. Curiously, when I opened the console through Tools > Web Developer > Web Console, and cleared the console log by clicking on the trash can icon to the left in its toolbar (I don't know if this is really relevant or not, but am including it for completeness; there was no relevant output before I cleared the console), HTTPS Everywhere started displaying correctly; I clicked its toolbar button hoping to capture some debugging information to add to this issue, and it displayed just fine. It also looks like Privacy Badger, which has been acting up exactly like HTTPS Everywhere just did, has now also started working. Both appear to remain stable also after restarting the browser. No output in the console window. Firefox ESR 52.3.0 / 64-bit, Debian.

**Comment by Cynnexis** [comment] 2017-08-24 07:06
I opened the console windows juste like @koops76 said and load a page (Qwant.com in this case) . Then I clicked the _HTTPS Everywhere_ button, but no outputs appeared in the console:
![bug](https://user-images.githubusercontent.com/2932967/29653635-e783a12c-88aa-11e7-9295-83c89a94703e.png)
Clicking the trash icon to clear the console did nothing, even when I reopened _HTTPS Everywhere_ panel.

**Comment by mkjorling** [comment] 2017-08-24 11:11
Sorry; strike my previous comment. I believe I've found what caused the issue shown in https://github.com/EFForg/https-everywhere/issues/12009#issuecomment-323594187 at least in my case: Javascript. If I use the "Toggle Javascript" add-on toolbar button to completely disable Javascript, then the HTTPS Everywhere dropdown shows as essentially empty and doesn't work, as previously shown. If I turn Javascript back on, then it works. @Cynnexis I see that you have NoScript in "no scripts allowed" mode in your most recent screenshot. Consider trying turning on Javascript globally via NoScript, and also if you have any other add-on that may interfere with Javascript make sure it doesn't, and see if it works better.

**Comment by jeremyn** [comment] 2017-08-24 15:49
In that case this is a duplicate of issue #11948, see specifically https://github.com/EFForg/https-everywhere/issues/11948#issuecomment-323188167. There are issues opened against both Firefox and Tor as linked in https://github.com/EFForg/https-everywhere/issues/11948#issuecomment-323231663.

**Comment by LMLB** [comment] 2017-08-29 16:44
I have javascript enabled and I have the same result as @jony0008.

**Comment by jeremyn** [comment] 2017-08-29 20:29
@LMLB Please describe your system and provide a screenshot.

**Comment by LMLB** [comment] 2017-08-30 07:43
Windows 7 64 bit, Firefox 55.0.3 (64-bit, Swedish).

![Swedish screenshot](https://user-images.githubusercontent.com/6322603/29860206-8c8e7228-8d65-11e7-9941-bb3479b74384.png)

However, if I install the "English (US)" language pack from https://addons.mozilla.org/firefox/language-tools/ and change the `general.useragent.locale` pref to `en-US` and restart Firefox, it looks like this:

![English screenshot](https://user-images.githubusercontent.com/6322603/29860523-9d0cdb84-8d66-11e7-85aa-05a0947acd3d.png)

**Comment by koops76** [comment] 2017-08-30 08:27
@LMLB Indeed, it is an I18N issue. We need to do something with the current I18N system.

**Comment by jeremyn** [comment] 2017-08-30 17:37
Thanks for the extra information @LMLB .

**Comment by macak3335** [comment] 2017-08-31 18:44
Glad I'm not the only one with this problem! 
I can confirm it occurs on Tor browser (newest version). I reistalled Tor 5 or 6 times, and got it every time soon after some browsing on Google. In the beginning the text is showed good, but after several searches on google it gets blanked out + after it gets blanked out it gets moved from the menu to the toolbar (next to menu button) on it's own!

**Comment by rncgit** [comment] 2017-09-30 05:53
I am having the same problem - but it's not due to some of the claimed causes mentioned in this thread. My system lang is US English, including the Firefox general.useragent.locale setting. I have completely disabled Noscript.  I have allowed all the popup settings I can find, but it doesn't make any difference.  Two points that hasn't been made so far::
1. when I R-click the toolbar icon, the full popup (with text) appears for half a second, then is overwritten by another popup that shows only scattered tickboxes and horizontal lines, no text. 
2. certain entries on the R-click menu are selectively missing now from other Firefox add-ons as well, eg, Save-Page-WE

**Comment by koops76** [comment] 2017-09-30 07:08
@rncgit Likely a Firefox issue.

**Comment by jony0008** [comment] 2017-10-01 10:13
Any progress on this issue? I still have the problem.

**Comment by Hainish** [comment] 2017-10-05 22:21
This is because the actual translations have been blanked out for 3 locales: `sv_SE` (Swedish) `ca@valencia` (Valencian Catalan) and `ms` (Malay).  I'll try to get this fixed ASAP.

**Comment by jony0008** [comment] 2017-10-06 02:39
sv should be used for Swedish and not sv_SE because Swedish is spoken in other countries such as Finland and is not specific to Sweden. Swedish text in other countries is not different.

**Comment by Hainish** [comment] 2017-10-06 03:50
@jony0008 my suggestion is only for HTTPS Everywhere, not in general.  We'll still be fixing the problem for the affected locales

**Comment by niklasholm** [comment] 2017-11-07 15:57
@Hainish I tried changing `general.useragent.locale` to `sv` from the default (`sv-SE`) but it didn't make any difference.

**Comment by Hainish** [comment] 2017-12-15 06:45
I've just pinged the upstream transifex maintainer again.

**Comment by Hainish** [comment] 2018-01-10 22:53
I've received notification that the upstream transifex fix was not pushed properly.  I have been notified that it was fixed with this commit: https://gitweb.torproject.org/translation.git/commit/?h=https_everywhere&id=4b55350d48a78614ad14087dc4eefe289543ff5b

**Comment by jony0008** [comment] 2018-01-11 03:32
@Hainish Swedish strings are missing in the commit. I think you pushed sv_SE strings which don't exist, and sv strings should be pushed instead.

**Comment by Hainish** [comment] 2018-02-27 01:08
@jony0008 can you confirm that the Swedish translation is still missing in the `2018.2.26` release? (It may take a moment to propagate the update in the Firefox & Chrome extension stores.)

**Comment by jony0008** [comment] 2018-02-27 05:48
@Hainish The Swedish translation is not missing in the latest version and the previous version. It works well in both Firefox and Chrome.

**Comment by Hainish** [comment] 2018-02-28 03:44
@jony0008 great, thank you! Closing now.

**Closed by Hainish** 2018-02-28 03:44 UTC
Labels: bug, ui, webextensions-firefox
