### ISSUE TITLE
 This extension may have been corrupted

### ISSUE THREAD

**Issue by hwk603** [EFForg/https-everywhere#6855] opened 2016-09-12 07:12 UTC
chrome ： 53

always warning ： This extension may have been corrupted

 
![images-2016-09-12-1473663939](https://cloud.githubusercontent.com/assets/7033138/18427534/5a240a5c-78fb-11e6-8729-a517841f4f60.png)

**Comment by jeremyn** [comment] 2016-09-12 14:04
This is probably a duplicate of issue #5874 , so I'm closing this issue.

**Closed by jeremyn** 2016-09-12 14:04 UTC
