### ISSUE TITLE
Firefox hangs when https everywhere option button is pressed

### ISSUE THREAD

**Issue by typhoon71** [EFForg/https-everywhere#2003] opened 2015-06-26 11:51 UTC
Firefox 38.0.5, https everywhere 5.0.x (all of them)
Hitting the option button in the plugin page hangs firefox.
The menu on the top doesn't exibit the issue.

**Comment by fuglede** [comment] 2015-06-26 19:20
Duplicate of #1771?

**Comment by typhoon71** [comment] 2015-06-26 21:18
Seems so. I suppose I should've searched harder.
Anyway I don't get 100% CPU, just 25% and then firefox hangs. 
Did not check the memory before closing, but if it's as high as in 1771 then the extension needs some optimization (can't help, I'm no programmer).
If the info here is redundant we can close this?

**Comment by reedy** [comment] 2015-06-28 01:32
Well, more cpu cores etc, depending on how utilisation etc is shown. I'd suspect it is a dupe of 1771, so closing :)

**Closed by reedy** 2015-06-28 01:32 UTC
