### ISSUE TITLE
Option to highlight insecure URLs

### ISSUE THREAD

**Issue by l0b0** [EFForg/https-everywhere#14608] opened 2018-02-11 21:56 UTC
Type: feature request

It would be great to have a way to in some way highlight all insecure URLs ("http://…", "ftp://…", …) on a web page. Use cases:

- As a developer, find insecure links to my own site which should be fixed.
- As a browsing user, avoid insecure links. Many sites link to the HTTP version of their own pages and other sites, even though the target web site ultimately redirects to HTTPS.
- As a user looking for software to install, avoid insecure download links.

(There used to be a Firefox add-on to do this, but it seems to have disappeared.)

**Comment by Bisaloo** [comment] 2018-02-12 08:44
> - As a developer, find insecure links to my own site which should be fixed.

This feature is already implemented in HTTPS Everywhere. If you open developper tools, you will see a tab called "HTTPS Everywhere". With it, you can analyse the current page and see which links can/should be fixed.

> - As a browsing user, avoid insecure links. Many sites link to the HTTP version of their own pages and other sites, even though the target web site ultimately redirects to HTTPS.
> - As a user looking for software to install, avoid insecure download links.

This can easily be achieved with [Stylus](https://add0n.com/stylus.html) and any extension that allow users to write custom styles by using the following snippet on all pages:

```css
a[href^="http:"] {
    color: red !important;
}
```

**Comment by pipboy96** [comment] 2019-03-31 07:28
Duplicate of #14895 and #16417.

**Closed by pipboy96** 2019-03-31 07:28 UTC
