### ISSUE TITLE
HTTPS error pop-up message

### ISSUE THREAD

**Issue by GNUbahn** [EFForg/https-everywhere#7369] opened 2016-10-18 05:03 UTC
When I install Https Everywhere in Firefox, Abrowser or IceCat I get an error message in a pop up window. This has happened in Linux Mint and Trisquel.

![skaermbillede fra 2016-10-18 07-01-58](https://cloud.githubusercontent.com/assets/22903560/19464968/dd297452-9500-11e6-8b29-1f5a1303b239.png)

**Comment by jeremyn** [comment] 2016-10-18 15:16
Thanks for the report. This is a duplicate of https://github.com/EFForg/https-everywhere/issues/4909, so I'm closing this issue.

**Closed by jeremyn** 2016-10-18 15:16 UTC
