### ISSUE TITLE
Feature request: Online rulesets

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#2605] opened 2015-08-19 16:32 UTC
Would it be possible to have the rulesets on a server where clients could just periodically download them as they update?  It seems like it would eliminate the problem of having to wait for an entirely new version of the extension before a site with a problem could be fixed.  Have it more along the lines of an Adblock Plus subscription in that aspect.

**Comment by rugk** [comment] 2015-08-19 16:39
Nice idea. :+1:

**Comment by jsha** [comment] 2015-08-19 17:17
We've definitely considered this strongly, and a GSoC participant last year produced an implementation for Firefox: https://github.com/EFForg/https-everywhere/pull/437. In the end I decided that, since releasing rulesets requires the same degree of care in signing that releasing the extension does, it's simpler to keep the current system where the extension is bundled with its rules. For instance, unbundling the rules would not actually allow daily updates to the rulesets, because we would have to manually sign those updates. I may wind up reconsidering in the future, depending on how onerous the new AMO release process becomes.

Closing as a duplicate of #437.

**Comment by foobar13373** [comment] 2015-08-22 07:43
Why would the rules have to be signed by AMO? Extensions like AdLock, uBlock and so on, can download their lists. Aren't the rules simple xml files? And xml is just plain text, just like the filter lists that uBlock or AdBlock use.

**Comment by rugk** [comment] 2015-08-22 08:07
I don't think they have to be signed by AMO, but they would need a signature so that HTTPSE can verify they are genuine.

**Comment by jsha** [comment] 2015-08-22 15:20
@rugk has it right. HTTPS Everywhere can rewrite any URL to any other URL, which would be a dangerous capability if someone was able to inject a bad ruleset into it. AdBlock and uBlock don't have to worry as much because they only block, not rewrite.

**Comment by foobar13373** [comment] 2015-08-22 16:08
But the rules come from a https site (-> eff.org) with a valid certificate. It's not like they come from something like http://wwrsdfsfgr5.verycooldownloadsite154.com

**Comment by semenko** [comment] 2015-12-17 22:21
Closed per above as duplicate of #437

**Closed by semenko** 2015-12-17 22:21 UTC
