### ISSUE TITLE
ACM Digital Library token not properly passed

### ISSUE THREAD

**Issue by martinbilles** [EFForg/https-everywhere#2087] opened 2015-07-08 14:24 UTC
The site at http://dl.acm.org/ offers scientific articles for download provided the user is identified as belonging to an institution that has purchased an ACM subscription. Accesses to dl.acm.org are rewritten in the style of http://dl.acm.org/dl.cfm?CFID=###&CFTOKEN=###

This is broken by HTTPS Everywhere, where accessing ACM DL will result in an authentication failure, and the user will not be served the material. Disabling the ACM rule in HTTPS Everywhere fixes the problem. Manually navigating the browser to https://dl.acm.org/ does not cause the problem.

**Comment by donced** [comment] 2015-07-09 10:18
The URL http://dl.acm.org/ doesn't redirect to http://dl.acm.org/dl.cfm?CFID=###&CFTOKEN=### in my case. Were you trying to access specific article? or just the home page? I don't see any rewrite rule to dl.cfm?CFID=###&CFTOKEN=### in the [ruleset](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/ACM.org.xml). Perhaps it's caused by `<securecookie host="^(?!cacm\.).*\.acm\.org$" name=".+" />`?

**Comment by martinbilles** [comment] 2015-07-09 13:27
I was mistaken. The CFID, CFTOKEN parameters actually get added when clicking the ACM logo on the top left of the page to go back to the home page.

Also, I was not able to reproduce the credentials problem on second try. I also tried activating the HTTPS Everywhere rule, clearing my cookies and visiting again, I am still properly authenticated. Weird.

**Comment by donced** [comment] 2015-07-10 05:02
so, no issue now?

**Comment by martinbilles** [comment] 2015-07-10 07:52
No, I cannot reproduce the issue.

**Comment by donced** [comment] 2015-07-10 08:00
you can close this issue then.

**Closed** 2015-07-10 19:29 UTC
