### ISSUE TITLE
[Discussion] Easier domain submission through a web app

### ISSUE THREAD

**Issue by koops76** [EFForg/https-everywhere#12662] opened 2017-09-20 19:36 UTC
Type: other

ping @Hainish @strugee.

I would like to develop a web app which allows to anonymously submit domains for @https-everywhere-bot to create issues for.

It will require a user to solve a reCAPTCHA puzzle and check if the domain is actually functional over HTTPS before creating any issue.

I will create a PoC soon.

**Comment by jeremyn** [comment] 2017-09-20 22:13
I'm closing this as a duplicate of https://github.com/EFForg/https-everywhere/issues/6322. I know that that issue is long and wandering, but note that a web app approach was specifically discussed in there (https://github.com/EFForg/https-everywhere/issues/6322#issuecomment-239857600, https://github.com/EFForg/https-everywhere/issues/6322#issuecomment-302667139).

**Closed by jeremyn** 2017-09-20 22:13 UTC
