### ISSUE TITLE
'Block all unencrypted traffic' auto disabled at startup

### ISSUE THREAD

**Issue by kaymio** [EFForg/https-everywhere#12525] opened 2017-09-12 08:50 UTC
Arch Linux 64, Firefox 55.0, Vivaldi 1.11.917.43

Since a few weeks the 'Block all unencrypted traffic' feature is not working at startup of the mentioned browsers. The symbol is blue, while the entry in the menu is marked correctly. After disabling and enabling again the symbol becomes red and it is working again. This has to be repeated at each startup of the browser.

**Comment by jeremyn** [comment] 2017-09-12 16:17
I'm closing as a duplicate of issue https://github.com/EFForg/https-everywhere/issues/12406. Please feel free to comment on that issue.

**Closed by jeremyn** 2017-09-12 16:17 UTC
