### ISSUE TITLE
gmx.net rewrite to gmx.ch

### ISSUE THREAD

**Issue by jsha** [EFForg/https-everywhere#2337] opened 2015-07-28 17:41 UTC
https://trac.torproject.org/projects/tor/ticket/16681

@donced, could you take a look at this since you worked on the GMX rule most recently?

**Comment by pauLee** [comment] 2015-07-30 09:18
:+1:  Yes, please solve that faulty rewrite. It´s very annoying.

**Comment by donced** [comment] 2015-08-08 08:18
Also reported by https://github.com/EFForg/https-everywhere/issues/1895#issuecomment-124518687, with fix https://github.com/EFForg/https-everywhere/pull/2329

**Comment by merlin-s** [comment] 2016-01-16 15:59
not fixed yet? Or was there a fix + regression?

gmx.net and gmx.de/gmx.at still redirect to https://www.gmx.ch.

**Comment by donced** [comment] 2016-01-28 12:24
@merlin-s I've already removed the redirect rule [GMX.xml](https://github.com/EFForg/https-everywhere/pull/2329/files). Chrome addon (v 2015.12.16) and Firefox addon (v [5.1.2](https://www.eff.org/files/https-everywhere-latest.xpi)) incorporate the fix (doesn't redirect anymore). However Firefox AMO still using v [5.1.0 ](https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/) which has yet to include the fix. On the other hand, [master](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/GMX.xml) branch has included the fix, but not [stable](https://github.com/EFForg/https-everywhere/blob/stable/src/chrome/content/rules/GMX.xml) branch.

**Comment by merlin-s** [comment] 2016-01-30 21:50
Was it your intention to remove any redirection to https for _gmx.*_ sites? Because that is what your fix does.

**Comment by donced** [comment] 2016-02-09 14:53
My main intention is to remove line 140-141 conform with the [ruleset style](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) (`Avoid snapping redirects....`). The rewrite rule on line 152-153 (changed file) applies to all _targeted_ gmx sites (line 91-130 of [changed file)](https://github.com/donced/https-everywhere/blob/0315ff5b6341b775070fbac0b29b6736ff231594/src/chrome/content/rules/GMX.xml). Line 152-153 would redirect all sites specified along line 91-130 to https.

**Comment by merlin-s** [comment] 2016-02-09 23:44
thanks for explaining. your changes are fine. i noticed that the gmx rule was still deactivated in my client, apparently i deactivated it a month ago and forgot about that after installing the latest httpse version.

my bad.

**Comment by HTTPSNowhere** [comment] 2017-07-16 11:55
This issue no longer appears, gmx.net rewrites to https://www.gmx.net
Looking at the [ruleset](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/GMX.xml) one can't find a rewrite rule for gmx.net->gmx.ch so it has been fixed.

@J0WI can you please close this issue? Thanks.

**Closed** 2017-07-17 21:20 UTC
Labels: ruleset-bug
