### ISSUE TITLE
"XML parsing error: undefined entity" in Firefox on Linux Mint

### ISSUE THREAD

**Issue by HTTPSing** [EFForg/https-everywhere#7716] opened 2016-11-30 04:26 UTC
**OS:** Linux Mint 18 (4.4.0-47-generic)
**Browser:** Firefox 50.0
**HTTPS Everywhere:** 5.2.7

Every time I start Firefox, I get the following popup:
![start](https://cloud.githubusercontent.com/assets/24262939/20739709/5bc47cc0-b6bd-11e6-953f-729107fc1375.png)
I am afraid the error message is in Danish, but it should not be very hard to understand. This issues title, _"XML parsing error: undefined entity"_, is a translation of the first line, _"Adresse"_ is _"Address"_, _"Linje"_ is _"Line"_ and _"kolonne"_ is _"column"_.
Having closed the popup, Firefox works fine.

If I attempt to open the HTTPS Everywhere settings, I get the following popup:
![settings](https://cloud.githubusercontent.com/assets/24262939/20739715/66a7110c-b6bd-11e6-830f-52295ff8949d.png)
Again, the error message is in Danish, but the translation is the same as above.
The settings do not open, and thus can not be accessed.

**Comment by jeremyn** [comment] 2016-11-30 18:18
Thanks for the report, however I'm closing this as a duplicate of issue https://github.com/EFForg/https-everywhere/issues/4909.

**Closed by jeremyn** 2016-11-30 18:18 UTC
