### ISSUE TITLE
Myfitnesspal.com issue 

### ISSUE THREAD

**Issue by mgik20** [EFForg/https-everywhere#11312] opened 2017-07-24 04:43 UTC
I am not certain the exact cause, but using HTTPS Everywhere with myfitnesspal.com causes an error on the site.

Some details are here on a ticket opened by someone else with myfitnesspal.com

http://myfitnesspal.desk.com/customer/portal/questions/17101256-site-down-for-maintenance

**Comment by Bisaloo** [comment] 2017-07-24 12:06
fixed in https://github.com/EFForg/https-everywhere/pull/11033.

**Comment by J0WI** [comment] 2017-07-24 21:23
Dupe of #11312

**Closed by J0WI** 2017-07-24 21:23 UTC
