### ISSUE TITLE
Disable https everywhere once for this site

### ISSUE THREAD

**Issue by BartOutOfTheBox** [EFForg/https-everywhere#17701] opened 2019-04-07 10:20 UTC
Type: feature request

[//]: # (Include any other relevant information below. Thank you again for)
Upon using a website which doesn't support https, currently you can choose to disable https everywhere for this site. However an option to disable just this one time, would be nice.

This feature would make it possible for users to check out a site, knowingly that it is using an unsecure protocol.

**Comment by Bisaloo** [comment] 2019-04-07 10:38
Thanks for reaching out. I'm going to close this issue as a duplicate of https://github.com/EFForg/https-everywhere/issues/16998. Please let me know if you disagree and this is a different issue.

My understanding is that this will be addressed as part of the ongoing UI redesign #16669

**Closed by Bisaloo** 2019-04-07 10:38 UTC
Labels: duplicate

**Comment by BartOutOfTheBox** [comment] 2019-04-07 12:03
Hi Hugo,

Seems like this is indeed a duplicate issue. Thanks for closing this one.

Somehow I must have missed it when browsing through the already existing
issues labeled with the tag for new functionality.

KR,
Bart
