### ISSUE TITLE
Broken site: deezer.com not functioning with default settings

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [EFForg/https-everywhere#4768] opened 2016-05-13 09:31 UTC
Apologies in advance if this is the wrong place to talk about broken sites; if not please inform me and i'll refrain from it once and for all.

The music streaming website deezer.com only works once I untick "deezer.com" in the list of Stable Rules. Is that how it is supposed to be? (I'm on Windows 10 and Chrome 50.0.2661.102 m.)

PS: Thanks to all dev's for this awesome extension!

Edit: This is the same in Firefox 46.0.1

**Comment by J0WI** [comment] 2016-05-14 15:40
Could you tell us more what exactly is broken when you enable the rule?
Do you have any errors in your browser console?

**Comment by AlfonsoMuskedunder** [comment] 2016-05-16 15:47
@J0WI Thank you for your reply. With the rule enabled, menus from which tracks are being selected simply won't open.

Here is a screenshot when the rule is disabled. I just clicked on "Alben":
![deezer_functioning](https://cloud.githubusercontent.com/assets/10466043/15294810/076b6488-1b8e-11e6-9e53-fa4c75fb923c.jpg)

With the rule enabled, the list of albums simply won't appear:
![deezer_broken_console](https://cloud.githubusercontent.com/assets/10466043/15294844/2fc48342-1b8e-11e6-86f4-dd40241b4853.jpg)

**Comment by J0WI** [comment] 2016-05-16 17:04
You need an account to reproduce this, right?

**Comment by AlfonsoMuskedunder** [comment] 2016-05-16 20:00
That's correct. Regular accounts are free, however.

**Comment by gyphub** [comment] 2016-06-30 09:59
In addition, the search on the site does not work if the rule for Deezer.com is enabled.
![screen_search_not_working](https://cloud.githubusercontent.com/assets/13639560/16484331/f93f72de-3eb8-11e6-8579-eaa559b8efa4.png)

If the rule is disabled, search works okay:
![screen_rule_disabled](https://cloud.githubusercontent.com/assets/13639560/16484546/04e3b2d4-3eba-11e6-9cc1-9dad4c7e38b3.png)

**Comment by jwatt** [comment] 2017-01-10 15:38
For me enabling HTTPS Everywhere somehow results in this error in the console:

`ReferenceError: reference to undefined property ma.https [Learn More]  vb.js:87:1679`

( http://connect.facebook.net/en_GB/sdk/vb.js )

When that exception is thrown it seems to interrupt the deezer scripts sufficiently badly that playing music on the site no longer works (clicking play buttons has no effect).

**Comment by jw243** [comment] 2017-01-22 18:00
For me, it is the same. With the default settings, deezer.com won't work properly. When I click on any menu entry on the left hand side of the browser window, the main frame simply stays empty. The content of the main frame will not be loaded. If the deezer.com rule is switched off in https everywhere, the site works as intended.

**Comment by jwatt** [comment] 2017-02-06 01:03
[The comment in my pull request](https://github.com/EFForg/https-everywhere/pull/8418/commits/cc9f60bcdf146ce16569159aaf886952c38cb8a7) to disable this rule by default explains why things are broken.

**Comment by J0WI** [comment] 2017-02-12 20:50
closed by #8418

**Closed by J0WI** 2017-02-12 20:50 UTC
Labels: CORS-bugs
