### ISSUE TITLE
Add (optional) onion mode for forcing .onion for HTTP(s)

### ISSUE THREAD

**Issue by e5f3c2ea895af0f27667** [EFForg/https-everywhere#8253] opened 2017-01-27 13:55 UTC
It would be great to have an optional onion mode where if enabled it would force .onion sites for particular HTTP website, for example when putting "qubes-os.org" instead of going to "https://www.qubes-os.org/" it would go to "http://qubesos4rrrrz6n4.onion/"

Also would such rules need a dedicate database?

**Comment by jeremyn** [comment] 2017-01-27 19:09
Thanks, but I'm closing this as a duplicate of issue https://github.com/EFForg/https-everywhere/issues/3798. Please feel free to add your thoughts on this feature there.

**Closed by jeremyn** 2017-01-27 19:09 UTC
