### ISSUE TITLE
https-everywhere does not work on firefox nightly anymore

### ISSUE THREAD

**Issue by unknownmhack** [EFForg/https-everywhere#11822] opened 2017-08-11 15:44 UTC
because Firefox is changing to web-extensions, the extension is blocked on Firefox nightly

**Comment by cschanaj** [comment] 2017-08-11 15:52
https://github.com/EFForg/https-everywhere/issues/11759#issuecomment-321386955

**Comment by jeremyn** [comment] 2017-08-11 16:04
Closing as a duplicate of #11759 .

**Closed by jeremyn** 2017-08-11 16:04 UTC

**Comment by koops76** [comment] 2017-08-11 17:47
@unknownmhack https://www.eff.org/files/https-everywhere-test/index.html
Download the latest WebExtensions-only version here.
