### ISSUE TITLE
https-everywhere breaks OpenStreetmaps routing capabilities

### ISSUE THREAD

**Issue by alex42ka** [EFForg/https-everywhere#1770] opened 2015-05-25 11:14 UTC
Wanted to test the routing capablities provided by OpenStreetmap found on www.openstreetmap.org. Having https-everywhere enabled it didn't work. Using manually https://www.openstreetmap.org made it work again as well with https-everywhere enabled.

**Comment by reedy** [comment] 2015-05-25 13:34
WFM on Chrome. Do you see any JS console errors?

**Comment by alex42ka** [comment] 2015-05-25 14:21
WFM?
Routing works in chromium, even when https-everywhere is activated, but I'm not redirected to https://www.openstreetmap.org.

**Comment by reedy** [comment] 2015-05-25 18:25
WFM = Works for me

Looking at the ruleset, it's not supposed to redirect https://www.openstreetmap.org to https://www.openstreetmap.org

**Comment by David-Leudolph** [comment] 2015-08-08 11:25
I'm having the same issue with Firefox for Linux Mint and Windows: 

- Firefox 39.0.3 / Linux Mint 17.1 / HTTPS-Everywhere 5.0.7 
- Firefox 39.0.3 / Windows 7 / HTTPS-Everywhere 5.0.7 

**Steps to reproduce:** 

1. Open openstreetmap.org 
2. Click the blue routing button with the two arrows 
3. Enter a start and destination 
4. Click the Go button or press enter 

Nothing happens. 

*The fix provided by alex42ka doesn't work for me.*

**Comment by semenko** [comment] 2015-12-17 21:37
WFM too in latest version, and I think the ruleset got updated.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.

**Closed by semenko** 2015-12-17 21:37 UTC
