### ISSUE TITLE
Pressing "See more" under "Settings for this website" reloads the page on Chrome.

### ISSUE THREAD

**Issue by pipboy96** [EFForg/https-everywhere#17902] opened 2019-05-05 09:49 UTC

**Comment by Bisaloo** [comment] 2019-05-05 10:21
I'm closing this as a duplicate of #17866. Please let me know if you disagree.

**Closed by Bisaloo** 2019-05-05 10:21 UTC
Labels: chrome, ui

**Comment by pipboy96** [comment] 2019-05-05 10:40
@Bisaloo Thx, didn't notice.
