### ISSUE TITLE
Convert Firefox extension to a WebExtension

### ISSUE THREAD

**Issue by 6a68** [EFForg/https-everywhere#8622] opened 2017-02-22 05:53 UTC
Firefox is [moving to WebExtensions](https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/) in 2017, and will be removing non-WebExtensions from AMO by the end of the year, in FF 57.

The https-everywhere code should get much simpler, since the same APIs that power the Chrome extension code should work on Firefox. While the WebExtension APIs aren't all supported yet, I think the pieces used by https-everywhere are:

- requests can be intercepted using the [`webRequest`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest) and [`webNavigation`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webNavigation) APIs
- the toolbar button can be wired up using the [`browserAction`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction) API
- the popup contents can be written as simple HTML, and specified in the `manifest.json` file's `browser_action.default_popup` config
- all the permissions requested by the https-everywhere WebExtension [are supported](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions)

Looking through the [known incompatibilities](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities#permissions) between FF and Chrome, I didn't immediately see any blockers--but I'm not super familiar with this code, so maybe I've missed something. There's [another page](https://arewewebextensionsyet.com/) which lists known issues. Again, I don't see any blockers, but someone more familiar with the Chrome code should take a look.

So, yeah. Should be really satisfying to mass-delete all that weird XUL and XPCOM stuff. Want some help getting things ported over?

**Comment by Bisaloo** [comment] 2017-02-22 05:57
see https://github.com/EFForg/https-everywhere/issues/7389 and https://github.com/EFForg/https-everywhere/issues/2640

**Comment by jeremyn** [comment] 2017-02-22 20:18
Thanks @6a68. I'm closing this issue as a duplicate of the issues that @Bisaloo mentions, but I'm pinging @Hainish so he is aware of your specific interest in this migration.

**Closed by jeremyn** 2017-02-22 20:18 UTC

**Comment by 6a68** [comment] 2017-02-23 01:38
thanks!
