### ISSUE TITLE
Dell.com rules break the site (missing images)

### ISSUE THREAD

**Issue by Diazonium** [EFForg/https-everywhere#13209] opened 2017-10-18 08:50 UTC
[//]: # (Thank you for reporting an issue to HTTPS Everywhere.)
[//]: # (We welcome input from users on improving this project.)
[//]: #
[//]: # (Please help us by following this issue template.)
[//]: # (You can delete all blank lines and all lines starting)
[//]: # (with the comment marker, such as this one.)
[//]: #
[//]: # (Delete all but one of the following "Type" lines.)
[//]: # (Leave in the line that best describes the issue you are reporting.)

Type: ruleset issue

[//]: # (If you are reporting a ruleset/website problem, include the top-level)
[//]: # (domain below. For example, if you want to report an issue about)
[//]: # ("one.example.com" and "two.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: example.com)
[//]: #
[//]: # (Be sure to remove the parenthesis and comment marker.  If you are only)
[//]: # (reporting an issue about "one.example.com", then the line below should)
[//]: # (be:)
[//]: #
[//]: # (Domain: one.example.com) 
[//]: #
[//]: # (Only include one top-level domain. If you have more than one top-level)
[//]: # (domain to report, such as both "example.com" and "example.org", open a)
[//]: # (new issue for each top-level domain.)
[//]: #
[//]: # (If you are not reporting a ruleset/website problem, you can delete the)
[//]: # ("Domain" line or leave it blank.)

Domain: dell.com

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

The Dell website breaks (missing images), with the default ruleset.
For example images are missing here: http://www.dell.com/en-us/work/shop/enterprise-products/sf/poweredge-tower-servers

**Comment by Bisaloo** [comment] 2017-10-18 09:04
Related: https://github.com/EFForg/https-everywhere/issues/12974

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment] 2017-11-02 14:31
I can't reproduce this, @Bisaloo @Diazonium can you confirm that this no longer happens?

**Comment by mileskrell** [comment] 2017-12-31 22:16
I can still reproduce this on HTTPS Everywhere 2017.12.6. Disabling the stable rule "Dell.com (partial)" fixes it.

**Comment by Sayrus** [comment] 2018-01-09 15:23
This happens only when accessing Dell's http version of the website. If you use the https version, HTTPS Everywhere does not break it.

I can reproduce on Firefox 57.0.4 with HTTPS Everywhere 2017.12.6.

**Comment by gloomy-ghost** [comment] 2018-04-28 05:45
Duplicate of #12974

**Closed by gloomy-ghost** 2018-04-28 05:45 UTC
Labels: top-1k
