### ISSUE TITLE
Issue with extension settings in Brave Browser 

### ISSUE THREAD

**Issue by Tnifey** [EFForg/https-everywhere#19641] opened 2020-10-02 18:03 UTC
Type: I can't remove rule from settings in Brave Browser extension panel...
This image explains what I mean: [WARNING: This image may potentially trigger seizures for people with photosensitive epilepsy. Viewer discretion is advised.](https://i.imgur.com/qzQbAc9.gif)

HTTPS Everywhere version: 2020.8.13
Brave Browser version: 1.13.86 Chromium: 85.0.4183.102 (64-bit)

`brave://extensions/  -> click on HTTPS Everywhere   -> Extension options`

[//]: # (Include any other relevant information below. Thank you again for)
[//]: # (helping to improve HTTPS Everywhere.)

**Comment by pipboy96** [comment] 2020-10-02 20:02
@Tnifey Thanks for report. Unfortunately, we don't officially support Brave since it already includes its own HTTPS rewriter, but this will get investigated.

**Comment by pipboy96** [comment] 2020-10-11 06:32
@Tnifey Are you still experiencing this issue?

**Comment by Tnifey** [comment] 2020-10-11 11:58
@pipboy96 it is still the same.

* [/chromium/pages/options/index.html](https://github.com/EFForg/https-everywhere/blob/master/chromium/pages/options/index.html)
* [/chromium/pages/options/style.css](https://github.com/EFForg/https-everywhere/blob/master/chromium/pages/options/style.css)

I think that body element in these files should have `overflow-y: scroll`
The content area is slightly wider than the body element and creates that vertical scrollbar on the body. After that, content matches width due overflow and layout change (that button on top goes inline the others, but with scrollbar it goes down) and it removes that scrollbar.

If there was always scrollbar that button remains in same position.

**Comment by pipboy96** [comment] 2020-10-11 17:43
@Tnifey Please try updating Brave. I can't reproduce this bug with the latest version.

**Comment by zoracon** [comment] 2021-03-02 21:29
This options page is now it's own tab/page now instead of being constrained by this modal. Closing for now. Can reopen if issue persists for some reason.

**Closed by zoracon** 2021-03-02 21:29 UTC
Labels: bug
