### ISSUE TITLE
HTTPS Everywhere seems to disable Multiprocess feature in Firefox 49

### ISSUE THREAD

**Issue by unleasher** [EFForg/https-everywhere#7127] opened 2016-09-25 18:09 UTC
When I updated to v. 49 of Firefox, I noticed that Multiprocess was not enabled due to extensions and this feature was turned on in this version.   Going through my extensions and disabling them all to test this, I found out that https everywhere, when it is the only extension enabled, seems to turn off Multiprocess.  If someone could investigate that would be great!

This thread on the mozilla forums has some more information:
http://forums.mozillazine.org/viewtopic.php?f=38&t=3023892

Thank you!

**Comment by jeremyn** [comment] 2016-09-25 19:24
I can confirm that with Firefox 49.0.1, Windows 10, and HTTPS Everywhere 5.2.5, if I enable only HTTPS Everywhere, `about:support` shows `Multiprocess Windows`|`0/1 (Disabled by add-ons)`. If I disable HTTPS Everywhere, it shows `Multiprocess Windows`|`1/1 (Enabled by default)`. Note that HTTPS Everywhere should be enabled/disabled through `about:addons`, not through the HTTPS Everywhere user interface.

@cooperq @Hainish @jsha Please review.

**Comment by J0WI** [comment] 2016-09-26 12:30
Mozilla currently allows only whitelisted add-ons and web extensions for e10s (see also #2640).

**Comment by unleasher** [comment] 2016-09-27 02:57
So does that mean the creators of HTTPS Everywhere have to ask Mozilla to white list or do we have to wait until next year for the re-architected add-on system comes out?

**Comment by demarcusw** [comment] 2016-10-03 17:16
This may be a Windows only issue? I am running macOS Sierra version 10.12 with Firefox version 49.0.1. 

I have HTTPS Everywhere version 5.2.5 installed and when I check `about:support ` it shows `Multiprocess Windows 	1/1 (Enabled by user)`.

Having HTTPS Everywhere does not force disable Multiprocess for me

**Comment by jsha** [comment] 2016-10-10 20:56
Last I checked (~year ago) HTTPS Everywhere worked fine with e10s in Nightly builds. Something may have broken, or perhaps Mozilla has gone to whitelisting extensions for e10s support and neglected to include us. @Hainish or @cooperq can dig deeper.

**Comment by J0WI** [comment] 2016-10-11 13:29
Referring to the [e10s road map](https://wiki.mozilla.org/Electrolysis#Add-ons_Schedule):

- In Firefox 48 e10s is only enabled for users without any Add-Ons.
- In Firefox 49 e10s is only enabled for users with white listed Add-Ons.
- In Firefox 50 e10s is enabled, if all Add-Ons are marked as e10s compatible.
- In Firefox 51 e10s is enabled by default and non-compatible Add-Ons will be disabled.

Firefox 50 will be released today.

**Comment by jsha** [comment] 2016-10-11 17:37
I've confirmed that in `src/install.rdf`, we enable the [multiProcessCompatible boolean flag](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#multiprocessCompatible):

`        <em:multiprocessCompatible>true</em:multiprocessCompatible>`

So in theory HTTPS Everywhere should not cause e10s to be disabled. We'll need to try and repro with a Windows VM.

**Comment by jeremyn** [comment] 2016-10-11 18:11
I reproduced this on Windows 10, see https://github.com/EFForg/https-everywhere/issues/7127#issuecomment-249441020. Of course if you mean reproduce it locally for testing, I understand.

**Comment by Mikaela** [comment] 2016-10-12 07:28
I cannot reproduce this on Firefox 50.0b6 (Arch Linux) and didn't have it in earlier versions.

Are you sure that the issue is caused by HTTPS Everywhere instead of some other extension? You can verify it by installing https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/ and going to the addons page where you should see:

![selection_290](https://cloud.githubusercontent.com/assets/831184/19301085/5f0768fc-9066-11e6-80b3-00b43ded8f7d.png)

**Comment by jeremyn** [comment] 2016-10-12 15:21
In my case, on Windows, HTTPS Everywhere is the only active add-on.

**Comment by Hainish** [comment] 2016-10-12 16:54
I can reproduce the "Disabled by add-ons" error in:

- Windows 10, FF 49.0.1, HTTPSE 5.2.5
- Windows 10, FF Unbranded 49.0.1, HTTPSE 5.2.5
- Ubuntu 14.04, FF 49.0, HTTPSE 5.2.5
- Ubuntu 14.04, FF Unbranded 49.0.1, HTTPSE 5.2.5

I could not reproduce this in:

- Windows 10, FF Nightly 52.0a1, HTTPSE 5.2.5
- Windows 10, FF Developer 51.0a2, HTTPSE 5.2.5
- Ubuntu 14.04, FF Nightly 52.0a1, HTTPSE 5.2.5
- Ubuntu 14.04, FF Developer 51.0a2, HTTPSE 5.2.5

Based on these results, my guess is that something changed between Firefox 49.0 and Firefox 52.0 to perform proper e10s support checking.

**Comment by jsha** [comment] 2016-10-12 17:15
Ah, re-reading the roadmap @J0WI posted, this makes sense. There's a distinction between "white listed Add-Ons" and "Add-Ons marked as e10s compatible." It's not clear where the white list lives, but I'm guessing HTTPS-E was not on it. However HTTPS-E *is* marked as e10s compatible, so works in 50 and later. Problem solved?

**Comment by Hainish** [comment] 2016-10-12 18:06
@J0WI you say [here](https://github.com/EFForg/https-everywhere/issues/7127#issuecomment-252916477) that FF 50 will be released "today".  Looking at the [release schedule](https://wiki.mozilla.org/RapidRelease/Calendar), it looks like stable will be released on Nov 8.

So we can either wait for FF 50 to be released (minimal effort on our part and not the worst solution in the world) or we can seek to be whitelisted (more effort, possibly futile, but would enable e10s for FF 49 users currently.)

**Comment by Hainish** [comment] 2016-10-12 18:23
According to the folks in Mozilla IRC, being whitelisted is not an easy process, so looks like we don't have much of a choice but to wait.

**Comment by J0WI** [comment] 2016-10-13 16:10
> @J0WI you say here that FF 50 will be released "today". Looking at the release schedule, it looks like stable will be released on Nov 8.

Yes, I got the date from [here](https://wiki.mozilla.org/Features/Release_Tracking). Nov 8 seems right.

**Comment by Hainish** [comment] 2016-10-13 17:09
Closing issue as there is no actionable on our part.

**Closed by Hainish** 2016-10-13 17:09 UTC
Labels: firefox
