### ISSUE TITLE
Video breakage on theatlantic.com

### ISSUE THREAD

**Issue by tancrackers** [EFForg/https-everywhere#4105] opened 2016-02-06 19:18 UTC
Video:
http://www.theatlantic.com/video/index/424995/autism-in-love-dating-and-courtship-on-the-spectrum/

Filter:
The Atlantic (partial)

**Comment by Hainish** [comment] 2016-02-09 20:43
@tancrackers do you happen to have Privacy Badger installed? I can't reproduce this unless I have PB installed as well.

**Comment by Hainish** [comment] 2016-02-09 20:51
cc @cooperq

**Comment by tancrackers** [comment] 2016-02-10 02:30
I have uBlock Origin instaled, default deny to third party scripts.
I should have accounted for that. However, I enabled The Atlantic in https-everywhere today and the video now plays.

**Comment by funkydude** [comment] 2016-02-20 20:33
@tancrackers If it's not an HTTPS Everywhere issue then close it please.

**Closed** 2016-02-20 21:34 UTC
