### ISSUE TITLE
Firefox 42 now requires signed extension, blocks HTTPS Everywhere on upgrade

### ISSUE THREAD

**Issue by shuhaowu** [EFForg/https-everywhere#2467] opened 2015-08-06 15:45 UTC
HTTPS everywhere is getting automatically disabled now with Firefox nightly. See https://wiki.mozilla.org/Addons/Extension_Signing for details.

I understand the review process for Firefox addons is not great, but is there something the EFF can do with Mozilla?

**Comment by Rudloff** [comment] 2015-08-06 17:10
The workaround is to set ```xpinstall.signatures.required``` to false (but this is clearly not optimal).

**Comment by numismatika** [comment] 2015-08-07 20:32
I would say this duplicates #2051

**Comment by jsha** [comment] 2015-08-10 19:04
Agreed. Closing as duplicate of #2051, thanks.

**Closed** 2015-08-11 14:52 UTC
