### ISSUE TITLE
[Feature Request] Separate Repository For Rules

### ISSUE THREAD

**Issue by zero77** [EFForg/https-everywhere#16440] opened 2018-08-31 11:59 UTC
Is it Worth creating a separate repository for rules and issues relating to rules, and leave this repository for the development of the https-everywhere addon its self.

That way it may make managing and development a bit easier.
Thanks

**Comment by Bisaloo** [comment] 2018-09-01 05:42
Thanks for opening this issue. I'm closing it as duplicate of #2697.

**Closed by Bisaloo** 2018-09-01 05:42 UTC
