### ISSUE TITLE
mailing.sbb.ch refuses connection on port 443

### ISSUE THREAD

**Issue by Siguza** [EFForg/https-everywhere#6837] opened 2016-09-10 21:22 UTC
mailing.sbb.ch is included in the [Swiss Federal Railways rule](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/Swiss-Federal-Railways.xml#L38) to upgrade from HTTP to HTTPS, but mailing.sbb.ch (currently resolving to 195.191.132.115 for me) does not accept connections on port 443 at all.

I believe it should therefore be excluded from the upgrade rule.
(Is that as simple as removing it from the XML file?)

**Comment by jeremyn** [comment] 2016-09-10 23:18
I can confirm with netcat that `mailing.sbb.ch` isn't listening on port 443.

Yes, just delete [the `mailing.sbb.ch` line](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/Swiss-Federal-Railways.xml#L38) from the XML file.

Please feel free to submit a pull request. If you do, please refer to this issue.

**Comment by jeremyn** [comment] 2016-09-10 23:40
Closing issue because I've merged pull request #6838 .

**Closed by jeremyn** 2016-09-10 23:40 UTC
