### ISSUE TITLE
Refactor some of our js files

### ISSUE THREAD

**Issue by pde** [EFForg/https-everywhere#274] opened 2014-05-08 00:31 UTC
In particular:
- there's a growing amount of file IO logic in src/chrome/content/code/HTTPSRules.js that probably shouldn't be there
- the cert whitelist management code in src/components/ssl-observatory.js could arguably be in its own file

**Comment by jsha** [comment] 2015-01-22 18:38
Additionally: A lot of the code to manage ApplicableLists is actually in toolbar_button.js, which is an issue on Android, since toolbar_button.js doesn't get included there.

**Comment by J0WI** [comment] 2017-08-09 21:36
This might get obsolete during the migration to WebExtensions.

**Comment by koops76** [comment] 2017-08-09 22:21
Duplicate of #11637, #10852, #10909, #10931, #10932 and others.

**Comment by koops76** [comment] 2017-08-09 22:23
@J0WI This code is going to be removed during the WebExtensions transition. Close this I guess.

**Comment by gloomy-ghost** [comment] 2017-09-01 09:27
It's already removed

**Closed by gloomy-ghost** 2017-09-01 09:27 UTC
Labels: enhancement, webextensions-firefox
