### ISSUE TITLE
Internet.org web font doesn't load

### ISSUE THREAD

**Issue by andreasbovens** [EFForg/https-everywhere#349] opened 2014-07-03 12:11 UTC
When the HTTPS Everywhere extension is turned on (in Opera), the web font on http://internet.org/projects doesn't load.

Once the extension is disabled, everything works fine again.

**Comment by julianladisch** [comment] 2015-02-21 17:07
What is the URL of the font that http://internet.org/projects tries to load?  I cannot reproduce the problem.

**Comment by KommX** [comment] 2015-04-22 11:29
Is this bug really still open? I can't reproduce.

**Comment by stevenmg** [comment] 2015-04-22 15:36
I am no longer able to reproduce the problem in Firefox 37 so it is probably safe to close it.

**Comment by semenko** [comment] 2015-04-22 20:11
Same.

**Closed by semenko** 2015-04-22 20:11 UTC
Labels: ruleset-bug
