### ISSUE TITLE
Nexus Mods Broken With HTTPS

### ISSUE THREAD

**Issue by ValiantBlade** [EFForg/https-everywhere#12505] opened 2017-09-10 03:55 UTC
Nexus Mods, has, for a while, has had issues with downloading in HTTPS. Needless to say, I would suggest the rule for Nexus Mods uses be changed.

An active demonstration is downloading anything from any page of the site, even if it's being downloaded using an NXM link (as can be seen with FISS: https://www.nexusmods.com/skyrim/mods/48265). I had discovered this when attempting to reinstall Skyrim STEP on my SSD, and this applies to every game on Nexus, which I tested quickly by grabbing a random mod off the frontpage for The Witcher 3 Nexus (WO Lighting Everywhere: https://www.nexusmods.com/witcher3/mods/2633/).

**Comment by RavenMind** [comment] 2017-09-10 07:05
Additionally, when forcing HTTPS at nexusmods.com attempting to use the search results in a Firefox warning: The information you have entered on this page will be sent over an insecure connection and could be read by a third party. Are you sure you want to send this information". This error message apparently can not be disabled, despite there being an about:config entry for it. Although this is the result of bad website design on the part of nexusmods, this is annoying enough to make me want to disable HTTPS Everywhere. I'm not sure there's even anything HTTPS everywhere can do to remedy this short of just whitelisting the site.

**Comment by cschanaj** [comment] 2017-09-10 12:58
duplicate of #11953 relate #11961

**Comment by jeremyn** [comment] 2017-09-10 15:02
I'm closing this as a duplicate of #11953 . Please feel free to add your comments to that issue.

**Closed by jeremyn** 2017-09-10 15:02 UTC
