### ISSUE TITLE
Implement all of HTTPS Finder functionality inside HTTPS-Everywhere

### ISSUE THREAD

**Issue by crisalis** [EFForg/https-everywhere#2718] opened 2015-08-29 15:35 UTC
HTTPS Finder is bound to die for several reasons and I think even some HTTPS-Everywhere developers use it.

**Comment by numismatika** [comment] 2015-08-29 16:46
It is a lot more likely to discover possible targets for a new rule or a changed rule, if you get an automated note while browsing the non-encrypted version of the site.

While i don't think a automated ruleset should be made without additional manual work, a notification "there is content you could encrypt" would be really helpfull.

I think something like https://addons.mozilla.org/de/firefox/addon/sixornot/ would be great, multi-colored status of the encryption for a certain object request in a tree-view.

States could be:
green: using TLS
red: can't be requested over TLS
orange: could be secured, but isn't
purple: could be used with TLS but uses a self signed or expired or otherwise not trusted certificate

**Comment by ldgbc** [comment] 2015-09-02 14:05
There seem to be little interest in adding these feature. It better to just hope for a HTTPS Finder fork as the original developer quit.

**Comment by foobar13373** [comment] 2015-09-03 14:27
I'd be very interested to see this implemented. HTTPS-E could have an option that let's you choose between: 
- "Finder off", just like now
- "Finder on (manually)", if on HTTP but HTTPS would be possible it shows a green dot telling us "hey, here is TLS possible", if user cliks on green light then it will reload the page with HTTPS
- "Finder on (auto)", like above, but it redirects automatically, but user can click on icon to force HTTP (for exampel if HTTPS has different content or breaks functionality)

I'd love to see this!

**Comment by numismatika** [comment] 2015-09-12 12:22
i wouldn't call it lack of interest, most of the people working on this are busy with getting letsencrypt into shape.

**Comment by stryx** [comment] 2015-09-23 13:42
Just wanted to say that I would also highly appreciate such functionality inside HTTPS-Everywhere.

**Comment by genodeftest** [comment] 2015-09-23 14:35
This might be a bad idea. See the FAQ for details: https://www.eff.org/https-everywhere/faq#faq-Why-use-a-whitelist-of-sites-that-support-HTTPS?-Why-can%27t-you-try-to-use-HTTPS-for-every-last-site,-and-only-fall-back-to-HTTP-if-it-isn%27t-available?

**Comment by Mikaela** [comment] 2015-09-23 14:39
I think this should be natural first step for browsers [with deprecating http}(https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/). Sadly no browser has done anything as far as I am aware and it would be nice if HTTPS Everywhere could do that.

**Comment by stryx** [comment] 2015-09-23 15:45
@genodeftest: I'm aware of these problems and I did not suggest to switch on such a finder-functionality by default. To me the suggestions above by @numismatika and @foobar13373 make sense as long as they are optional and inactive by default. Also, when somebody wants to activate the finder, there could be a warning showing the text from the FAQ.
However, I do understand that this is not a high priority issue.

**Comment by foobar13373** [comment] 2015-11-21 21:23
Combining this with "Block all HTTP requests" (which HTTPS-E already can) like suggested in #3230 is actually a pretty good idea. This could be added as a first step and in a later release release allow more fine-grained controlling.

**Comment by rugk** [comment] 2015-12-05 19:26
Possibly related to https://github.com/EFForg/https-everywhere/issues/2115

**Comment by rezad1393** [comment] 2016-05-05 17:02
https-finder in longer working with firefox last version.
I used self-signed one that worked before but now stopped working.

**Comment by pipboy96** [comment] 2019-03-28 20:04
Outdated, duplicate of #13041.

**Closed by pipboy96** 2019-03-28 20:04 UTC
