### ISSUE TITLE
Error in "Visa"-rule

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#4671] opened 2016-04-22 19:26 UTC
Visa.xml breaks the following link:
http://www.visa.com/atmlocator

**Comment by jeremyn** [comment] 2016-08-13 18:15
Pull request #6244 should resolve this issue.

**Comment by jeremyn** [comment] 2016-08-22 15:18
Pull request #6244 has been merged so I'm closing this issue, but @KommX please feel free to reopen this issue and add a comment if the issue isn't fixed for you.

**Closed by jeremyn** 2016-08-22 15:18 UTC
Labels: Good Volunteer Task, ruleset-bug
