### ISSUE TITLE
URLs that point to a PDF file do not get upgraded to HTTPS

### ISSUE THREAD

**Issue by Gitoffthelawn** [EFForg/https-everywhere#17708] opened 2019-04-08 09:43 UTC
Type: code issue

URLs that point directly to a PDF file do not get upgraded from HTTP to HTTPS, even when all other URLs on the host get upgraded by HTTPS Everywhere.

This appears to happen on most sites that accept HTTP connections.

**Comment by pipboy96** [comment] 2019-04-08 10:02
@Gitoffthelawn Which browser? Do you have a test URL?

**Comment by Gitoffthelawn** [comment] 2019-04-08 19:01
@pipboy96 Firefox 66.0.2 64-bit

Here's an example url:
http://www-thphys.physics.ox.ac.uk/people/JamesBinney/qb.pdf

**Comment by pipboy96** [comment] 2019-04-08 19:46
@Gitoffthelawn Have you tried with Chrome?

**Comment by Gitoffthelawn** [comment] 2019-04-08 22:44
@pipboy96  Nope.  I'm Google-free.

**Comment by pipboy96** [comment] 2019-04-08 23:45
@Gitoffthelawn I will try this URL tomorrow then.

**Comment by pipboy96** [comment] 2019-04-09 01:24
I can't reproduce this with either FF Nightly, Chrome or Tor Browser. Most likely reason is ruleset being disabled by default ([Ox.ac.uk-falsemixed.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Ox.ac.uk-falsemixed.xml)). Closing unless another test URL exists.

**Comment by Gitoffthelawn** [comment] 2019-04-09 02:37
@pipboy96 As requested, here are 3 additional examples:

1.  http://physics.bgu.ac.il/~gedalin/Teaching/Mater/am.pdf
2.  http://webhome.phy.duke.edu/~rgb/Class/intro_physics_1/intro_physics_1.pdf
3.  http://web.pdx.edu/~pmoeck/lectures/Modern%20Physics%20for%20Science%20and%20Engineering%20(eval).pdf

**Comment by pipboy96** [comment] 2019-04-09 14:01
None of these domains have HTTPS Everywhere rules, thus not being rewritten by default. The first one redirects to HTTPS on its own but not on the PDF URL. You can enable EASE to make HTTPS Everywhere attempt to rewrite each URL.

**Closed by pipboy96** 2019-04-09 14:01 UTC
Labels: bug
