### ISSUE TITLE
the rule for dvd.netflix.com is broken

### ISSUE THREAD

**Issue by okrick** [EFForg/https-everywhere#5645] opened 2016-07-14 18:14 UTC
When I click on dvd.netflix.com with httpsEverywhere enabled I get a repeating url of perhaps 500 characters.  In Firefox the screen is blank.  In Chrome and Chromebook the sequence repeats twice then the screen shows a bad gateway 503 error.  There is no option to disable the rule for dvd.netflix.com.  The only way to visit the url is to turn off Everywhere globally.

The other areas of Netflix.com operate normally.

**Comment by J0WI** [comment] 2016-07-15 15:06
duplicate of #5117

**Closed by J0WI** 2016-07-15 15:06 UTC
