### ISSUE TITLE
feature request Rulesets As A Subscription

### ISSUE THREAD

**Issue by zero77** [EFForg/https-everywhere#12956] opened 2017-10-04 13:16 UTC
Can you please implement rulesets as a subscription.

For example, in the same way ublock, adguard and other ad blockers update their block rules by a subscription from github or elsewhere that is automatically updated every number of hours.

This would make it easier to submit fixes and new rules without having to push a new https-everywhere add-on each time, this is also lightly to make life a little easier for developers.

Thanks

**Comment by bardiharborow** [comment] 2017-10-04 13:21
Pretty much a duplicate of #12606.

**Comment by zero77** [comment] 2017-10-04 13:26
@bardiharborow 
Correct me if I am wrong but I don’t think it is, PR #12606 is asking not to have a subscription based update and this is.

**Comment by Bisaloo** [comment] 2017-10-04 13:51
Duplicate of https://github.com/EFForg/https-everywhere/issues/4380, related to https://github.com/EFForg/https-everywhere/issues/2605 and #12606 (as @bardiharborow said).

**Comment by koops76** [comment] 2017-10-04 17:29
Similar, but I think @zero77 wants to be able to add their own rulesets from an external list.

**Comment by jeremyn** [comment] 2017-10-05 18:23
@zero77 Issue https://github.com/EFForg/https-everywhere/issues/12606 is a general discussion about these updates, which I personally don't want, but if you want them then please add your support for them in that issue.

**Closed by jeremyn** 2017-10-05 18:23 UTC
