### ISSUE TITLE
Problem with potentiallyApplicableRuelsets / "rs is null" exception

### ISSUE THREAD

**Issue by pde** [EFForg/https-everywhere#1933] opened 2015-06-16 01:57 UTC
Testing from git, I'm seeing the following errors in the Firefox developer console:

HTTPS Everywhere WARN: Malformed host passed to potentiallyApplicableRulesets: 
**rs is null**  [HTTPSRules:line 514](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/code/HTTPSRules.js#l514)

**Comment by jsha** [comment] 2015-07-10 01:35
I can't reproduce. More details?

**Comment by gloomy-ghost** [comment] 2017-09-01 09:35
Closing as we are moving to WebExtension

**Closed by gloomy-ghost** 2017-09-01 09:35 UTC
Labels: bug, firefox, question
