### ISSUE TITLE
Display the reason why a rule is greyed out

### ISSUE THREAD

**Issue by numismatika** [EFForg/https-everywhere#10365] opened 2017-06-13 12:36 UTC
As far as i know the addon disables rulesets itself if they lead to redirect loops or otherwise cause problems.
You can also disable them yourself.
If the first case is true, shouldn't we collect the troubled urls and what exactly the problem was so that we can revisit them and fix it?
It would help to review the cases if we knew if that was "manually disabled, disabled by default, got disabled because it failed on http://example.org/images/sample-picture.jpg due to redirect loop, 404 error, something else"

**Comment by cschanaj** [comment] 2017-06-13 13:06
Possibly related: https://github.com/EFForg/https-everywhere/issues/9906#issuecomment-301373827

**Comment by jeremyn** [comment] 2017-06-13 14:50
@numismatika Are you suggesting we collect some kind of telemetry from users? I agree that would be really helpful but unfortunately this project is sort, by its nature, hostile to collecting data from users.

**Comment by numismatika** [comment] 2017-06-14 05:22
The intention was rather a locally collected info for the user only.
Depending on how much he cares and his experience,he can then ignore it, make a more useful report or fix it with a pull request.

My example would be various google rules that i enable manually and grey out half a week later and i have no idea why that happened.

**Comment by pipboy96** [comment] 2019-03-28 19:48
Partial duplicate of #13041.

**Closed** 2021-06-28 21:43 UTC
Labels: ui
