### ISSUE TITLE
Breaks login on https://www.anthem.com

### ISSUE THREAD

**Issue by lamahmud** [EFForg/https-everywhere#2431] opened 2015-08-05 14:33 UTC
The ruleset causes a redirect loop on https://www.anthem.com  It also causes several icons not to appear.  However, once disabled, all pictures/icons etc appear fine.  Here are screenshots, with and without https everywhere enabled.

![screen shot 2015-08-05 at 10 31 57 am](https://cloud.githubusercontent.com/assets/1789369/9088290/46100070-3b5d-11e5-9105-3950f96173e0.png)

![screen shot 2015-08-05 at 10 32 11 am](https://cloud.githubusercontent.com/assets/1789369/9088291/4611fd4e-3b5d-11e5-87c8-e8f3fabeffec.png)

**Comment by Manouchehri** [comment] 2015-08-06 05:42
I searched through the repo and didn't see any ruleset for www.anthem.com. They're the ones that are forwarding to `https://`, not HTTPS Everywhere.

```
~ > curlh http://www.anthem.com
HTTP/1.1 301 Moved Permanently
Location: https://www.anthem.com/health-insurance/home/overview
Server: BigIP
Content-Length: 0
Date: Thu, 06 Aug 2015 05:33:13 GMT
Connection: keep-alive
```

I can't reproduce the issue either. With a few uBlock lists the only thing that HTTPS Everywhere is touching is Google Services Simple; I also tried it without any blocking.

![2015-08-06-01 32 45-screenshot](https://cloud.githubusercontent.com/assets/7232674/9104509/59e0d5ec-3bdb-11e5-825f-f038a6018085.png)
![2015-08-06-01 32 33-screenshot](https://cloud.githubusercontent.com/assets/7232674/9104510/5a27ea72-3bdb-11e5-862f-6606e8743025.png)

I'm also forcing no mixed content with my browser, so that probably isn't an issue either.

**Comment by semenko** [comment] 2015-12-17 20:28
[Works for me, + comments above suggest OK]

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if you think it's still a bug.

**Closed by semenko** 2015-12-17 20:28 UTC
Labels: ruleset-bug
