### ISSUE TITLE
Remove ruleset for myfitnesspal.com

### ISSUE THREAD

**Issue by mvhirsch** [EFForg/https-everywhere#11941] opened 2017-08-16 07:56 UTC
Hi, something I would never recommend, but please remove the redirection ruleset to HTTPS for myfitnesspal.com.
The reason is simple: myfitnesspal.com supports HTTPS _only_ on it's homepage: https://www.myfitnesspal.com
But after logging into it's service, they're forcing a redirect to HTTP (unsecure). So a typical login on looks like the following:

1. Open http://www.myfitnesspal.com
2. Redirect to https://www.myfitnesspal.com (by https-everywhere)
3. Login using private credentials (successfully)
4. Redirect to http://www.myfitnesspal.com/private/member/area (by myfitnesspal)
5. Redirect to https://www.myfitnesspal.com/private/member/area (by https-everywhere)
6. Repeat steps 4-5 until browser refuses to follow (circuit breaker)

This renders using myfitnesspal useless. Disabling https-everywhere works, but then I disable the whole plugin :-(

Could you please remove the rule for myfitnesspal.com (until they manage to use HTTPS in their private member area too)?

**Comment by koops76** [comment] 2017-08-16 09:24
@mvhirsch https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/MyFitnessPal.com.xml

We do not have a `www` target. Not sure what is causing the redirect for you.

**Comment by mvhirsch** [comment] 2017-08-16 09:35
@koops76 it doesn't depend on `www.`. Requesting http://myfitnesspal.com will redirect to http://www.myfitnesspal.com (triggered by myfitnesspal).
The problem is, that after this redirect https-everywhere then redirects to https (which is fine too).

But after logging into the website, myfitnesspal forces a http (unsecure), but https-everywhere kicks in again and redirects to https ... causing an infinite loop.
Disabling the plugin solves the problem temporary.

**Comment by cschanaj** [comment] 2017-08-16 09:38
duplicate of #11029, fixed in #11033. this problem should be resolved when `2017.8.15` is released.

**Comment by J0WI** [comment] 2017-08-17 01:09
closed by #11033

**Closed by J0WI** 2017-08-17 01:09 UTC

**Comment by mvhirsch** [comment] 2017-08-18 09:53
Thank you very much! I will test it as soon as the update gets available for firefox :-)
