### ISSUE TITLE
"Block all unencrypted requests" is broken in Chrome

### ISSUE THREAD

**Issue by aemxdp** [EFForg/https-everywhere#12075] opened 2017-08-24 06:09 UTC
When you turn it on for the first time, it works. When you restart browser, it's not. Icon is blue, but the checkbox is checked. If you uncheck the checkbox and then check it back, it works again.

HTTPS Everywhere (Version: 2017.8.19)
Chrome Version 60.0.3112.101 (Official Build) (64-bit)

**Comment by Bisaloo** [comment] 2017-08-25 07:07
Duplicate of https://github.com/EFForg/https-everywhere/issues/10478.

**Closed** 2017-08-25 11:42 UTC
