### ISSUE TITLE
ESA.int videos not loading

### ISSUE THREAD

**Issue by MDawg957** [EFForg/https-everywhere#7243] opened 2016-09-30 20:15 UTC
http://www.esa.int/spaceinvideos/Videos

You get an "Error loading skin: Error loading file" error message on some videos on the site.

http://www.esa.int/spaceinvideos/Videos/2016/09/Once_upon_a_time_mission_complete can be used as an example.

Disabling ESA.int (partial) fixes the problem.

**Comment by jeremyn** [comment] 2016-10-01 00:13
I can reproduce this problem with Windows 10, Firefox 49.0.1, and HTTPS Everywhere 5.2.5 with the "Once upon a time" URL given. Note that it looks like if your browser window isn't large enough, the URL redirects to http://m.esa.int/spaceinvideos/Videos/2016/09/Once_upon_a_time_mission_complete , which doesn't trigger [the `ESA.int (partial)` rule](https://github.com/EFForg/https-everywhere/blob/375124aa311c82db8c87c1882c41b082da4b84a4/src/chrome/content/rules/European_Space_Agency.xml).

**Comment by gitarra** [comment] 2016-12-12 16:25
Why not disable the ruleset until someone fixes the issue? Since no one bothers users get served broken content for months.

**Comment by jeremyn** [comment] 2016-12-12 22:56
@gitarra Issue https://github.com/EFForg/https-everywhere/issues/7338 is a previous discussion on disabling rulesets that might answer your question.

**Comment by gitarra** [comment] 2016-12-13 14:01
This is not a CDN, so should be disabled according to that discussion?

**Comment by jeremyn** [comment] 2016-12-13 14:56
That issue did wander around a little. More specifically, see what I wrote in https://github.com/EFForg/https-everywhere/issues/7338#issuecomment-253545383:

>I disagree that we should bulk disable rules just because no one has fixed an issue with them yet, especially these complex CDN rules that span multiple sites in unclear ways (see `#4510 (comment)`). Unfortunately the people who can decide that a rule is safe to disable are the same ones who are able to fix it, and the problem is we don't have enough of those people looking at issues.

> It's also a security concern. Perhaps I'm a malicious actor and want to disable a ruleset for one of these domains, so I report a fake issue with some other domain in the ruleset, with a problem that sounds tricky and hard-to-reproduce. Eventually I pressure the maintainers (us) to disable the entire ruleset until my fake issue is resolved, which will never happen.

**Comment by gitarra** [comment] 2016-12-14 13:53
This is not a CDN, this is not a fake report since it has been verified and this has gone unfixed for months. So according to your quoted comment this ruleset should be disabled.

The issue here is that ESA.int doesnt specify CORS origin header and the request for the player skin gets blocked because of it.

**Comment by jeremyn** [comment] 2016-12-14 16:05
The quote shouldn't be read to say that non-CDN rulesets should be disabled. Anyway I'm not interested in arguing over the semantics of my own quote.

The basic problem is that this project is very understaffed, particularly for people with commit access. Look at the number of people who have merged commits in the past month or so, the number of merges, and the number of open issues and pull requests, and you'll understand what I mean. Either disabling or fixing a ruleset requires a pull request that has to be reviewed and merged by one of the limited number of people with commit access. Speaking for me personally, if you submitted a pull request to disable this ruleset and I was reviewing it, I would ask you to instead fix the underlying problem or explain why it's too difficult to fix. Maybe one of the other reviewers would feel differently. You're welcome to try submitting either type of pull request.

**Comment by jeremyn** [comment] 2016-12-14 16:09
Also, to be clear, some of the "staff" you see in the commit history, like me, are unpaid volunteers. The actual paid staff at EFF has tremendous demands on their time outside of this project.

**Comment by gitarra** [comment] 2016-12-14 16:21
I know, but for a fraction of the effort gone into this conversation the ruleset could have been disabled already.

I fixed this already here https://github.com/gitarra/https-everywhere/commit/8231c5994d720af4eb90643b48d140f60c6025eb but I messed it up and I cant figure out how to PR only that commit into here now. I'm not familiar with git and the web interface here on github is confusing.

And just to be clear AFAICT this cannot be fixed without website changes because it is a CORS issue. The only fix possible here is to disable the ruleset, there is no other solution if you dont take into account tech evangelism by contacting the webmaster.

**Comment by jeremyn** [comment] 2016-12-14 16:39
I'm not talking about just this issue, but about the hundreds of other issues too.

As an example of the review needed: the issue was reported against https://www.esa.int/spaceinvideos/Videos, not the whole domain, so at most we should add an `exclusion` for just this URL and not disable the entire ruleset. That requires verification though, and at that point we are basically fixing the problem anyway.

**Comment by gitarra** [comment] 2016-12-14 16:52
Ok. I appreciate your stance is that rulesets are allowed to (supposed to?) break websites.

Still I will argue that I cannot understand the value in causing users repeated grief and annoyance, without really providing any additional value.

**Comment by jeremyn** [comment] 2016-12-14 21:44
I think you are still misunderstanding, and I'm sorry if my explanations haven't been good enough. Rulesets are not supposed to break websites. This issue is a bug and it should be fixed. The question you asked is why not just shut the ruleset down entirely until the bug is fixed. My answer is that I'm not going to disable this ruleset without review, and reviewing takes time, and if I'm going to spend the time then I might as well fix the actual problem. Since I'm not willing to spend time on this either way, the ruleset stays as it is.

On the other hand I'm willing to have this discussion with you so that you and all other contributors understand the decision-making process, because I hope that will give better outcomes, not just for this issue, but for all the other issues and the project as a whole.

**Comment by J0WI** [comment] 2018-06-15 17:04
This issue is not reproducible anymore and the rule is off by default.

**Closed by J0WI** 2018-06-15 17:04 UTC
Labels: good volunteer task, ruleset-bug
