### ISSUE TITLE
Amazon Prime Instant Video is reportedly broken

### ISSUE THREAD

**Issue by pde** [EFForg/https-everywhere#1578] opened 2015-04-24 22:30 UTC

**Comment by fnkr** [comment] 2015-04-25 17:32
I can confirm that Amazon Prime Instant Video does not work if the Cloudfront rule is enabled and Flash player is used for Streaming (Silverlight works for me). It is very likely that all Amazon Instant Video streams are affected, not just Prime but I havent tried.

**Comment by J0WI** [comment] 2016-08-14 13:43
closed by #4997

**Closed by J0WI** 2016-08-14 13:43 UTC
Labels: ruleset-bug
