### ISSUE TITLE
"Block all unencrypted requests" Issue on start up

### ISSUE THREAD

**Issue by JohnDoeInTheSnow** [EFForg/https-everywhere#12070] opened 2017-08-23 16:43 UTC
When I open Chrome (without any other "chromes" open) the "S" icon starts as blue, flashes red, then is back to blue. When I click on the icon, "Block all unencrypted requests" is checked, but I am still able to go to encrypted sites. (I just search "news" and go to www.bbc.com/news to test this)

If I uncheck and re-check the box (block all unencrypted requests) and reload the site (www.bbc.com/news), the site will then be blocked. I am not sure what is the cause of this, and I have even re-downloaded the plugin, but the problem persists.

Does anyone have any ideas?

**Comment by Bisaloo** [comment] 2017-08-23 19:53
Duplicate of https://github.com/EFForg/https-everywhere/issues/10478.

**Closed** 2017-08-24 00:04 UTC
