### ISSUE TITLE
"This extension may have been corrupted."

### ISSUE THREAD

**Issue by HalinReno** [EFForg/https-everywhere#6725] opened 2016-09-02 00:03 UTC
As of Version 53.0.2785.89 beta (64-bit) I get the message "This extension may have been corrupted." in the extensions screen. Repair or reinstalling does not fix the issue. My not be helpful but I also get this error for privacy badger as well. Let me know if you need anything such as logs, etc. Thank you.

Also, running Antergos w/MATE 64 bit

**Comment by rentamob** [comment] 2016-09-02 06:21
I'm also having this issue with Chrome version 53.0.2785.89 (64-bit) in Linux.

**Comment by Grinderz** [comment] 2016-09-02 11:15
Chrome Version 53.0.2785.89 (64-bit)
extension version 2016.9.1

have same issue

**Comment by anand-bhat** [comment] 2016-09-02 14:56
Same here. Clicking repair fixed it on one system but not in the other.

Chrome: Version 53.0.2785.89 m (64-bit)
OS: Windows 10

![image](https://cloud.githubusercontent.com/assets/7332442/18208021/547df94e-714b-11e6-8b43-49bfca11ba38.png)

**Comment by xrisk** [comment] 2016-09-02 15:02
Same issue on Chrome 53 (OS X).

**Comment by fuglede** [comment] 2016-09-02 17:24
Thanks for the report. This one is a duplicate of #5874.

**Comment by jeremyn** [comment] 2016-09-02 21:46
I'm closing this because it's a duplicate as @fuglede said. Please feel free to add further reports or feedback to #5874 as needed.

**Closed by jeremyn** 2016-09-02 21:46 UTC

**Comment by Pysis868** [comment] 2016-11-10 19:37
Just had the issue today (11/10/2016).  Will check the new thread in #7456 since #5874 is now closed, in case it is a different root cause.

**Comment by bobsage123** [comment] 2017-01-06 19:56
Currently getting this on 1/6/2017 on 56.0.2924.51 beta (64-bit) and the latest HTTPs everywhere from the chrome store.
