### ISSUE TITLE
marketo.com login not working

### ISSUE THREAD

**Issue by alexandergitter** [EFForg/https-everywhere#1179] opened 2015-03-10 13:57 UTC
Using 4.0.3, I can't login at https://login.marketo.com/. After pressing the Login button, it looks like I'm being redirected back to the login form.

It works fine if I disable the Marketo rule.

**Comment by 2d1** [comment] 2015-03-16 23:29
Could you test whether this is the case with 5.0development.3, please.

If it is, then could you list the cookies set during login, please. You can find these in Firefox's Network tab (Ctrl+Alt+Q).

Of particular interest is whether the secure and httpOnly attributes are set differently.

**Comment by alexandergitter** [comment] 2015-03-18 09:06
The following cookies are being set when I login to Marketo:

symfony:
  path:"/"
  
symfony:
  path:"/"
  secure:true
  httpOnly:true

ids_sso:
  path:"/"
  domain:"marketo.com"
  secure:true
  httpOnly:true

_ved_rsu_...:
  path:"/"
  domain:".marketo.com"
  secure:true

rememberUserId:
  path:"/"
  domain:".marketo.com"

mkto_pod:
  path:"/"
  domain:".marketo.com"
  secure:true
  httpOnly:true

**Comment by 2d1** [comment] 2015-03-18 11:45
@alexandergitter could you check for differences from those values in the cookie manager, please. Note that for Firefox, private browsing must be disabled to view stored cookies.

If I had to guess, it'd be rememberUserId being read from a script after we set httpOnly on it.

**Comment by alexandergitter** [comment] 2015-03-18 13:05
The only change seems to be that rememberUserId is set to secure.

**Comment by J0WI** [comment] 2015-07-14 16:05
seems to be obsolete.
#closeme

**Comment by jsha** [comment] 2015-07-14 19:10
@J0WI can you say more about why you think it is obsolete? Looks like the marketo rule is still enabled, but I don't have a login to test with.

**Comment by Ellipsis753** [comment] 2015-08-12 16:38
I can say that this is still outstanding. I had this issue just now.

Kind regards,
Shanee Vanstone.

**Comment by J0WI** [comment] 2015-08-12 23:26
I thought that this has been fixed by https://github.com/EFForg/https-everywhere/commit/db1cf12d9ecbc340f112ca042eca765e926fd1c2

**Comment by Ellipsis753** [comment] 2015-08-13 05:49
Ah. Sorry. I mean to say that I can confirm that login does not work on new Firefox with:
https://addons.mozilla.org/en-us/firefox/addon/https-everywhere/

It's possible the above commit fixes this if it's not live yet.

**Comment by bardiharborow** [comment] 2017-10-13 13:58
@J0WI I think this is closable.

**Closed** 2017-10-13 21:19 UTC
Labels: ruleset-bug
