### ISSUE TITLE
Issue on bahn.de

### ISSUE THREAD

**Issue by KommX** [EFForg/https-everywhere#3297] opened 2015-11-26 14:53 UTC
http://www.bahn.de/p/view/bahncard/bahnbonus/praemiengewinnspiel.shtml doesn't work with rule "Bahn.de" enabled.

**Comment by numismatika** [comment] 2015-11-28 15:39
Yes because it embeds external content from www.app-coding.de in an iframe which usually gets blocked by the browser for being active mixed content.
#3334 adds a new ruleset for that coding company, but https://bugzilla.mozilla.org/show_bug.cgi?id=878890 is still being worked on.

**Comment by fuglede** [comment] 2015-11-28 20:01
Looks like [their contact page](https://www.bahn.de/q?s=faq|pk/DEU/de&l=de&c=DEU&n=7&t=2&dbkanal_007=L01_S01_D001_KIN0001_Kontakt_LZ01) also has issues; to reproduce, try clicking 'Kontakt zu www.bahn.de'. Expected behavior is a dropdown menu which does not appear.

**Comment by KommX** [comment] 2015-11-28 20:21
@fuglede that works for me

**Comment by fuglede** [comment] 2015-11-28 20:30
@KommX Thanks for checking; seems that it is indeed working, and that another plugin was interfering. Disregard my previous comment.

**Comment by numismatika** [comment] 2015-12-19 13:50
@KommX does it still happen after #3334 got merged?

**Comment by KommX** [comment] 2015-12-19 18:27
@numismatika The link I mentioned in the first post is now redirected to the main page, so I can't really tell.

**Comment by semenko** [comment] 2016-01-20 03:09
Appears fixe per above commits.

Closing, as this issue may be resolved or invalid with the latest version of the extension. Feel free to reopen or send a pull request if this is still a bug.

**Closed by semenko** 2016-01-20 03:09 UTC
Labels: ruleset-bug
