### ISSUE TITLE
Firefox 41b1 OSX deactivates https everywhere

### ISSUE THREAD

**Issue by magnusmanske** [EFForg/https-everywhere#2552] opened 2015-08-13 19:44 UTC
Something about the add-on not signed by Mozilla. Re-adding from EFF or Mozilla both failed.

Not sure who needs to fix what, just thought I'd let you know.

**Comment by jsha** [comment] 2015-08-13 19:47
Duplicate of #2051. We're working on it! Thanks for reporting.

**Closed** 2015-08-14 07:56 UTC
