### ISSUE TITLE
Detect if there are infinite redirection loops and show popup to user suggesting to disable the relevant ruleset

### ISSUE THREAD

**Issue by HTTPSNowhere** [EFForg/https-everywhere#11047] opened 2017-07-13 12:02 UTC
In some instances, a bad ruleset may lead to an infinite loop of http->https->http->https->...

A good way to have the user fix this problem himself is to detect if there are infinite redirection loops and show popup to user suggesting to disable the relevant ruleset.

```
We detected that a ruleset was causing redirection loops, you can: [Disable] [Cancel] 
```

Not sure however if the detection part may be possible as a WebExtension.

**Comment by koops76** [comment] 2017-07-14 11:33
I think the Chromium extension already does something similar, but without warning the user.

See https://github.com/EFForg/https-everywhere/blob/master/chromium/background.js#L556

**Comment by pipboy96** [comment] 2019-03-28 19:46
Duplicate of #10477.

**Closed by pipboy96** 2019-03-28 19:46 UTC
