### ISSUE TITLE
How about merge darkweb into this addon?

### ISSUE THREAD

**Issue by yoursoftwarebug** [EFForg/https-everywhere#9713] opened 2017-04-30 00:02 UTC
https://github.com/chris-barry/darkweb-everywhere

New option:
[X] Activate .onion redirection if available

**Comment by Bisaloo** [comment] 2017-04-30 07:43
Duplicate of https://github.com/EFForg/https-everywhere/issues/3798

**Closed** 2017-04-30 14:58 UTC
