### ISSUE TITLE
senate.gov broken

### ISSUE THREAD

**Issue by anewuser** [EFForg/https-everywhere#3028] opened 2015-10-02 02:06 UTC
HTTPS Everywhere redirects http://www.senate.gov/ to https://www.senate.gov/ , which says that HTTPS is not supported at the moment.

**Comment by fuglede** [comment] 2015-10-02 10:15
Thanks for the report. This looks like a duplicate of #2596.

**Closed** 2015-10-02 22:18 UTC

**Comment by anewuser** [comment] 2015-10-02 22:20
@fuglede I've closed this, but it actually affects more subdomains than only "www".
