### ISSUE TITLE
HTTPS Everywhere WebExtension blocks video playback on Fox News

### ISSUE THREAD

**Issue by smartfonreddit** [EFForg/https-everywhere#13457] opened 2017-11-01 19:21 UTC
With the latest WebExtension installed, visit a Fox News link that only has a video and not an article, such as this one http://video.foxnews.com/v/5631922107001/?#sp=show-clips

The play button and the video never appear until HTTPS Everywhere is disabled.

EDIT:

Force encrypted connections to these websites:
Google APIs
Segment
Optimizely (partial)
ScorecardResearch.com
IMR Worldwide.com
KrxD.net
Demdex.net
Taboola (partial)
2mdn.net
Googletagservices.com
Chartbeat.com (partial)
Moat ads.com (partial)
Cxense.com
Chartbeat.net
Google.com Subdomains (Complex)
Everest Tech.net
Livefyre.com (partial)
Outbrain.com (partial)
RPXNow.com (partial)
Cloudfront.net
New Relic.com
NR-data.net
Google Services Simple
Akamai

EDIT:

Type: ruleset issue

Domain: video.foxnews.com

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment] 2017-11-02 14:26
@smartfonreddit  I can't test it since I get an "Access Denied" error, but does it work for you if you access the https version of that site namely https://video.foxnews.com/v/5631922107001/?#sp=show-clips ?

**Comment by gloomy-ghost** [comment] 2017-11-03 03:37
I can confirm that it is an CORS issue and the https version works

**Comment by smartfonreddit** [comment] 2017-11-03 04:11
@I-have-50-open-PRs-to-HTTPS-EVERYWHERE yes, your link with HTTPS works.

**Comment by I-have-50-open-PRs-to-HTTPS-EVERYWHERE** [comment] 2017-11-03 09:03
@smartfonreddit Also if you enable the ruleset `Fox News (partial)` when visiting the http version (click on the HTTPS Everywhere button and you can check it to enable it), do you get the redirect to the https version and does  the video work?

**Comment by ihave100openPRs** [comment] 2017-11-12 16:05
@gloomy-ghost This is a duplicate of https://github.com/EFForg/https-everywhere/issues/7721

**Closed** 2017-11-13 03:59 UTC
Labels: CORS-bugs
