### ISSUE TITLE
http://internt.slu.se/ will direct to https://internet.slu.se/ Please fix

### ISSUE THREAD

**Issue by jony0008** [EFForg/https-everywhere#7596] opened 2016-11-17 16:54 UTC
internt.slu.se does not direct correctly and breaks to https://internet.slu.se

**Comment by jony0008** [comment] 2016-11-17 17:07
internet.slu.se

**Comment by jeremyn** [comment] 2016-11-18 00:17
This is fixed by open pull request #7504 , which should resolve issue #7502 . So, I'm closing this issue as a duplicate of issue #7502 .

**Closed by jeremyn** 2016-11-18 00:17 UTC
